import { Actions } from "./models/permission/actions";
import { Resources } from "./models/permission/resources";

export const navigation = [
  {
    text: 'Navs.Home',
    icon: 'home',
    path: '',
    items: [
      {
        text: 'Navs.Home',
        path: '/home',
        permission:  Resources.Dashboard + '.' + Actions.View
      }
    ],
  },
  {
    text: 'Navs.Admin',
    icon: 'card',
    path: '',
    items: [
      {
        text: 'Navs.MainRoles',
        path: '/roles',
        permission: Resources.Roles + '.' + Actions.View
      },
      {
        text: 'Navs.Users',
        path: '/users',
        permission: Resources.Users + '.' + Actions.View
      },
       {
        text: 'Navs.Customers',
        path: '/customers',
        permission: Resources.Customers + '.' + Actions.View
      },
      {
        text: 'Navs.Brands',
        path: '/brands',
        permission: Resources.Brands + '.' + Actions.View
      }
    ],
  },
  {
    text: 'Navs.Payments',
    icon: 'money',
    path: '',
    items: [
      {
        text: 'Navs.PayEasy',
        path: '/payeasy',
        permission: Resources.Payments + '.' + Actions.PayEasy
      }
    ],
  },
  // =====================================================
  // VEM - Veri Entegrasyon Merkezi
  // =====================================================
  {
    text: 'Hasta Islemleri',
    icon: 'user',
    path: '',
    items: [
      { text: 'Hastalar', path: '/vem/hasta' },
      { text: 'Hasta Basvuru', path: '/vem/hasta-basvuru' },
      { text: 'Basvuru Tani', path: '/vem/basvuru-tani' },
      { text: 'Hasta Hizmet', path: '/vem/hasta-hizmet' },
      { text: 'Hasta Yatak', path: '/vem/hasta-yatak' },
      { text: 'Anlik Yatan Hasta', path: '/vem/anlik-yatan-hasta' },
      { text: 'Hasta Sevk', path: '/vem/hasta-sevk' },
      { text: 'Hasta Epikriz', path: '/vem/hasta-epikriz' },
      { text: 'Hasta Tibbi Bilgi', path: '/vem/hasta-tibbi-bilgi' },
      { text: 'Hasta Vital/Fiziki Bulgu', path: '/vem/hasta-vital-fiziki-bulgu' },
      { text: 'Hasta Iletisim', path: '/vem/hasta-iletisim' },
      { text: 'Hasta Fotograf', path: '/vem/hasta-fotograf' },
      { text: 'Hasta Notlari', path: '/vem/hasta-notlari' },
      { text: 'Hasta Uyari', path: '/vem/hasta-uyari' },
      { text: 'Hasta Gizlilik', path: '/vem/hasta-gizlilik' },
      { text: 'Hasta Adli Rapor', path: '/vem/hasta-adli-rapor' },
      { text: 'Hasta Arsiv', path: '/vem/hasta-arsiv' },
      { text: 'Hasta Arsiv Detay', path: '/vem/hasta-arsiv-detay' },
      { text: 'Hasta Olum', path: '/vem/hasta-olum' },
      { text: 'Hasta Ventilator', path: '/vem/hasta-ventilator' },
      { text: 'Hasta Seans', path: '/vem/hasta-seans' },
      { text: 'Klinik Seyir', path: '/vem/klinik-seyir' },
      { text: 'Hemsire Bakim', path: '/vem/hemsire-bakim' },
      { text: 'Risk Skorlama', path: '/vem/risk-skorlama' },
      { text: 'Risk Skorlama Detay', path: '/vem/risk-skorlama-detay' },
      { text: 'Randevu', path: '/vem/randevu' },
    ],
  },
  {
    text: 'Ameliyat & Cerrahi',
    icon: 'medkit',
    path: '',
    items: [
      { text: 'Ameliyat', path: '/vem/ameliyat' },
      { text: 'Ameliyat Ekip', path: '/vem/ameliyat-ekip' },
      { text: 'Ameliyat Islem', path: '/vem/ameliyat-islem' },
      { text: 'Konsultasyon', path: '/vem/konsultasyon' },
      { text: 'Dogum', path: '/vem/dogum' },
      { text: 'Dogum Detay', path: '/vem/dogum-detay' },
    ],
  },
  {
    text: 'Laboratuvar',
    icon: 'flask',
    path: '',
    items: [
      { text: 'Tetkik', path: '/vem/tetkik' },
      { text: 'Tetkik Sonuc', path: '/vem/tetkik-sonuc' },
      { text: 'Tetkik Numune', path: '/vem/tetkik-numune' },
      { text: 'Tetkik Parametre', path: '/vem/tetkik-parametre' },
      { text: 'Tetkik Referans Aralik', path: '/vem/tetkik-referans-aralik' },
      { text: 'Tetkik Cihaz Eslesme', path: '/vem/tetkik-cihaz-eslesme' },
      { text: 'Radyoloji', path: '/vem/radyoloji' },
      { text: 'Radyoloji Sonuc', path: '/vem/radyoloji-sonuc' },
      { text: 'Patoloji', path: '/vem/patoloji' },
      { text: 'Antibiyotik Sonuc', path: '/vem/antibiyotik-sonuc' },
      { text: 'Bakteri Sonuc', path: '/vem/bakteri-sonuc' },
    ],
  },
  {
    text: 'Kan Bankasi',
    icon: 'favorites',
    path: '',
    items: [
      { text: 'Kan Bagisci', path: '/vem/kan-bagisci' },
      { text: 'Kan Urun', path: '/vem/kan-urun' },
      { text: 'Kan Stok', path: '/vem/kan-stok' },
      { text: 'Kan Talep', path: '/vem/kan-talep' },
      { text: 'Kan Talep Detay', path: '/vem/kan-talep-detay' },
      { text: 'Kan Cikis', path: '/vem/kan-cikis' },
      { text: 'Kan Urun Imha', path: '/vem/kan-urun-imha' },
    ],
  },
  {
    text: 'Stok & Malzeme',
    icon: 'product',
    path: '',
    items: [
      { text: 'Stok Kart', path: '/vem/stok-kart' },
      { text: 'Stok Durum', path: '/vem/stok-durum' },
      { text: 'Stok Hareket', path: '/vem/stok-hareket' },
      { text: 'Stok Fis', path: '/vem/stok-fis' },
      { text: 'Stok Istek', path: '/vem/stok-istek' },
      { text: 'Stok Istek Hareket', path: '/vem/stok-istek-hareket' },
      { text: 'Stok Istek Uygulama', path: '/vem/stok-istek-uygulama' },
      { text: 'Stok EHU Takip', path: '/vem/stok-ehu-takip' },
      { text: 'Hasta Malzeme', path: '/vem/hasta-malzeme' },
      { text: 'Depo', path: '/vem/depo' },
    ],
  },
  {
    text: 'Sterilizasyon',
    icon: 'clearsquare',
    path: '',
    items: [
      { text: 'Sterilizasyon Giris', path: '/vem/sterilizasyon-giris' },
      { text: 'Sterilizasyon Cikis', path: '/vem/sterilizasyon-cikis' },
      { text: 'Sterilizasyon Yikama', path: '/vem/sterilizasyon-yikama' },
      { text: 'Sterilizasyon Set', path: '/vem/sterilizasyon-set' },
      { text: 'Sterilizasyon Set Detay', path: '/vem/sterilizasyon-set-detay' },
      { text: 'Sterilizasyon Paket', path: '/vem/sterilizasyon-paket' },
      { text: 'Sterilizasyon Paket Detay', path: '/vem/sterilizasyon-paket-detay' },
      { text: 'Sterilizasyon Stok Durum', path: '/vem/sterilizasyon-stok-durum' },
    ],
  },
  {
    text: 'Personel',
    icon: 'group',
    path: '',
    items: [
      { text: 'Personel', path: '/vem/personel' },
      { text: 'Personel Izin', path: '/vem/personel-izin' },
      { text: 'Personel Izin Durumu', path: '/vem/personel-izin-durumu' },
      { text: 'Personel Bordro', path: '/vem/personel-bordro' },
      { text: 'Personel Bordro Sondurum', path: '/vem/personel-bordro-sondurum' },
      { text: 'Personel Egitim', path: '/vem/personel-egitim' },
      { text: 'Personel Ogrenim', path: '/vem/personel-ogrenim' },
      { text: 'Personel Yandal', path: '/vem/personel-yandal' },
      { text: 'Personel Gorevlendirme', path: '/vem/personel-gorevlendirme' },
      { text: 'Personel Odul/Ceza', path: '/vem/personel-odul-ceza' },
      { text: 'Personel Banka', path: '/vem/personel-banka' },
      { text: 'Personel Bakmakla Yukumlu', path: '/vem/personel-bakmakla-yukumlu' },
      { text: 'Nobetci Personel Bilgisi', path: '/vem/nobetci-personel-bilgisi' },
    ],
  },
  {
    text: 'Kurul & Raporlar',
    icon: 'textdocument',
    path: '',
    items: [
      { text: 'Kurul', path: '/vem/kurul' },
      { text: 'Kurul Hekim', path: '/vem/kurul-hekim' },
      { text: 'Kurul Rapor', path: '/vem/kurul-rapor' },
      { text: 'Kurul Teshis', path: '/vem/kurul-teshis' },
      { text: 'Kurul Etken Madde', path: '/vem/kurul-etken-madde' },
      { text: 'Kurul Engelli', path: '/vem/kurul-engelli' },
      { text: 'Kurul Askeri', path: '/vem/kurul-askeri' },
    ],
  },
  {
    text: 'Saglik Izlemleri',
    icon: 'chart',
    path: '',
    items: [
      { text: 'Bebek Cocuk Izlem', path: '/vem/bebek-cocuk-izlem' },
      { text: 'Gebe Izlem', path: '/vem/gebe-izlem' },
      { text: 'Lohusa Izlem', path: '/vem/lohusa-izlem' },
      { text: 'Kadin Izlem', path: '/vem/kadin-izlem' },
      { text: 'Evde Saglik Izlem', path: '/vem/evde-saglik-izlem' },
      { text: 'Intihar Izlem', path: '/vem/intihar-izlem' },
      { text: 'Kuduz Izlem', path: '/vem/kuduz-izlem' },
      { text: 'Obezite Izlem', path: '/vem/obezite-izlem' },
      { text: 'Diyabet', path: '/vem/diyabet' },
      { text: 'Cocuk Diyabet', path: '/vem/cocuk-diyabet' },
      { text: 'Hemoglobinopati', path: '/vem/hemoglobinopati' },
      { text: 'Madde Bagimliligi', path: '/vem/madde-bagimliligi' },
    ],
  },
  {
    text: 'Recete & Ilac',
    icon: 'contentlayout',
    path: '',
    items: [
      { text: 'Recete', path: '/vem/recete' },
      { text: 'Recete Ilac', path: '/vem/recete-ilac' },
      { text: 'Recete Ilac Aciklama', path: '/vem/recete-ilac-aciklama' },
      { text: 'Optik Recete', path: '/vem/optik-recete' },
      { text: 'Tibbi Order', path: '/vem/tibbi-order' },
      { text: 'Tibbi Order Detay', path: '/vem/tibbi-order-detay' },
      { text: 'Ilac Uyum', path: '/vem/ilac-uyum' },
    ],
  },
  {
    text: 'Dis Islemleri',
    icon: 'pin',
    path: '',
    items: [
      { text: 'Hasta Dis', path: '/vem/hasta-dis' },
      { text: 'Dis Taahhut', path: '/vem/dis-taahhut' },
      { text: 'Dis Taahhut Detay', path: '/vem/dis-taahhut-detay' },
      { text: 'Dis Protez', path: '/vem/disprotez' },
      { text: 'Dis Protez Detay', path: '/vem/disprotez-detay' },
      { text: 'Ortodonti Icon Skor', path: '/vem/ortodonti-icon-skor' },
    ],
  },
  {
    text: 'Finans & Muhasebe',
    icon: 'money',
    path: '',
    items: [
      { text: 'Fatura', path: '/vem/fatura' },
      { text: 'Vezne', path: '/vem/vezne' },
      { text: 'Vezne Detay', path: '/vem/vezne-detay' },
      { text: 'Hasta Borc', path: '/vem/hasta-borc' },
      { text: 'Ek Odeme', path: '/vem/ek-odeme' },
      { text: 'Ek Odeme Detay', path: '/vem/ek-odeme-detay' },
      { text: 'Ek Odeme Donem', path: '/vem/ek-odeme-donem' },
      { text: 'Icmal', path: '/vem/icmal' },
    ],
  },
  {
    text: 'Tanimlar',
    icon: 'folder',
    path: '',
    items: [
      { text: 'Kurum', path: '/vem/kurum' },
      { text: 'Birim', path: '/vem/birim' },
      { text: 'Bina', path: '/vem/bina' },
      { text: 'Oda', path: '/vem/oda' },
      { text: 'Yatak', path: '/vem/yatak' },
      { text: 'Hizmet', path: '/vem/hizmet' },
      { text: 'Cihaz', path: '/vem/cihaz' },
      { text: 'Firma', path: '/vem/firma' },
      { text: 'Referans Kodlar', path: '/vem/referans-kodlar' },
    ],
  },
  {
    text: 'Sistem',
    icon: 'preferences',
    path: '',
    items: [
      { text: 'Kullanici', path: '/vem/kullanici' },
      { text: 'Kullanici Grup', path: '/vem/kullanici-grup' },
      { text: 'Grup Uyelik', path: '/vem/grup-uyelik' },
      { text: 'Silinen Kayitlar', path: '/vem/silinen-kayitlar' },
      { text: 'SYS Paket', path: '/vem/sys-paket' },
    ],
  },
  {
    text: 'Diger Islemler',
    icon: 'more',
    path: '',
    items: [
      { text: 'Asi Bilgisi', path: '/vem/asi-bilgisi' },
      { text: 'Basvuru Yemek', path: '/vem/basvuru-yemek' },
      { text: 'Bildirimi Zorunlu', path: '/vem/bildirimi-zorunlu' },
      { text: 'Doktor Mesaji', path: '/vem/doktor-mesaji' },
      { text: 'GETAT', path: '/vem/getat' },
      { text: 'Medula Takip', path: '/vem/medula-takip' },
    ],
  },
];
