// HastaAdliRapor Model Definitions
import { VemBaseDto, BaseListFilter } from './base.model';

export interface HastaAdliRaporDto extends VemBaseDto {
  hastaAdliRaporKodu: string;
  referansTabloAdi: string;
  hastaBasvuruKodu: string;
  hastaKodu: string;
  adliRaporTuru: string;
  raporZamani?: Date;
  adliMuayeneyeGonderenKurum: string;
  resmiYaziNumarasi: string;
  resmiYaziTarihi: Date;
  adliMuayeneEdilmeNedeni: string;
  guvenlikSicilNumarasi: string;
  guvenlikAdiSoyadi: string;
  olayZamani: Date;
  adliOlayOykusu: string;
  sikayet: string;
  ozgecmisi: string;
  soygecmisi: string;
  muayeneZamani: Date;
  hekimKodu: string;
  tibbiMudahale: string;
  uygunSartSaglanmaDurumu: string;
  uygunSartAciklama: string;
  elbiseDurumu: string;
  konsultasyonBilgisi: string;
  lezyonBulgulari: string;
  sistemBulgulari: string;
  bilincDurumu: string;
  pupillaDegerlendirmesi: string;
  isikRefleksi: string;
  nabiz: string;
  tendonRefleksi: string;
  psikiyatrikMuayene: string;
  psikiyatrikSonuc: string;
  hizmetAciklama: string;
  sevkDurumu: string;
  sevkAciklama: string;
  teslimAlanAdiSoyadi: string;
  teslimAlanTcKimlikNumarasi: string;
  vucutDiyagrami: string;
  aciklama: string;
  adliMuayeneRizaDurumu: string;
  rizaVerenKisi: string;
  rizaVereninYakinlikDerecesi: string;
  sonCinselIliskiTarihi: Date;
  hamilelikDurumu: string;
  hamilelikOykusuAciklama: string;
  veneryalHastalikOykusu: string;
  emosyonelHastalikOykusu: string;
  solunum: string;
  adliMuayeneNotu: string;
  alinanMateryal: string;
  muayenedekiKisiBilgisi: string;
  muayenedekiKisiAciklama: string;
  alkolKullanimi: string;
  siddetTehditBilgisi: string;
  silahAletBilgisi: string;
  hayatiTehlikeDurumu: string;
  sistolikKanBasinciDegeri: string;
  diastolikKanBasinciDegeri: string;
  iptalZamani: Date;
  iptalEdenKullaniciKodu: string;
  adliRaporIptalGerekcesi: string;
  onaylayanKullaniciKodu: string;
  adliRaporOnaylanmaZamani: Date;
  ekleyenKullaniciKodu?: string;
  kayitZamani?: Date;
  guncelleyenKullaniciKodu?: string;
  guncellemeZamani?: Date;
}

export interface ListHastaAdliRaporDto {
  id: string;
  hastaAdliRaporKodu: string;
  referansTabloAdi: string;
  hastaBasvuruKodu: string;
  hastaKodu: string;
  adliRaporTuru: string;
  raporZamani?: Date;
  adliMuayeneyeGonderenKurum: string;
  resmiYaziNumarasi: string;
}

export interface CreateHastaAdliRaporDto {
  hastaAdliRaporKodu: string;
  referansTabloAdi: string;
  hastaBasvuruKodu: string;
  hastaKodu: string;
  adliRaporTuru: string;
  raporZamani?: Date;
  adliMuayeneyeGonderenKurum: string;
  resmiYaziNumarasi: string;
  resmiYaziTarihi: Date;
  adliMuayeneEdilmeNedeni: string;
  guvenlikSicilNumarasi: string;
  guvenlikAdiSoyadi: string;
  olayZamani: Date;
  adliOlayOykusu: string;
  sikayet: string;
  ozgecmisi: string;
  soygecmisi: string;
  muayeneZamani: Date;
  hekimKodu: string;
  tibbiMudahale: string;
  uygunSartSaglanmaDurumu: string;
  uygunSartAciklama: string;
  elbiseDurumu: string;
  konsultasyonBilgisi: string;
  lezyonBulgulari: string;
  sistemBulgulari: string;
  bilincDurumu: string;
  pupillaDegerlendirmesi: string;
  isikRefleksi: string;
  nabiz: string;
  tendonRefleksi: string;
  psikiyatrikMuayene: string;
  psikiyatrikSonuc: string;
  hizmetAciklama: string;
  sevkDurumu: string;
  sevkAciklama: string;
  teslimAlanAdiSoyadi: string;
  teslimAlanTcKimlikNumarasi: string;
  vucutDiyagrami: string;
  aciklama: string;
  adliMuayeneRizaDurumu: string;
  rizaVerenKisi: string;
  rizaVereninYakinlikDerecesi: string;
  sonCinselIliskiTarihi: Date;
  hamilelikDurumu: string;
  hamilelikOykusuAciklama: string;
  veneryalHastalikOykusu: string;
  emosyonelHastalikOykusu: string;
  solunum: string;
  adliMuayeneNotu: string;
  alinanMateryal: string;
  muayenedekiKisiBilgisi: string;
  muayenedekiKisiAciklama: string;
  alkolKullanimi: string;
  siddetTehditBilgisi: string;
  silahAletBilgisi: string;
  hayatiTehlikeDurumu: string;
  sistolikKanBasinciDegeri: string;
  diastolikKanBasinciDegeri: string;
  iptalZamani: Date;
  iptalEdenKullaniciKodu: string;
  adliRaporIptalGerekcesi: string;
  onaylayanKullaniciKodu: string;
  adliRaporOnaylanmaZamani: Date;
  ekleyenKullaniciKodu?: string;
  kayitZamani?: Date;
  guncelleyenKullaniciKodu?: string;
  guncellemeZamani?: Date;
}

export interface UpdateHastaAdliRaporDto extends CreateHastaAdliRaporDto {
  id: string;
}

export interface HastaAdliRaporListFilter extends BaseListFilter {
  hastaAdliRaporKodu?: string;
  referansTabloAdi?: string;
  hastaBasvuruKodu?: string;
  hastaKodu?: string;
  adliRaporTuru?: string;
}

export const newHastaAdliRapor: CreateHastaAdliRaporDto = {
  hastaAdliRaporKodu: '',
  referansTabloAdi: '',
  hastaBasvuruKodu: '',
  hastaKodu: '',
  adliRaporTuru: '',
  raporZamani: undefined,
  adliMuayeneyeGonderenKurum: '',
  resmiYaziNumarasi: '',
  resmiYaziTarihi: undefined,
  adliMuayeneEdilmeNedeni: '',
  guvenlikSicilNumarasi: '',
  guvenlikAdiSoyadi: '',
  olayZamani: undefined,
  adliOlayOykusu: '',
  sikayet: '',
  ozgecmisi: '',
  soygecmisi: '',
  muayeneZamani: undefined,
  hekimKodu: '',
  tibbiMudahale: '',
  uygunSartSaglanmaDurumu: '',
  uygunSartAciklama: '',
  elbiseDurumu: '',
  konsultasyonBilgisi: '',
  lezyonBulgulari: '',
  sistemBulgulari: '',
  bilincDurumu: '',
  pupillaDegerlendirmesi: '',
  isikRefleksi: '',
  nabiz: '',
  tendonRefleksi: '',
  psikiyatrikMuayene: '',
  psikiyatrikSonuc: '',
  hizmetAciklama: '',
  sevkDurumu: '',
  sevkAciklama: '',
  teslimAlanAdiSoyadi: '',
  teslimAlanTcKimlikNumarasi: '',
  vucutDiyagrami: '',
  aciklama: '',
  adliMuayeneRizaDurumu: '',
  rizaVerenKisi: '',
  rizaVereninYakinlikDerecesi: '',
  sonCinselIliskiTarihi: undefined,
  hamilelikDurumu: '',
  hamilelikOykusuAciklama: '',
  veneryalHastalikOykusu: '',
  emosyonelHastalikOykusu: '',
  solunum: '',
  adliMuayeneNotu: '',
  alinanMateryal: '',
  muayenedekiKisiBilgisi: '',
  muayenedekiKisiAciklama: '',
  alkolKullanimi: '',
  siddetTehditBilgisi: '',
  silahAletBilgisi: '',
  hayatiTehlikeDurumu: '',
  sistolikKanBasinciDegeri: '',
  diastolikKanBasinciDegeri: '',
  iptalZamani: undefined,
  iptalEdenKullaniciKodu: '',
  adliRaporIptalGerekcesi: '',
  onaylayanKullaniciKodu: '',
  adliRaporOnaylanmaZamani: undefined,
  ekleyenKullaniciKodu: '',
  kayitZamani: undefined,
  guncelleyenKullaniciKodu: '',
  guncellemeZamani: undefined,
};
