// PersonelBordro Model Definitions
import { VemBaseDto, BaseListFilter } from './base.model';

export interface PersonelBordroDto extends VemBaseDto {
  personelBordroKodu: string;
  referansTabloAdi: string;
  yil: string;
  ay: string;
  personelKodu: string;
  bordroTuru: string;
  bordroNumarasi: string;
  maasDerecesi: string;
  maasKademesi: string;
  maasGostergesi: string;
  maasEkGostergesi: string;
  emekliDerecesi: string;
  emekliKademesi: string;
  emekliGostergesi: string;
  emekliEkGostergesi: string;
  tabanAylikTutari: string;
  aylikTutari: string;
  kidemTutari: string;
  ekGostergeTutari: string;
  yanOdemeTutari: string;
  ozelHizmetTutari: string;
  aileYardimiTutari: string;
  cocukYardimiTutari: string;
  cocukSayisi6YasAlti: string;
  cocukSayisi6YasUstu: string;
  agiEsasCocukSayisi: string;
  esCalismaDurumu: string;
  besFirmaKodu: string;
  besOrani: string;
  besKesintiTutari: string;
  yabanciDilTazminatiTutari: string;
  yabanciDilBilgisi: string;
  yabanciDilPuani: string;
  sendikaOdenegiTutari: string;
  sendikaBilgisi: string;
  sendikaSiraNumarasi: string;
  sendikaKesintiOrani: string;
  sendikaAidatiTutari: string;
  devletEmekliKesenegi: string;
  sahisEmekliKesenegi: string;
  emekliKesenegiMatrahiTutari: string;
  ozelSigortaTutari: string;
  vergiIndirimiTutari: string;
  damgaVergisiTutari: string;
  gelirVergisiTutari: string;
  gelirVergisiMatrahiTutari: string;
  kumulatifGelirVergisiTutari: string;
  icraTutari: string;
  nafakaTutari: string;
  yuzdeYuzTutari: string;
  doguTazminatiTutari: string;
  sgkSahisTutari: string;
  sgkIsverenTutari: string;
  sgkMatrahiTutari: string;
  kefaletTutari: string;
  sozlesmeUcretiTutari: string;
  lojmanKesintisiTutari: string;
  asgariGecimIndirimiTutari: string;
  issizlikSahisTutari: string;
  issizlikIsverenTutari: string;
  issizlikPrimiMatrahiTutari: string;
  malullukDevletTutari: string;
  malullukSahisTutari: string;
  giyecekYardimiTutari: string;
  farkTazminatiTutari: string;
  hizmetZammiTutari: string;
  vasitaYardimiTutari: string;
  kiraYardimiTutari: string;
  yemekYardimiTutari: string;
  fazlaMesaiTutari: string;
  nobetBirimUcretTutari: string;
  nobetBirimUcret20Tutari: string;
  nobetBirimUcret50Tutari: string;
  nobetSaati: string;
  nobet20Saati: string;
  nobet50Saati: string;
  yevmiyeTutari: string;
  calismaSaati: string;
  tahakkukToplami: string;
  netTutar: string;
  kesintiToplami: string;
  ekleyenKullaniciKodu?: string;
  kayitZamani?: Date;
  guncelleyenKullaniciKodu?: string;
  guncellemeZamani?: Date;
}

export interface ListPersonelBordroDto {
  id: string;
  personelBordroKodu: string;
  referansTabloAdi: string;
  yil: string;
  ay: string;
  personelKodu: string;
  bordroTuru: string;
  bordroNumarasi: string;
  maasDerecesi: string;
}

export interface CreatePersonelBordroDto {
  personelBordroKodu: string;
  referansTabloAdi: string;
  yil: string;
  ay: string;
  personelKodu: string;
  bordroTuru: string;
  bordroNumarasi: string;
  maasDerecesi: string;
  maasKademesi: string;
  maasGostergesi: string;
  maasEkGostergesi: string;
  emekliDerecesi: string;
  emekliKademesi: string;
  emekliGostergesi: string;
  emekliEkGostergesi: string;
  tabanAylikTutari: string;
  aylikTutari: string;
  kidemTutari: string;
  ekGostergeTutari: string;
  yanOdemeTutari: string;
  ozelHizmetTutari: string;
  aileYardimiTutari: string;
  cocukYardimiTutari: string;
  cocukSayisi6YasAlti: string;
  cocukSayisi6YasUstu: string;
  agiEsasCocukSayisi: string;
  esCalismaDurumu: string;
  besFirmaKodu: string;
  besOrani: string;
  besKesintiTutari: string;
  yabanciDilTazminatiTutari: string;
  yabanciDilBilgisi: string;
  yabanciDilPuani: string;
  sendikaOdenegiTutari: string;
  sendikaBilgisi: string;
  sendikaSiraNumarasi: string;
  sendikaKesintiOrani: string;
  sendikaAidatiTutari: string;
  devletEmekliKesenegi: string;
  sahisEmekliKesenegi: string;
  emekliKesenegiMatrahiTutari: string;
  ozelSigortaTutari: string;
  vergiIndirimiTutari: string;
  damgaVergisiTutari: string;
  gelirVergisiTutari: string;
  gelirVergisiMatrahiTutari: string;
  kumulatifGelirVergisiTutari: string;
  icraTutari: string;
  nafakaTutari: string;
  yuzdeYuzTutari: string;
  doguTazminatiTutari: string;
  sgkSahisTutari: string;
  sgkIsverenTutari: string;
  sgkMatrahiTutari: string;
  kefaletTutari: string;
  sozlesmeUcretiTutari: string;
  lojmanKesintisiTutari: string;
  asgariGecimIndirimiTutari: string;
  issizlikSahisTutari: string;
  issizlikIsverenTutari: string;
  issizlikPrimiMatrahiTutari: string;
  malullukDevletTutari: string;
  malullukSahisTutari: string;
  giyecekYardimiTutari: string;
  farkTazminatiTutari: string;
  hizmetZammiTutari: string;
  vasitaYardimiTutari: string;
  kiraYardimiTutari: string;
  yemekYardimiTutari: string;
  fazlaMesaiTutari: string;
  nobetBirimUcretTutari: string;
  nobetBirimUcret20Tutari: string;
  nobetBirimUcret50Tutari: string;
  nobetSaati: string;
  nobet20Saati: string;
  nobet50Saati: string;
  yevmiyeTutari: string;
  calismaSaati: string;
  tahakkukToplami: string;
  netTutar: string;
  kesintiToplami: string;
  ekleyenKullaniciKodu?: string;
  kayitZamani?: Date;
  guncelleyenKullaniciKodu?: string;
  guncellemeZamani?: Date;
}

export interface UpdatePersonelBordroDto extends CreatePersonelBordroDto {
  id: string;
}

export interface PersonelBordroListFilter extends BaseListFilter {
  personelBordroKodu?: string;
  referansTabloAdi?: string;
  yil?: string;
  ay?: string;
  personelKodu?: string;
}

export const newPersonelBordro: CreatePersonelBordroDto = {
  personelBordroKodu: '',
  referansTabloAdi: '',
  yil: '',
  ay: '',
  personelKodu: '',
  bordroTuru: '',
  bordroNumarasi: '',
  maasDerecesi: '',
  maasKademesi: '',
  maasGostergesi: '',
  maasEkGostergesi: '',
  emekliDerecesi: '',
  emekliKademesi: '',
  emekliGostergesi: '',
  emekliEkGostergesi: '',
  tabanAylikTutari: '',
  aylikTutari: '',
  kidemTutari: '',
  ekGostergeTutari: '',
  yanOdemeTutari: '',
  ozelHizmetTutari: '',
  aileYardimiTutari: '',
  cocukYardimiTutari: '',
  cocukSayisi6YasAlti: '',
  cocukSayisi6YasUstu: '',
  agiEsasCocukSayisi: '',
  esCalismaDurumu: '',
  besFirmaKodu: '',
  besOrani: '',
  besKesintiTutari: '',
  yabanciDilTazminatiTutari: '',
  yabanciDilBilgisi: '',
  yabanciDilPuani: '',
  sendikaOdenegiTutari: '',
  sendikaBilgisi: '',
  sendikaSiraNumarasi: '',
  sendikaKesintiOrani: '',
  sendikaAidatiTutari: '',
  devletEmekliKesenegi: '',
  sahisEmekliKesenegi: '',
  emekliKesenegiMatrahiTutari: '',
  ozelSigortaTutari: '',
  vergiIndirimiTutari: '',
  damgaVergisiTutari: '',
  gelirVergisiTutari: '',
  gelirVergisiMatrahiTutari: '',
  kumulatifGelirVergisiTutari: '',
  icraTutari: '',
  nafakaTutari: '',
  yuzdeYuzTutari: '',
  doguTazminatiTutari: '',
  sgkSahisTutari: '',
  sgkIsverenTutari: '',
  sgkMatrahiTutari: '',
  kefaletTutari: '',
  sozlesmeUcretiTutari: '',
  lojmanKesintisiTutari: '',
  asgariGecimIndirimiTutari: '',
  issizlikSahisTutari: '',
  issizlikIsverenTutari: '',
  issizlikPrimiMatrahiTutari: '',
  malullukDevletTutari: '',
  malullukSahisTutari: '',
  giyecekYardimiTutari: '',
  farkTazminatiTutari: '',
  hizmetZammiTutari: '',
  vasitaYardimiTutari: '',
  kiraYardimiTutari: '',
  yemekYardimiTutari: '',
  fazlaMesaiTutari: '',
  nobetBirimUcretTutari: '',
  nobetBirimUcret20Tutari: '',
  nobetBirimUcret50Tutari: '',
  nobetSaati: '',
  nobet20Saati: '',
  nobet50Saati: '',
  yevmiyeTutari: '',
  calismaSaati: '',
  tahakkukToplami: '',
  netTutar: '',
  kesintiToplami: '',
  ekleyenKullaniciKodu: '',
  kayitZamani: undefined,
  guncelleyenKullaniciKodu: '',
  guncellemeZamani: undefined,
};
