-- =============================================
-- SEED SCRIPT PART 6: Kalan Tablolar (Son Kisim)
-- Tablolar: SILINEN_KAYITLAR, ILAC_UYUM, TIBBI_ORDER, TIBBI_ORDER_DETAY,
--           ASI_BILGISI, BAKTERI_SONUC, ANTIBIYOTIK_SONUC, RISK_SKORLAMA,
--           RISK_SKORLAMA_DETAY, SYS_PAKET, MEDULA_TAKIP
-- =============================================

USE TESTDATA;
GO

SET NOCOUNT ON;
GO

DECLARE @Now DATETIME = GETDATE();
DECLARE @User NVARCHAR(50) = 'SYSTEM';
DECLARE @i INT;

-- =============================================
-- SILINEN_KAYITLAR - Silinen kayitlarin izlenmesi (30 kayit)
-- =============================================
PRINT 'SILINEN_KAYITLAR ekleniyor...';

DECLARE @SilinenKayitNo INT = 1;
WHILE @SilinenKayitNo <= 30
BEGIN
    DECLARE @RefGoruntuAdi NVARCHAR(100);
    SET @RefGoruntuAdi = CASE (@SilinenKayitNo % 10)
        WHEN 1 THEN 'HASTA'
        WHEN 2 THEN 'HASTA_BASVURU'
        WHEN 3 THEN 'RECETE'
        WHEN 4 THEN 'TETKIK_ISTEK'
        WHEN 5 THEN 'AMELIYAT'
        WHEN 6 THEN 'RADYOLOJI'
        WHEN 7 THEN 'STOK_HAREKET'
        WHEN 8 THEN 'PERSONEL'
        WHEN 9 THEN 'VEZNE'
        ELSE 'RANDEVU'
    END;

    INSERT INTO SILINEN_KAYITLAR (
        SILINEN_KAYITLAR_KODU, REFERANS_GORUNTU_ADI, SILINME_ZAMANI, SILINEN_KAYDIN_KODU,
        EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'SLN-' + RIGHT('000000' + CAST(@SilinenKayitNo AS VARCHAR), 6),
        @RefGoruntuAdi,
        DATEADD(DAY, -(@SilinenKayitNo * 3), @Now),
        @RefGoruntuAdi + '-SILINEN-' + CAST(@SilinenKayitNo AS VARCHAR),
        @User, @Now
    WHERE NOT EXISTS (SELECT 1 FROM SILINEN_KAYITLAR WHERE SILINEN_KAYITLAR_KODU = 'SLN-' + RIGHT('000000' + CAST(@SilinenKayitNo AS VARCHAR), 6));

    SET @SilinenKayitNo = @SilinenKayitNo + 1;
END;
GO

-- =============================================
-- REFERANS_KODLAR - Ilac Uyum ve ASI icin gerekli referans kodlar
-- =============================================
PRINT 'Ilac Uyum ve ASI referans kodlari ekleniyor...';

-- Ilac Uyumsuzluk Turleri
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ILAC_UYUMSUZLUK_TURU')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ILACUYUM-001', 'Ilac-Ilac Etkilesimi', 'ILAC_UYUMSUZLUK_TURU', 'Iki ilac arasindaki etkilesim', 'SYSTEM', GETDATE()),
    ('ILACUYUM-002', 'Ilac-Besin Etkilesimi', 'ILAC_UYUMSUZLUK_TURU', 'Ilac ve besin arasindaki etkilesim', 'SYSTEM', GETDATE()),
    ('ILACUYUM-003', 'Doz Uyumsuzlugu', 'ILAC_UYUMSUZLUK_TURU', 'Dozaj uyumsuzlugu', 'SYSTEM', GETDATE()),
    ('ILACUYUM-004', 'Yas Uyumsuzlugu', 'ILAC_UYUMSUZLUK_TURU', 'Yas grubuna uyumsuz ilac', 'SYSTEM', GETDATE()),
    ('ILACUYUM-005', 'Cinsiyet Uyumsuzlugu', 'ILAC_UYUMSUZLUK_TURU', 'Cinsiyete uyumsuz ilac', 'SYSTEM', GETDATE());
END;

-- Ilac Barkodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ILAC_BARKOD')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ILAC-BRK-001', 'Aspirin 100mg', 'ILAC_BARKOD', 'Asetilsalisilik asit 100mg tablet', 'SYSTEM', GETDATE()),
    ('ILAC-BRK-002', 'Parol 500mg', 'ILAC_BARKOD', 'Parasetamol 500mg tablet', 'SYSTEM', GETDATE()),
    ('ILAC-BRK-003', 'Cefazolin 1g', 'ILAC_BARKOD', 'Cefazolin sodyum 1g flakon', 'SYSTEM', GETDATE()),
    ('ILAC-BRK-004', 'Metformin 850mg', 'ILAC_BARKOD', 'Metformin HCL 850mg tablet', 'SYSTEM', GETDATE()),
    ('ILAC-BRK-005', 'Atorvastatin 20mg', 'ILAC_BARKOD', 'Atorvastatin 20mg tablet', 'SYSTEM', GETDATE()),
    ('ILAC-BRK-006', 'Omeprazol 20mg', 'ILAC_BARKOD', 'Omeprazol 20mg kapsul', 'SYSTEM', GETDATE()),
    ('ILAC-BRK-007', 'Ramipril 5mg', 'ILAC_BARKOD', 'Ramipril 5mg tablet', 'SYSTEM', GETDATE()),
    ('ILAC-BRK-008', 'Warfarin 5mg', 'ILAC_BARKOD', 'Warfarin sodyum 5mg tablet', 'SYSTEM', GETDATE());
END;

-- Etken Maddeler
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ETKEN_MADDE')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ETK-001', 'Asetilsalisilik Asit', 'ETKEN_MADDE', 'NSAIi etken maddesi', 'SYSTEM', GETDATE()),
    ('ETK-002', 'Parasetamol', 'ETKEN_MADDE', 'Analjezik antipretik', 'SYSTEM', GETDATE()),
    ('ETK-003', 'Cefazolin', 'ETKEN_MADDE', 'Sefalosporin grubu antibiyotik', 'SYSTEM', GETDATE()),
    ('ETK-004', 'Metformin', 'ETKEN_MADDE', 'Oral antidiyabetik', 'SYSTEM', GETDATE()),
    ('ETK-005', 'Atorvastatin', 'ETKEN_MADDE', 'Kolesterol dusuricu', 'SYSTEM', GETDATE()),
    ('ETK-006', 'Omeprazol', 'ETKEN_MADDE', 'Proton pompa inhibitoru', 'SYSTEM', GETDATE()),
    ('ETK-007', 'Ramipril', 'ETKEN_MADDE', 'ACE inhibitoru', 'SYSTEM', GETDATE()),
    ('ETK-008', 'Warfarin', 'ETKEN_MADDE', 'Antikoagulan', 'SYSTEM', GETDATE());
END;

-- Besinler
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'BESIN')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('BES-001', 'Greyfurt', 'BESIN', 'Citrus meyve', 'SYSTEM', GETDATE()),
    ('BES-002', 'Sut', 'BESIN', 'Suturun', 'SYSTEM', GETDATE()),
    ('BES-003', 'Yesillik', 'BESIN', 'K vitamini iceren besin', 'SYSTEM', GETDATE()),
    ('BES-004', 'Alkol', 'BESIN', 'Alkollü icecek', 'SYSTEM', GETDATE()),
    ('BES-005', 'Kahve', 'BESIN', 'Kafeinli icecek', 'SYSTEM', GETDATE());
END;

-- Renk Seviyeleri
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'RENK_SEVIYE')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('RENK-001', 'Kirmizi', 'RENK_SEVIYE', 'Ciddi uyari - Kullanilmamali', 'SYSTEM', GETDATE()),
    ('RENK-002', 'Turuncu', 'RENK_SEVIYE', 'Dikkat - Risk mevcut', 'SYSTEM', GETDATE()),
    ('RENK-003', 'Sari', 'RENK_SEVIYE', 'Hafif uyari - Izleme gerekli', 'SYSTEM', GETDATE()),
    ('RENK-004', 'Yesil', 'RENK_SEVIYE', 'Guvenli - Etkilesim yok', 'SYSTEM', GETDATE());
END;

-- ASI Kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASI-001', 'Hepatit B', 'ASI', 'Hepatit B asisi', 'SYSTEM', GETDATE()),
    ('ASI-002', 'BCG', 'ASI', 'Tuberkuloz asisi', 'SYSTEM', GETDATE()),
    ('ASI-003', 'DBT-IPA-Hib', 'ASI', 'Besli karma asi', 'SYSTEM', GETDATE()),
    ('ASI-004', 'KPA', 'ASI', 'Konjuge pnomokok asisi', 'SYSTEM', GETDATE()),
    ('ASI-005', 'OPA', 'ASI', 'Oral polio asisi', 'SYSTEM', GETDATE()),
    ('ASI-006', 'KKK', 'ASI', 'Kizamik-Kizamikcik-Kabakulak', 'SYSTEM', GETDATE()),
    ('ASI-007', 'Su Cicegi', 'ASI', 'Varisella asisi', 'SYSTEM', GETDATE()),
    ('ASI-008', 'Td', 'ASI', 'Tetanoz-Difteri asisi', 'SYSTEM', GETDATE()),
    ('ASI-009', 'Grip', 'ASI', 'Mevsimsel grip asisi', 'SYSTEM', GETDATE()),
    ('ASI-010', 'COVID-19', 'ASI', 'Koronavirus asisi', 'SYSTEM', GETDATE());
END;

-- ASI Dozlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_DOZ')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASIDOZ-001', '1. Doz', 'ASI_DOZ', 'Birinci doz', 'SYSTEM', GETDATE()),
    ('ASIDOZ-002', '2. Doz', 'ASI_DOZ', 'Ikinci doz', 'SYSTEM', GETDATE()),
    ('ASIDOZ-003', '3. Doz', 'ASI_DOZ', 'Ucuncu doz', 'SYSTEM', GETDATE()),
    ('ASIDOZ-004', 'Rapel', 'ASI_DOZ', 'Hatirlatma dozu', 'SYSTEM', GETDATE());
END;

-- ASI Uygulama Sekli
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_UYGULAMA_SEKLI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASIUYG-001', 'IM', 'ASI_UYGULAMA_SEKLI', 'Kas ici', 'SYSTEM', GETDATE()),
    ('ASIUYG-002', 'SC', 'ASI_UYGULAMA_SEKLI', 'Cilt alti', 'SYSTEM', GETDATE()),
    ('ASIUYG-003', 'ID', 'ASI_UYGULAMA_SEKLI', 'Cilt ici', 'SYSTEM', GETDATE()),
    ('ASIUYG-004', 'Oral', 'ASI_UYGULAMA_SEKLI', 'Agizdan', 'SYSTEM', GETDATE());
END;

-- ASI Uygulama Yeri
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_UYGULAMA_YERI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASIYER-001', 'Sol Kol', 'ASI_UYGULAMA_YERI', 'Sol kol deltoid', 'SYSTEM', GETDATE()),
    ('ASIYER-002', 'Sag Kol', 'ASI_UYGULAMA_YERI', 'Sag kol deltoid', 'SYSTEM', GETDATE()),
    ('ASIYER-003', 'Sol Bacak', 'ASI_UYGULAMA_YERI', 'Sol uyluk on yuz', 'SYSTEM', GETDATE()),
    ('ASIYER-004', 'Sag Bacak', 'ASI_UYGULAMA_YERI', 'Sag uyluk on yuz', 'SYSTEM', GETDATE());
END;

-- ASI Islem Turu
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_ISLEM_TURU')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASIISLM-001', 'Yapildi', 'ASI_ISLEM_TURU', 'Asi uygulandi', 'SYSTEM', GETDATE()),
    ('ASIISLM-002', 'Ertelendi', 'ASI_ISLEM_TURU', 'Asi ertelendi', 'SYSTEM', GETDATE()),
    ('ASIISLM-003', 'Iptal', 'ASI_ISLEM_TURU', 'Asi iptal edildi', 'SYSTEM', GETDATE()),
    ('ASIISLM-004', 'Dis Kayit', 'ASI_ISLEM_TURU', 'Baska kurumda yapildi', 'SYSTEM', GETDATE());
END;

-- ASI Ozel Durum Nedeni
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_OZEL_DURUM_NEDENI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASIOZEL-001', 'Yok', 'ASI_OZEL_DURUM_NEDENI', 'Ozel durum yok', 'SYSTEM', GETDATE()),
    ('ASIOZEL-002', 'Alerji', 'ASI_OZEL_DURUM_NEDENI', 'Alerjik reaksiyon', 'SYSTEM', GETDATE()),
    ('ASIOZEL-003', 'Ates', 'ASI_OZEL_DURUM_NEDENI', 'Yuksek ates', 'SYSTEM', GETDATE()),
    ('ASIOZEL-004', 'Enfeksiyon', 'ASI_OZEL_DURUM_NEDENI', 'Aktif enfeksiyon', 'SYSTEM', GETDATE());
END;

-- ASIE Nedenleri
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASIE_NEDENLERI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASIE-001', 'Yok', 'ASIE_NEDENLERI', 'Istenmeyen etki yok', 'SYSTEM', GETDATE()),
    ('ASIE-002', 'Lokal Reaksiyon', 'ASIE_NEDENLERI', 'Enjeksiyon yerinde reaksiyon', 'SYSTEM', GETDATE()),
    ('ASIE-003', 'Ates', 'ASIE_NEDENLERI', 'Ates yukselmesi', 'SYSTEM', GETDATE()),
    ('ASIE-004', 'Anafilaksi', 'ASIE_NEDENLERI', 'Anafilaktik sok', 'SYSTEM', GETDATE());
END;

-- ASI Yapilmama Durumu
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_YAPILMAMA_DURUMU')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASIYOK-001', 'Yapildi', 'ASI_YAPILMAMA_DURUMU', 'Asi yapildi', 'SYSTEM', GETDATE()),
    ('ASIYOK-002', 'Ertelendi', 'ASI_YAPILMAMA_DURUMU', 'Asi ertelendi', 'SYSTEM', GETDATE()),
    ('ASIYOK-003', 'Iptal', 'ASI_YAPILMAMA_DURUMU', 'Asi iptal edildi', 'SYSTEM', GETDATE());
END;

-- ASI Yapilmama Nedeni
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_YAPILMAMA_NEDENI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ASINEDEN-001', 'Yok', 'ASI_YAPILMAMA_NEDENI', 'Neden yok, asi yapildi', 'SYSTEM', GETDATE()),
    ('ASINEDEN-002', 'Hasta Reddi', 'ASI_YAPILMAMA_NEDENI', 'Hasta veya veli reddetti', 'SYSTEM', GETDATE()),
    ('ASINEDEN-003', 'Tibbi Kontrendikasyon', 'ASI_YAPILMAMA_NEDENI', 'Tibbi nedenlerle yapilmadi', 'SYSTEM', GETDATE()),
    ('ASINEDEN-004', 'Stok Yok', 'ASI_YAPILMAMA_NEDENI', 'Asi stokta mevcut degil', 'SYSTEM', GETDATE());
END;

-- Altta Yatan Hastalik
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ALTTA_YATAN_HASTALIK')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ALTHA-001', 'Yok', 'ALTTA_YATAN_HASTALIK', 'Altta yatan hastalik yok', 'SYSTEM', GETDATE()),
    ('ALTHA-002', 'Immun Yetmezlik', 'ALTTA_YATAN_HASTALIK', 'Bagisiklik sistemi bozuklugu', 'SYSTEM', GETDATE()),
    ('ALTHA-003', 'Kanser', 'ALTTA_YATAN_HASTALIK', 'Malign hastalik', 'SYSTEM', GETDATE()),
    ('ALTHA-004', 'Kronik Hastalik', 'ALTTA_YATAN_HASTALIK', 'Kronik sistemik hastalik', 'SYSTEM', GETDATE());
END;

-- Bakteri Kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'BAKTERI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('BAK-001', 'Escherichia coli', 'BAKTERI', 'E. coli', 'SYSTEM', GETDATE()),
    ('BAK-002', 'Staphylococcus aureus', 'BAKTERI', 'S. aureus', 'SYSTEM', GETDATE()),
    ('BAK-003', 'Streptococcus pneumoniae', 'BAKTERI', 'S. pneumoniae', 'SYSTEM', GETDATE()),
    ('BAK-004', 'Pseudomonas aeruginosa', 'BAKTERI', 'P. aeruginosa', 'SYSTEM', GETDATE()),
    ('BAK-005', 'Klebsiella pneumoniae', 'BAKTERI', 'K. pneumoniae', 'SYSTEM', GETDATE()),
    ('BAK-006', 'Enterococcus faecalis', 'BAKTERI', 'E. faecalis', 'SYSTEM', GETDATE()),
    ('BAK-007', 'Acinetobacter baumannii', 'BAKTERI', 'A. baumannii', 'SYSTEM', GETDATE()),
    ('BAK-008', 'Haemophilus influenzae', 'BAKTERI', 'H. influenzae', 'SYSTEM', GETDATE());
END;

-- Antibiyotik Kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ANTIBIYOTIK')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ANT-001', 'Penisilin', 'ANTIBIYOTIK', 'Penisilin grubu', 'SYSTEM', GETDATE()),
    ('ANT-002', 'Amikasin', 'ANTIBIYOTIK', 'Aminoglikozid', 'SYSTEM', GETDATE()),
    ('ANT-003', 'Gentamisin', 'ANTIBIYOTIK', 'Aminoglikozid', 'SYSTEM', GETDATE()),
    ('ANT-004', 'Siprofloksasin', 'ANTIBIYOTIK', 'Florokinolon', 'SYSTEM', GETDATE()),
    ('ANT-005', 'Vankomisin', 'ANTIBIYOTIK', 'Glikopeptid', 'SYSTEM', GETDATE()),
    ('ANT-006', 'Meropenem', 'ANTIBIYOTIK', 'Karbapenem', 'SYSTEM', GETDATE()),
    ('ANT-007', 'Seftriakson', 'ANTIBIYOTIK', 'Sefalosporin', 'SYSTEM', GETDATE()),
    ('ANT-008', 'Kolistin', 'ANTIBIYOTIK', 'Polimiksin', 'SYSTEM', GETDATE());
END;

-- Antibiyotik Sonuc
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ANTIBIYOTIK_SONUC')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('ANTSONUC-001', 'S (Duyarli)', 'ANTIBIYOTIK_SONUC', 'Bakteri antibiyotik duyarli', 'SYSTEM', GETDATE()),
    ('ANTSONUC-002', 'I (Orta)', 'ANTIBIYOTIK_SONUC', 'Orta derecede duyarli', 'SYSTEM', GETDATE()),
    ('ANTSONUC-003', 'R (Direncli)', 'ANTIBIYOTIK_SONUC', 'Bakteri direncli', 'SYSTEM', GETDATE());
END;

-- Tibbi Order Turu
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TIBBI_ORDER_TURU')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('TORDER-001', 'Ilac', 'TIBBI_ORDER_TURU', 'Ilac orderi', 'SYSTEM', GETDATE()),
    ('TORDER-002', 'Serum', 'TIBBI_ORDER_TURU', 'Serum orderi', 'SYSTEM', GETDATE()),
    ('TORDER-003', 'Tetkik', 'TIBBI_ORDER_TURU', 'Tetkik istemi', 'SYSTEM', GETDATE()),
    ('TORDER-004', 'Konsultasyon', 'TIBBI_ORDER_TURU', 'Konsultasyon istemi', 'SYSTEM', GETDATE()),
    ('TORDER-005', 'Diyet', 'TIBBI_ORDER_TURU', 'Diyet orderi', 'SYSTEM', GETDATE()),
    ('TORDER-006', 'Bakim', 'TIBBI_ORDER_TURU', 'Bakim orderi', 'SYSTEM', GETDATE());
END;

-- Tibbi Order Iptal Nedeni
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TIBBI_ORDER_IPTAL_NEDENI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('TIPTAL-001', 'Iptal Yok', 'TIBBI_ORDER_IPTAL_NEDENI', 'Order iptal edilmedi', 'SYSTEM', GETDATE()),
    ('TIPTAL-002', 'Hekim Karari', 'TIBBI_ORDER_IPTAL_NEDENI', 'Hekim tarafindan iptal', 'SYSTEM', GETDATE()),
    ('TIPTAL-003', 'Hasta Reddi', 'TIBBI_ORDER_IPTAL_NEDENI', 'Hasta reddetti', 'SYSTEM', GETDATE()),
    ('TIPTAL-004', 'Stok Yok', 'TIBBI_ORDER_IPTAL_NEDENI', 'Malzeme/ilac stokta yok', 'SYSTEM', GETDATE()),
    ('TIPTAL-005', 'Taburcu', 'TIBBI_ORDER_IPTAL_NEDENI', 'Hasta taburcu oldu', 'SYSTEM', GETDATE());
END;

-- Risk Skorlama Turu
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'RISK_SKORLAMA_TURU')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('RISK-001', 'APACHE II', 'RISK_SKORLAMA_TURU', 'Akut fizyoloji ve kronik saglik degerlendirmesi', 'SYSTEM', GETDATE()),
    ('RISK-002', 'SAPS II', 'RISK_SKORLAMA_TURU', 'Basitlestirilmis akut fizyoloji skoru', 'SYSTEM', GETDATE()),
    ('RISK-003', 'SOFA', 'RISK_SKORLAMA_TURU', 'Sirasal organ yetmezligi degerlendirmesi', 'SYSTEM', GETDATE()),
    ('RISK-004', 'ITAKI', 'RISK_SKORLAMA_TURU', 'Dusme riski degerlendirmesi', 'SYSTEM', GETDATE()),
    ('RISK-005', 'HARIZMI', 'RISK_SKORLAMA_TURU', 'Basi yarasi riski degerlendirmesi', 'SYSTEM', GETDATE()),
    ('RISK-006', 'BRADEN', 'RISK_SKORLAMA_TURU', 'Basinc yarasi riski', 'SYSTEM', GETDATE()),
    ('RISK-007', 'MORSE', 'RISK_SKORLAMA_TURU', 'Dusme riski degerlendirmesi', 'SYSTEM', GETDATE()),
    ('RISK-008', 'NEWS', 'RISK_SKORLAMA_TURU', 'Ulusal erken uyari skoru', 'SYSTEM', GETDATE());
END;

-- Risk Skorlama Alt Turu
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'RISK_SKORLAMA_ALT_TURU')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('RISKALT-001', 'Yas', 'RISK_SKORLAMA_ALT_TURU', 'Yas puani', 'SYSTEM', GETDATE()),
    ('RISKALT-002', 'Kalp Hizi', 'RISK_SKORLAMA_ALT_TURU', 'Kalp hizi puani', 'SYSTEM', GETDATE()),
    ('RISKALT-003', 'Tansiyon', 'RISK_SKORLAMA_ALT_TURU', 'Kan basinci puani', 'SYSTEM', GETDATE()),
    ('RISKALT-004', 'Solunum', 'RISK_SKORLAMA_ALT_TURU', 'Solunum hizi puani', 'SYSTEM', GETDATE()),
    ('RISKALT-005', 'Ates', 'RISK_SKORLAMA_ALT_TURU', 'Vucut isisi puani', 'SYSTEM', GETDATE()),
    ('RISKALT-006', 'Bilinc', 'RISK_SKORLAMA_ALT_TURU', 'Bilinc durumu puani', 'SYSTEM', GETDATE()),
    ('RISKALT-007', 'Oksijen', 'RISK_SKORLAMA_ALT_TURU', 'Oksijen saturasyonu puani', 'SYSTEM', GETDATE()),
    ('RISKALT-008', 'Kreatinin', 'RISK_SKORLAMA_ALT_TURU', 'Kreatinin puani', 'SYSTEM', GETDATE());
END;

-- Provizyon Turu
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'PROVIZYON_TURU')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('PROV-001', 'Normal', 'PROVIZYON_TURU', 'Normal provizyon', 'SYSTEM', GETDATE()),
    ('PROV-002', 'Acil', 'PROVIZYON_TURU', 'Acil provizyon', 'SYSTEM', GETDATE()),
    ('PROV-003', 'Sevk', 'PROVIZYON_TURU', 'Sevk provizyonu', 'SYSTEM', GETDATE()),
    ('PROV-004', 'Yatan', 'PROVIZYON_TURU', 'Yatan hasta provizyonu', 'SYSTEM', GETDATE());
END;

-- Takip Tipi
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TAKIP_TIPI')
BEGIN
    INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_ADI, REFERANS_TIPI, REFERANS_ACIKLAMASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
    VALUES
    ('TAKIP-001', 'Normal', 'TAKIP_TIPI', 'Normal takip', 'SYSTEM', GETDATE()),
    ('TAKIP-002', 'Eslik Eden Hastalik', 'TAKIP_TIPI', 'Komorbidite takibi', 'SYSTEM', GETDATE()),
    ('TAKIP-003', 'Uzayan Yatis', 'TAKIP_TIPI', 'Uzun sureli yatis', 'SYSTEM', GETDATE()),
    ('TAKIP-004', 'Yogun Bakim', 'TAKIP_TIPI', 'Yogun bakim takibi', 'SYSTEM', GETDATE());
END;
GO

-- =============================================
-- ILAC_UYUM (30 kayit)
-- =============================================
PRINT 'ILAC_UYUM ekleniyor...';

-- Degiskenleri bir kere tanimla
DECLARE @IlacBarkodlar TABLE (BarkodKodu NVARCHAR(50));
INSERT INTO @IlacBarkodlar SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ILAC_BARKOD';

DECLARE @EtkenMaddeler TABLE (EtkenKodu NVARCHAR(50));
INSERT INTO @EtkenMaddeler SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ETKEN_MADDE';

DECLARE @Besinler TABLE (BesinKodu NVARCHAR(50));
INSERT INTO @Besinler SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'BESIN';

DECLARE @UyumsuzlukTurleri TABLE (TurKodu NVARCHAR(50));
INSERT INTO @UyumsuzlukTurleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ILAC_UYUMSUZLUK_TURU';

DECLARE @RenkSeviyeler TABLE (RenkKodu NVARCHAR(50));
INSERT INTO @RenkSeviyeler SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'RENK_SEVIYE';

DECLARE @Cinsiyetler TABLE (CinsKodu NVARCHAR(50));
INSERT INTO @Cinsiyetler SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'CINSIYET';

DECLARE @IlacUyumNo INT = 1;
WHILE @IlacUyumNo <= 30
BEGIN
    DECLARE @UyumsuzTur NVARCHAR(50) = (SELECT TOP 1 TurKodu FROM @UyumsuzlukTurleri ORDER BY NEWID());
    DECLARE @Ilac1 NVARCHAR(50) = (SELECT TOP 1 BarkodKodu FROM @IlacBarkodlar ORDER BY NEWID());
    DECLARE @Ilac2 NVARCHAR(50) = (SELECT TOP 1 BarkodKodu FROM @IlacBarkodlar WHERE BarkodKodu <> @Ilac1 ORDER BY NEWID());
    DECLARE @Etken1 NVARCHAR(50) = (SELECT TOP 1 EtkenKodu FROM @EtkenMaddeler ORDER BY NEWID());
    DECLARE @Etken2 NVARCHAR(50) = (SELECT TOP 1 EtkenKodu FROM @EtkenMaddeler WHERE EtkenKodu <> @Etken1 ORDER BY NEWID());
    DECLARE @Besin NVARCHAR(50) = (SELECT TOP 1 BesinKodu FROM @Besinler ORDER BY NEWID());
    DECLARE @RenkSev NVARCHAR(50) = (SELECT TOP 1 RenkKodu FROM @RenkSeviyeler ORDER BY NEWID());
    DECLARE @Cins NVARCHAR(50) = ISNULL((SELECT TOP 1 CinsKodu FROM @Cinsiyetler ORDER BY NEWID()), 'CINS-001');

    INSERT INTO ILAC_UYUM (
        ILAC_UYUM_KODU, ILAC_UYUMSUZLUK_TURU, BIRINCI_ILAC_BARKODU, BIRINCI_ETKEN_MADDE_KODU,
        IKINCI_ILAC_BARKODU, IKINCI_ETKEN_MADDE_KODU, BESIN_KODU, YAS_BASLANGIC, YAS_BITIS,
        CINSIYET, RENK_SEVIYE_KODU, ACIKLAMA, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'ILACUYUM-' + RIGHT('000000' + CAST(@IlacUyumNo AS VARCHAR), 6),
        @UyumsuzTur,
        @Ilac1,
        @Etken1,
        @Ilac2,
        @Etken2,
        @Besin,
        CAST((@IlacUyumNo % 10) * 365 AS VARCHAR),
        CAST((((@IlacUyumNo % 10) + 5) * 365) AS VARCHAR),
        @Cins,
        @RenkSev,
        'Ilac uyum kaydi ' + CAST(@IlacUyumNo AS VARCHAR),
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM ILAC_UYUM WHERE ILAC_UYUM_KODU = 'ILACUYUM-' + RIGHT('000000' + CAST(@IlacUyumNo AS VARCHAR), 6));

    SET @IlacUyumNo = @IlacUyumNo + 1;
END;
GO

-- =============================================
-- TIBBI_ORDER (30 kayit)
-- =============================================
PRINT 'TIBBI_ORDER ekleniyor...';

DECLARE @TibbiOrderNo INT = 1;
DECLARE @HastaKoduTbl TABLE (HK NVARCHAR(50));
INSERT INTO @HastaKoduTbl SELECT TOP 30 HASTA_KODU FROM HASTA ORDER BY NEWID();

DECLARE @BasvuruKoduTbl TABLE (BK NVARCHAR(50));
INSERT INTO @BasvuruKoduTbl SELECT TOP 30 HASTA_BASVURU_KODU FROM HASTA_BASVURU ORDER BY NEWID();

DECLARE @PersonelKoduTbl TABLE (PK NVARCHAR(50));
INSERT INTO @PersonelKoduTbl SELECT TOP 30 PERSONEL_KODU FROM PERSONEL ORDER BY NEWID();

DECLARE @OrderTurleri TABLE (OT NVARCHAR(50));
INSERT INTO @OrderTurleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TIBBI_ORDER_TURU';

WHILE @TibbiOrderNo <= 30
BEGIN
    DECLARE @TOHasta NVARCHAR(50) = ISNULL((SELECT TOP 1 HK FROM @HastaKoduTbl ORDER BY NEWID()), 'HST-000001');
    DECLARE @TOBasvuru NVARCHAR(50) = ISNULL((SELECT TOP 1 BK FROM @BasvuruKoduTbl ORDER BY NEWID()), 'BSV-000001');
    DECLARE @TOPersonel NVARCHAR(50) = ISNULL((SELECT TOP 1 PK FROM @PersonelKoduTbl ORDER BY NEWID()), 'PRS-000001');
    DECLARE @TOTur NVARCHAR(50) = ISNULL((SELECT TOP 1 OT FROM @OrderTurleri ORDER BY NEWID()), 'TORDER-001');

    INSERT INTO TIBBI_ORDER (
        TIBBI_ORDER_KODU, HASTA_KODU, HASTA_BASVURU_KODU, TIBBI_ORDER_TURU,
        ORDER_ZAMANI, HEKIM_KODU, ACIKLAMA, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'TORD-' + RIGHT('000000' + CAST(@TibbiOrderNo AS VARCHAR), 6),
        @TOHasta,
        @TOBasvuru,
        @TOTur,
        DATEADD(HOUR, -(@TibbiOrderNo * 2), GETDATE()),
        @TOPersonel,
        'Tibbi order ' + CAST(@TibbiOrderNo AS VARCHAR) + ' - Hekim istemi',
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM TIBBI_ORDER WHERE TIBBI_ORDER_KODU = 'TORD-' + RIGHT('000000' + CAST(@TibbiOrderNo AS VARCHAR), 6));

    SET @TibbiOrderNo = @TibbiOrderNo + 1;
END;
GO

-- =============================================
-- TIBBI_ORDER_DETAY (30 kayit)
-- =============================================
PRINT 'TIBBI_ORDER_DETAY ekleniyor...';

DECLARE @TODetayNo INT = 1;
DECLARE @TibbiOrderKodlari TABLE (TOK NVARCHAR(50));
INSERT INTO @TibbiOrderKodlari SELECT TOP 30 TIBBI_ORDER_KODU FROM TIBBI_ORDER ORDER BY NEWID();

DECLARE @HemsireKodlari TABLE (HK NVARCHAR(50));
INSERT INTO @HemsireKodlari SELECT TOP 30 PERSONEL_KODU FROM PERSONEL ORDER BY NEWID();

DECLARE @IptalNedenleri TABLE (INK NVARCHAR(50));
INSERT INTO @IptalNedenleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TIBBI_ORDER_IPTAL_NEDENI';

WHILE @TODetayNo <= 30
BEGIN
    DECLARE @TODetayOrderKodu NVARCHAR(50) = ISNULL((SELECT TOP 1 TOK FROM @TibbiOrderKodlari ORDER BY NEWID()), 'TORD-000001');
    DECLARE @UygulayanHem NVARCHAR(50) = ISNULL((SELECT TOP 1 HK FROM @HemsireKodlari ORDER BY NEWID()), 'PRS-000001');
    DECLARE @IptalEdenHem NVARCHAR(50) = ISNULL((SELECT TOP 1 HK FROM @HemsireKodlari ORDER BY NEWID()), 'PRS-000001');
    DECLARE @IptalNed NVARCHAR(50) = ISNULL((SELECT TOP 1 INK FROM @IptalNedenleri ORDER BY NEWID()), 'TIPTAL-001');
    DECLARE @UygulamaDurum NVARCHAR(50) = CASE (@TODetayNo % 3) WHEN 0 THEN 'UYGULAND' WHEN 1 THEN 'BEKLIYOR' ELSE 'IPTAL' END;

    INSERT INTO TIBBI_ORDER_DETAY (
        TIBBI_ORDER_DETAY_KODU, TIBBI_ORDER_KODU, PLANLANAN_UYGULANMA_ZAMANI,
        UYGULAYAN_HEMSIRE_KODU, UYGULAMA_ZAMANI, UYGULANMA_DURUMU,
        TIBBI_ORDER_IPTAL_NEDENI, IPTAL_EDEN_HEMSIRE_KODU, IPTAL_ZAMANI,
        ACIKLAMA, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'TODTAY-' + RIGHT('000000' + CAST(@TODetayNo AS VARCHAR), 6),
        @TODetayOrderKodu,
        DATEADD(HOUR, @TODetayNo, GETDATE()),
        @UygulayanHem,
        CASE WHEN @UygulamaDurum = 'UYGULAND' THEN DATEADD(MINUTE, @TODetayNo * 30, GETDATE()) ELSE GETDATE() END,
        @UygulamaDurum,
        @IptalNed,
        @IptalEdenHem,
        CASE WHEN @UygulamaDurum = 'IPTAL' THEN GETDATE() ELSE GETDATE() END,
        'Order detay ' + CAST(@TODetayNo AS VARCHAR),
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM TIBBI_ORDER_DETAY WHERE TIBBI_ORDER_DETAY_KODU = 'TODTAY-' + RIGHT('000000' + CAST(@TODetayNo AS VARCHAR), 6));

    SET @TODetayNo = @TODetayNo + 1;
END;
GO

-- =============================================
-- ASI_BILGISI (30 kayit)
-- =============================================
PRINT 'ASI_BILGISI ekleniyor...';

DECLARE @AsiBilgiNo INT = 1;
DECLARE @AsiBHastaKodlari TABLE (HK NVARCHAR(50));
INSERT INTO @AsiBHastaKodlari SELECT TOP 30 HASTA_KODU FROM HASTA ORDER BY NEWID();

DECLARE @AsiBBasvuruKodlari TABLE (BK NVARCHAR(50));
INSERT INTO @AsiBBasvuruKodlari SELECT TOP 30 HASTA_BASVURU_KODU FROM HASTA_BASVURU ORDER BY NEWID();

DECLARE @AsiKodlari TABLE (AK NVARCHAR(50));
INSERT INTO @AsiKodlari SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI';

DECLARE @AsiDozlari TABLE (AD NVARCHAR(50));
INSERT INTO @AsiDozlari SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_DOZ';

DECLARE @AsiUygSekli TABLE (AUS NVARCHAR(50));
INSERT INTO @AsiUygSekli SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_UYGULAMA_SEKLI';

DECLARE @AsiUygYeri TABLE (AUY NVARCHAR(50));
INSERT INTO @AsiUygYeri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_UYGULAMA_YERI';

DECLARE @AsiIslemTuru TABLE (AIT NVARCHAR(50));
INSERT INTO @AsiIslemTuru SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_ISLEM_TURU';

DECLARE @AsiOzelDurum TABLE (AOD NVARCHAR(50));
INSERT INTO @AsiOzelDurum SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_OZEL_DURUM_NEDENI';

DECLARE @AsieNeden TABLE (AN NVARCHAR(50));
INSERT INTO @AsieNeden SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASIE_NEDENLERI';

DECLARE @AsiYapilmamaDurum TABLE (AYD NVARCHAR(50));
INSERT INTO @AsiYapilmamaDurum SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_YAPILMAMA_DURUMU';

DECLARE @AsiYapilmamaNeden TABLE (AYN NVARCHAR(50));
INSERT INTO @AsiYapilmamaNeden SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ASI_YAPILMAMA_NEDENI';

DECLARE @AlttaYatanHast TABLE (AYH NVARCHAR(50));
INSERT INTO @AlttaYatanHast SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ALTTA_YATAN_HASTALIK';

WHILE @AsiBilgiNo <= 30
BEGIN
    DECLARE @ABHasta NVARCHAR(50) = ISNULL((SELECT TOP 1 HK FROM @AsiBHastaKodlari ORDER BY NEWID()), 'HST-000001');
    DECLARE @ABBasvuru NVARCHAR(50) = ISNULL((SELECT TOP 1 BK FROM @AsiBBasvuruKodlari ORDER BY NEWID()), 'BSV-000001');
    DECLARE @ABAsi NVARCHAR(50) = ISNULL((SELECT TOP 1 AK FROM @AsiKodlari ORDER BY NEWID()), 'ASI-001');
    DECLARE @ABDoz NVARCHAR(50) = ISNULL((SELECT TOP 1 AD FROM @AsiDozlari ORDER BY NEWID()), 'ASIDOZ-001');
    DECLARE @ABUygSekil NVARCHAR(50) = ISNULL((SELECT TOP 1 AUS FROM @AsiUygSekli ORDER BY NEWID()), 'ASIUYG-001');
    DECLARE @ABUygYer NVARCHAR(50) = ISNULL((SELECT TOP 1 AUY FROM @AsiUygYeri ORDER BY NEWID()), 'ASIYER-001');
    DECLARE @ABIslemTur NVARCHAR(50) = ISNULL((SELECT TOP 1 AIT FROM @AsiIslemTuru ORDER BY NEWID()), 'ASIISLM-001');
    DECLARE @ABOzelDurum NVARCHAR(50) = ISNULL((SELECT TOP 1 AOD FROM @AsiOzelDurum ORDER BY NEWID()), 'ASIOZEL-001');
    DECLARE @ABAsieNed NVARCHAR(50) = ISNULL((SELECT TOP 1 AN FROM @AsieNeden ORDER BY NEWID()), 'ASIE-001');
    DECLARE @ABYapDurum NVARCHAR(50) = ISNULL((SELECT TOP 1 AYD FROM @AsiYapilmamaDurum ORDER BY NEWID()), 'ASIYOK-001');
    DECLARE @ABYapNeden NVARCHAR(50) = ISNULL((SELECT TOP 1 AYN FROM @AsiYapilmamaNeden ORDER BY NEWID()), 'ASINEDEN-001');
    DECLARE @ABAlttaYatan NVARCHAR(50) = ISNULL((SELECT TOP 1 AYH FROM @AlttaYatanHast ORDER BY NEWID()), 'ALTHA-001');

    INSERT INTO ASI_BILGISI (
        ASI_BILGISI_KODU, HASTA_KODU, HASTA_BASVURU_KODU, ASI_KODU, ASININ_DOZU,
        ASININ_UYGULAMA_SEKLI, ASI_UYGULAMA_YERI, ASI_SORGU_NUMARASI, ASI_ISLEM_TURU,
        BILGI_ALINAN_KISI_AD_SOYADI, BILGI_ALINAN_KISI_TELEFON, ASI_YAPILMA_ZAMANI,
        ASI_OZEL_DURUM_NEDENI, ASIE_ORTAYA_CIKIS_ZAMANI, ASIE_NEDENLERI,
        ASI_ERTELEME_SURESI, ASI_YAPILMAMA_DURUMU, ASI_YAPILMAMA_NEDENI,
        ALTTA_YATAN_HASTALIK, ACIKLAMA, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'ASIB-' + RIGHT('000000' + CAST(@AsiBilgiNo AS VARCHAR), 6),
        @ABHasta,
        @ABBasvuru,
        @ABAsi,
        @ABDoz,
        @ABUygSekil,
        @ABUygYer,
        'ASI-SRG-' + RIGHT('00000000' + CAST(@AsiBilgiNo * 1000 AS VARCHAR), 8),
        @ABIslemTur,
        'Veli ' + CAST(@AsiBilgiNo AS VARCHAR),
        '053' + RIGHT('00000000' + CAST(@AsiBilgiNo * 123456 AS VARCHAR), 8),
        DATEADD(DAY, -(@AsiBilgiNo * 7), GETDATE()),
        @ABOzelDurum,
        DATEADD(DAY, -(@AsiBilgiNo * 7) + 1, GETDATE()),
        @ABAsieNed,
        CAST((@AsiBilgiNo % 30) AS VARCHAR),
        @ABYapDurum,
        @ABYapNeden,
        @ABAlttaYatan,
        'Asi bilgisi ' + CAST(@AsiBilgiNo AS VARCHAR),
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM ASI_BILGISI WHERE ASI_BILGISI_KODU = 'ASIB-' + RIGHT('000000' + CAST(@AsiBilgiNo AS VARCHAR), 6));

    SET @AsiBilgiNo = @AsiBilgiNo + 1;
END;
GO

-- =============================================
-- BAKTERI_SONUC (30 kayit)
-- =============================================
PRINT 'BAKTERI_SONUC ekleniyor...';

DECLARE @BakteriSonucNo INT = 1;
DECLARE @TetkikSonucKodlari TABLE (TSK NVARCHAR(50));
INSERT INTO @TetkikSonucKodlari SELECT TOP 30 TETKIK_SONUC_KODU FROM TETKIK_SONUC ORDER BY NEWID();

DECLARE @BakteriKodlari TABLE (BK NVARCHAR(50));
INSERT INTO @BakteriKodlari SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'BAKTERI';

WHILE @BakteriSonucNo <= 30
BEGIN
    DECLARE @BSTetkikSonuc NVARCHAR(50) = ISNULL((SELECT TOP 1 TSK FROM @TetkikSonucKodlari ORDER BY NEWID()), 'TTKSN-000001');
    DECLARE @BSBakteri NVARCHAR(50) = ISNULL((SELECT TOP 1 BK FROM @BakteriKodlari ORDER BY NEWID()), 'BAK-001');

    INSERT INTO BAKTERI_SONUC (
        BAKTERI_SONUC_KODU, TETKIK_SONUC_KODU, BAKTERI_KODU, KOLONI_SAYISI,
        RAPOR_SONUC_SIRASI, ACIKLAMA, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'BAKTSNC-' + RIGHT('000000' + CAST(@BakteriSonucNo AS VARCHAR), 6),
        @BSTetkikSonuc,
        @BSBakteri,
        CAST((@BakteriSonucNo * 1000 + 5000) AS VARCHAR),
        CAST(@BakteriSonucNo AS VARCHAR),
        'Bakteri sonuc ' + CAST(@BakteriSonucNo AS VARCHAR) + ' - Kultur sonucu',
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM BAKTERI_SONUC WHERE BAKTERI_SONUC_KODU = 'BAKTSNC-' + RIGHT('000000' + CAST(@BakteriSonucNo AS VARCHAR), 6));

    SET @BakteriSonucNo = @BakteriSonucNo + 1;
END;
GO

-- =============================================
-- ANTIBIYOTIK_SONUC (30 kayit)
-- =============================================
PRINT 'ANTIBIYOTIK_SONUC ekleniyor...';

DECLARE @AntibiyotikSonucNo INT = 1;
DECLARE @BakteriSonucKodlari TABLE (BSK NVARCHAR(50));
INSERT INTO @BakteriSonucKodlari SELECT TOP 30 BAKTERI_SONUC_KODU FROM BAKTERI_SONUC ORDER BY NEWID();

DECLARE @AntibiyotikKodlari TABLE (AK NVARCHAR(50));
INSERT INTO @AntibiyotikKodlari SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ANTIBIYOTIK';

DECLARE @AntibiyotikSonuclari TABLE (ASN NVARCHAR(50));
INSERT INTO @AntibiyotikSonuclari SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'ANTIBIYOTIK_SONUC';

WHILE @AntibiyotikSonucNo <= 30
BEGIN
    DECLARE @ASBakteriSonuc NVARCHAR(50) = ISNULL((SELECT TOP 1 BSK FROM @BakteriSonucKodlari ORDER BY NEWID()), 'BAKTSNC-000001');
    DECLARE @ASAntibiyotik NVARCHAR(50) = ISNULL((SELECT TOP 1 AK FROM @AntibiyotikKodlari ORDER BY NEWID()), 'ANT-001');
    DECLARE @ASSonuc NVARCHAR(50) = ISNULL((SELECT TOP 1 ASN FROM @AntibiyotikSonuclari ORDER BY NEWID()), 'ANTSONUC-001');

    INSERT INTO ANTIBIYOTIK_SONUC (
        ANTIBIYOTIK_SONUC_KODU, BAKTERI_SONUC_KODU, ANTIBIYOTIK_KODU, TETKIK_SONUCU,
        ZON_CAPI, ACIKLAMA, RAPORDA_GORULME_DURUMU, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'ANTSNC-' + RIGHT('000000' + CAST(@AntibiyotikSonucNo AS VARCHAR), 6),
        @ASBakteriSonuc,
        @ASAntibiyotik,
        @ASSonuc,
        CAST((10 + (@AntibiyotikSonucNo % 30)) AS VARCHAR),
        'Antibiyotik duyarlilik testi ' + CAST(@AntibiyotikSonucNo AS VARCHAR),
        CASE (@AntibiyotikSonucNo % 2) WHEN 0 THEN 'Gorunur' ELSE 'Gizli' END,
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM ANTIBIYOTIK_SONUC WHERE ANTIBIYOTIK_SONUC_KODU = 'ANTSNC-' + RIGHT('000000' + CAST(@AntibiyotikSonucNo AS VARCHAR), 6));

    SET @AntibiyotikSonucNo = @AntibiyotikSonucNo + 1;
END;
GO

-- =============================================
-- RISK_SKORLAMA (30 kayit)
-- =============================================
PRINT 'RISK_SKORLAMA ekleniyor...';

DECLARE @RiskSkorNo INT = 1;
DECLARE @RSHastaKodlari TABLE (HK NVARCHAR(50));
INSERT INTO @RSHastaKodlari SELECT TOP 30 HASTA_KODU FROM HASTA ORDER BY NEWID();

DECLARE @RSBasvuruKodlari TABLE (BK NVARCHAR(50));
INSERT INTO @RSBasvuruKodlari SELECT TOP 30 HASTA_BASVURU_KODU FROM HASTA_BASVURU ORDER BY NEWID();

DECLARE @RSOrderDetayKodlari TABLE (ODK NVARCHAR(50));
INSERT INTO @RSOrderDetayKodlari SELECT TOP 30 TIBBI_ORDER_DETAY_KODU FROM TIBBI_ORDER_DETAY ORDER BY NEWID();

DECLARE @RiskTurleri TABLE (RT NVARCHAR(50));
INSERT INTO @RiskTurleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'RISK_SKORLAMA_TURU';

WHILE @RiskSkorNo <= 30
BEGIN
    DECLARE @RSHasta NVARCHAR(50) = ISNULL((SELECT TOP 1 HK FROM @RSHastaKodlari ORDER BY NEWID()), 'HST-000001');
    DECLARE @RSBasvuru NVARCHAR(50) = ISNULL((SELECT TOP 1 BK FROM @RSBasvuruKodlari ORDER BY NEWID()), 'BSV-000001');
    DECLARE @RSOrderDetay NVARCHAR(50) = ISNULL((SELECT TOP 1 ODK FROM @RSOrderDetayKodlari ORDER BY NEWID()), 'TODTAY-000001');
    DECLARE @RSRiskTur NVARCHAR(50) = ISNULL((SELECT TOP 1 RT FROM @RiskTurleri ORDER BY NEWID()), 'RISK-001');
    DECLARE @ToplamPuan INT = 5 + (@RiskSkorNo % 50);
    DECLARE @OlumOrani DECIMAL(5,2) = CAST((@RiskSkorNo % 50) AS DECIMAL(5,2));

    INSERT INTO RISK_SKORLAMA (
        RISK_SKORLAMA_KODU, HASTA_BASVURU_KODU, HASTA_KODU, RISK_SKORLAMA_TURU,
        ISLEM_ZAMANI, RISK_SKORLAMA_TOPLAM_PUANI, BEKLENEN_OLUM_ORANI,
        GLASGOW_SKALASI, DUZELTILMISBEKLENEN_OLUM_ORANI, TIBBI_ORDER_DETAY_KODU,
        ACIKLAMA, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'RISKSK-' + RIGHT('000000' + CAST(@RiskSkorNo AS VARCHAR), 6),
        @RSBasvuru,
        @RSHasta,
        @RSRiskTur,
        DATEADD(HOUR, -(@RiskSkorNo * 4), GETDATE()),
        CAST(@ToplamPuan AS VARCHAR),
        CAST(@OlumOrani AS VARCHAR) + '%',
        CAST((8 + (@RiskSkorNo % 7)) AS VARCHAR),
        CAST((@OlumOrani + 2) AS VARCHAR) + '%',
        @RSOrderDetay,
        'Risk skorlama degerlendirmesi ' + CAST(@RiskSkorNo AS VARCHAR),
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM RISK_SKORLAMA WHERE RISK_SKORLAMA_KODU = 'RISKSK-' + RIGHT('000000' + CAST(@RiskSkorNo AS VARCHAR), 6));

    SET @RiskSkorNo = @RiskSkorNo + 1;
END;
GO

-- =============================================
-- RISK_SKORLAMA_DETAY (30 kayit)
-- =============================================
PRINT 'RISK_SKORLAMA_DETAY ekleniyor...';

DECLARE @RiskDetayNo INT = 1;
DECLARE @RiskSkorKodlari TABLE (RSK NVARCHAR(50));
INSERT INTO @RiskSkorKodlari SELECT TOP 30 RISK_SKORLAMA_KODU FROM RISK_SKORLAMA ORDER BY NEWID();

DECLARE @RiskAltTurleri TABLE (RAT NVARCHAR(50));
INSERT INTO @RiskAltTurleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'RISK_SKORLAMA_ALT_TURU';

WHILE @RiskDetayNo <= 30
BEGIN
    DECLARE @RDRiskSkor NVARCHAR(50) = ISNULL((SELECT TOP 1 RSK FROM @RiskSkorKodlari ORDER BY NEWID()), 'RISKSK-000001');
    DECLARE @RDAltTur NVARCHAR(50) = ISNULL((SELECT TOP 1 RAT FROM @RiskAltTurleri ORDER BY NEWID()), 'RISKALT-001');

    INSERT INTO RISK_SKORLAMA_DETAY (
        RISK_SKORLAMA_DETAY_KODU, RISK_SKORLAMA_KODU, GLASGOW_SKALASI,
        RISK_SKORLAMA_ALT_TURU, RISK_SKOR_DEGERI, ACIKLAMA,
        EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'RISKDT-' + RIGHT('000000' + CAST(@RiskDetayNo AS VARCHAR), 6),
        @RDRiskSkor,
        CAST((8 + (@RiskDetayNo % 7)) AS VARCHAR),
        @RDAltTur,
        CAST((@RiskDetayNo % 10) AS VARCHAR),
        'Risk skorlama detay ' + CAST(@RiskDetayNo AS VARCHAR),
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM RISK_SKORLAMA_DETAY WHERE RISK_SKORLAMA_DETAY_KODU = 'RISKDT-' + RIGHT('000000' + CAST(@RiskDetayNo AS VARCHAR), 6));

    SET @RiskDetayNo = @RiskDetayNo + 1;
END;
GO

-- =============================================
-- SYS_PAKET (30 kayit)
-- =============================================
PRINT 'SYS_PAKET ekleniyor...';

DECLARE @SysPaketNo INT = 1;
DECLARE @SPHastaKodlari TABLE (HK NVARCHAR(50));
INSERT INTO @SPHastaKodlari SELECT TOP 30 HASTA_KODU FROM HASTA ORDER BY NEWID();

DECLARE @SPBasvuruKodlari TABLE (BK NVARCHAR(50));
INSERT INTO @SPBasvuruKodlari SELECT TOP 30 HASTA_BASVURU_KODU FROM HASTA_BASVURU ORDER BY NEWID();

WHILE @SysPaketNo <= 30
BEGIN
    DECLARE @SPHasta NVARCHAR(50) = ISNULL((SELECT TOP 1 HK FROM @SPHastaKodlari ORDER BY NEWID()), 'HST-000001');
    DECLARE @SPBasvuru NVARCHAR(50) = ISNULL((SELECT TOP 1 BK FROM @SPBasvuruKodlari ORDER BY NEWID()), 'BSV-000001');
    DECLARE @GonderimDurum NVARCHAR(20) = CASE (@SysPaketNo % 3) WHEN 0 THEN 'GONDERILDI' WHEN 1 THEN 'BEKLEMEDE' ELSE 'HATA' END;

    INSERT INTO SYS_PAKET (
        SYS_PAKET_KODU, HASTA_BASVURU_KODU, HASTA_KODU, VERI_PAKETI_NUMARASI,
        VERI_PAKETI_GONDERILME_ZAMANI, VERI_PAKETI_GONDERIM_DURUMU,
        GONDERILEN_PAKET_BILGISI, GELEN_CEVAP_BILGISI,
        EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'SYSPKT-' + RIGHT('000000' + CAST(@SysPaketNo AS VARCHAR), 6),
        @SPBasvuru,
        @SPHasta,
        'PKT-' + RIGHT('0000000000' + CAST(@SysPaketNo * 12345 AS VARCHAR), 10),
        DATEADD(HOUR, -(@SysPaketNo * 2), GETDATE()),
        @GonderimDurum,
        '<PaketBilgisi><Tip>MUAYENE</Tip><No>' + CAST(@SysPaketNo AS VARCHAR) + '</No></PaketBilgisi>',
        '<Cevap><Durum>' + @GonderimDurum + '</Durum><Mesaj>Islem tamamlandi</Mesaj></Cevap>',
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM SYS_PAKET WHERE SYS_PAKET_KODU = 'SYSPKT-' + RIGHT('000000' + CAST(@SysPaketNo AS VARCHAR), 6));

    SET @SysPaketNo = @SysPaketNo + 1;
END;
GO

-- =============================================
-- MEDULA_TAKIP (30 kayit)
-- =============================================
PRINT 'MEDULA_TAKIP ekleniyor...';

DECLARE @MedulaTakipNo INT = 1;
DECLARE @MTHastaKodlari TABLE (HK NVARCHAR(50));
INSERT INTO @MTHastaKodlari SELECT TOP 30 HASTA_KODU FROM HASTA ORDER BY NEWID();

DECLARE @MTBasvuruKodlari TABLE (BK NVARCHAR(50));
INSERT INTO @MTBasvuruKodlari SELECT TOP 30 HASTA_BASVURU_KODU FROM HASTA_BASVURU ORDER BY NEWID();

DECLARE @ProvizyonTurleri TABLE (PT NVARCHAR(50));
INSERT INTO @ProvizyonTurleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'PROVIZYON_TURU';

DECLARE @TakipTipleri TABLE (TT NVARCHAR(50));
INSERT INTO @TakipTipleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TAKIP_TIPI';

DECLARE @TedaviTurleri TABLE (TDT NVARCHAR(50));
INSERT INTO @TedaviTurleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TEDAVI_TURU';

DECLARE @TedaviTipleri TABLE (TDP NVARCHAR(50));
INSERT INTO @TedaviTipleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TEDAVI_TIPI';

DECLARE @TedaviSekilleri TABLE (TDS NVARCHAR(50));
INSERT INTO @TedaviSekilleri SELECT REFERANS_KODU FROM REFERANS_KODLAR WHERE REFERANS_TIPI = 'TEDAVI_SEKLI';

WHILE @MedulaTakipNo <= 30
BEGIN
    DECLARE @MTHasta NVARCHAR(50) = ISNULL((SELECT TOP 1 HK FROM @MTHastaKodlari ORDER BY NEWID()), 'HST-000001');
    DECLARE @MTBasvuru NVARCHAR(50) = ISNULL((SELECT TOP 1 BK FROM @MTBasvuruKodlari ORDER BY NEWID()), 'BSV-000001');
    DECLARE @MTProv NVARCHAR(50) = ISNULL((SELECT TOP 1 PT FROM @ProvizyonTurleri ORDER BY NEWID()), 'PROV-001');
    DECLARE @MTTakipTip NVARCHAR(50) = ISNULL((SELECT TOP 1 TT FROM @TakipTipleri ORDER BY NEWID()), 'TAKIP-001');
    DECLARE @MTTedaviTur NVARCHAR(50) = (SELECT TOP 1 TDT FROM @TedaviTurleri ORDER BY NEWID());
    DECLARE @MTTedaviTip NVARCHAR(50) = (SELECT TOP 1 TDP FROM @TedaviTipleri ORDER BY NEWID());
    DECLARE @MTTedaviSekil NVARCHAR(50) = ISNULL((SELECT TOP 1 TDS FROM @TedaviSekilleri ORDER BY NEWID()), 'TEDSEK-001');
    DECLARE @TCNo NVARCHAR(11) = RIGHT('00000000000' + CAST(10000000000 + (@MedulaTakipNo * 123456789) AS VARCHAR), 11);

    INSERT INTO MEDULA_TAKIP (
        MEDULA_TAKIP_KODU, HASTA_BASVURU_KODU, HASTA_KODU, SGK_TAKIP_NUMARASI,
        SGK_ILKTAKIP_NUMARASI, MEDULA_TESIS_KODU, MEDULA_BRANS_KODU, PROVIZYON_TURU,
        PROVIZYON_TARIHI, TC_KIMLIK_NUMARASI, CINSIYET, MEDULA_TUTARI,
        FATURA_TESLIM_NUMARASI, FATURA_TESLIM_TARIHI, TEDAVI_TURU, SIGORTALI_TURU,
        DEVREDILEN_KURUM, SONUC_KODU, SONUC_MESAJI, TAKIP_TIPI, BASVURU_NUMARASI,
        TEDAVI_TIPI, TEDAVI_SEKLI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
    )
    SELECT
        'MEDTK-' + RIGHT('000000' + CAST(@MedulaTakipNo AS VARCHAR), 6),
        @MTBasvuru,
        @MTHasta,
        'TKP' + RIGHT('0000000000' + CAST(@MedulaTakipNo * 11111 AS VARCHAR), 10),
        'ILKTKP' + RIGHT('0000000000' + CAST(@MedulaTakipNo * 11111 AS VARCHAR), 10),
        '11068888',
        CAST(4400 + (@MedulaTakipNo % 10) AS VARCHAR),
        @MTProv,
        DATEADD(DAY, -(@MedulaTakipNo * 2), GETDATE()),
        @TCNo,
        CASE (@MedulaTakipNo % 2) WHEN 0 THEN 'E' ELSE 'K' END,
        CAST(100 + (@MedulaTakipNo * 50) AS VARCHAR) + '.00',
        'FTR' + RIGHT('0000000000' + CAST(@MedulaTakipNo * 99999 AS VARCHAR), 10),
        DATEADD(DAY, -(@MedulaTakipNo * 2) + 5, GETDATE()),
        @MTTedaviTur,
        CASE (@MedulaTakipNo % 4) WHEN 0 THEN 'CALISAN' WHEN 1 THEN 'EMEKLI' WHEN 2 THEN 'BAKMAKLA_YUKUMLU' ELSE 'DIGER' END,
        'SGK',
        '0',
        'Islem basarili',
        @MTTakipTip,
        'BSV' + RIGHT('0000000000' + CAST(@MedulaTakipNo * 77777 AS VARCHAR), 10),
        @MTTedaviTip,
        @MTTedaviSekil,
        'SYSTEM', GETDATE()
    WHERE NOT EXISTS (SELECT 1 FROM MEDULA_TAKIP WHERE MEDULA_TAKIP_KODU = 'MEDTK-' + RIGHT('000000' + CAST(@MedulaTakipNo AS VARCHAR), 6));

    SET @MedulaTakipNo = @MedulaTakipNo + 1;
END;
GO

PRINT 'Part 6 tamamlandi!';
PRINT 'Eklenen tablolar: SILINEN_KAYITLAR, ILAC_UYUM, TIBBI_ORDER, TIBBI_ORDER_DETAY, ASI_BILGISI, BAKTERI_SONUC, ANTIBIYOTIK_SONUC, RISK_SKORLAMA, RISK_SKORLAMA_DETAY, SYS_PAKET, MEDULA_TAKIP';
GO
