-- =====================================================
-- LBYS Kalan Tablolar Seed Data Script
-- 78 Tablo icin 25-30 kayit
-- Olusturma: 2026-01-09
-- =====================================================

SET NOCOUNT ON;
GO

-- =====================================================
-- BOLUM 1: REFERANS KODLARI (FK'ler icin gerekli)
-- =====================================================

PRINT 'Referans kodlari ekleniyor...';

-- AMELIYAT referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'AML_TURU_MAJÖR')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('AML_TURU_MAJÖR', 'AMELIYAT_TURU', 'Majör Ameliyat', 'M', 'M', 'M', 'M', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'AML_TURU_MINÖR')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('AML_TURU_MINÖR', 'AMELIYAT_TURU', 'Minör Ameliyat', 'MI', 'MI', 'MI', 'MI', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'AML_DURUMU_PLANLANDI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('AML_DURUMU_PLANLANDI', 'AMELIYAT_DURUMU', 'Planlandı', 'P', 'P', 'P', 'P', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'AML_DURUMU_TAMAMLANDI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('AML_DURUMU_TAMAMLANDI', 'AMELIYAT_DURUMU', 'Tamamlandı', 'T', 'T', 'T', 'T', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'ANESTEZI_GENEL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('ANESTEZI_GENEL', 'ANESTEZI_TURU', 'Genel Anestezi', 'G', 'G', 'G', 'G', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'ANESTEZI_LOKAL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('ANESTEZI_LOKAL', 'ANESTEZI_TURU', 'Lokal Anestezi', 'L', 'L', 'L', 'L', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'ANESTEZI_SPINAL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('ANESTEZI_SPINAL', 'ANESTEZI_TURU', 'Spinal Anestezi', 'S', 'S', 'S', 'S', 'KLN-ADMIN', GETDATE());

-- AMELIYAT_ISLEM referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KESI_ORANI_TAM')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KESI_ORANI_TAM', 'KESI_ORANI', 'Tam', '100', '100', '100', '100', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KESI_ORANI_YARIM')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KESI_ORANI_YARIM', 'KESI_ORANI', 'Yarım', '50', '50', '50', '50', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KESI_SEANS_TEK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KESI_SEANS_TEK', 'KESI_SEANS_BILGISI', 'Tek Seans', '1', '1', '1', '1', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'TARAF_SAG')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('TARAF_SAG', 'TARAF_BILGISI', 'Sağ', 'S', 'S', 'S', 'S', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'TARAF_SOL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('TARAF_SOL', 'TARAF_BILGISI', 'Sol', 'SO', 'SO', 'SO', 'SO', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'TARAF_BILATERAL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('TARAF_BILATERAL', 'TARAF_BILGISI', 'Bilateral', 'B', 'B', 'B', 'B', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'ASA_1')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('ASA_1', 'ASA_SKORU', 'ASA I - Sağlıklı', '1', '1', '1', '1', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'ASA_2')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('ASA_2', 'ASA_SKORU', 'ASA II - Hafif Sistemik Hastalık', '2', '2', '2', '2', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'EUROSCORE_DUSUK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('EUROSCORE_DUSUK', 'EUROSCORE', 'Düşük Risk', 'D', 'D', 'D', 'D', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'YARA_TEMIZ')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('YARA_TEMIZ', 'YARA_SINIFI', 'Temiz Yara', 'T', 'T', 'T', 'T', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'GOREV_CERRAH')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('GOREV_CERRAH', 'AMELIYAT_PERSONEL_GOREV', 'Cerrah', 'C', 'C', 'C', 'C', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'GOREV_ASISTAN')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('GOREV_ASISTAN', 'AMELIYAT_PERSONEL_GOREV', 'Asistan', 'A', 'A', 'A', 'A', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'GOREV_HEMSIRE')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('GOREV_HEMSIRE', 'AMELIYAT_PERSONEL_GOREV', 'Hemşire', 'H', 'H', 'H', 'H', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'GOREV_ANESTEZIST')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('GOREV_ANESTEZIST', 'AMELIYAT_PERSONEL_GOREV', 'Anestezist', 'AN', 'AN', 'AN', 'AN', 'KLN-ADMIN', GETDATE());

-- RECETE referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'RCT_TURU_NORMAL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('RCT_TURU_NORMAL', 'RECETE_TURU', 'Normal Reçete', 'N', 'N', 'N', 'N', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'RCT_TURU_KIRMIZI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('RCT_TURU_KIRMIZI', 'RECETE_TURU', 'Kırmızı Reçete', 'K', 'K', 'K', 'K', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'RCT_TURU_YESIL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('RCT_TURU_YESIL', 'RECETE_TURU', 'Yeşil Reçete', 'Y', 'Y', 'Y', 'Y', 'KLN-ADMIN', GETDATE());

-- RECETE_ILAC referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'DOZ_BIRIM_MG')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('DOZ_BIRIM_MG', 'DOZ_BIRIM', 'Miligram', 'MG', 'MG', 'MG', 'MG', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'DOZ_BIRIM_ML')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('DOZ_BIRIM_ML', 'DOZ_BIRIM', 'Mililitre', 'ML', 'ML', 'ML', 'ML', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KULLANIM_ORAL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KULLANIM_ORAL', 'ILAC_KULLANIM_SEKLI', 'Ağızdan', 'O', 'O', 'O', 'O', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KULLANIM_IV')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KULLANIM_IV', 'ILAC_KULLANIM_SEKLI', 'İntravenöz', 'IV', 'IV', 'IV', 'IV', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'PERIYOT_GUN')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('PERIYOT_GUN', 'ILAC_KULLANIM_PERIYODU_BIRIMI', 'Gün', 'G', 'G', 'G', 'G', 'KLN-ADMIN', GETDATE());

-- KAN referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_GRUBU_A_RH_POZ')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_GRUBU_A_RH_POZ', 'KAN_GRUBU', 'A Rh+', 'A+', 'A+', 'A+', 'A+', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_GRUBU_B_RH_POZ')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_GRUBU_B_RH_POZ', 'KAN_GRUBU', 'B Rh+', 'B+', 'B+', 'B+', 'B+', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_GRUBU_0_RH_POZ')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_GRUBU_0_RH_POZ', 'KAN_GRUBU', '0 Rh+', '0+', '0+', '0+', '0+', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_GRUBU_AB_RH_POZ')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_GRUBU_AB_RH_POZ', 'KAN_GRUBU', 'AB Rh+', 'AB+', 'AB+', 'AB+', 'AB+', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_STOK_MEVCUT')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_STOK_MEVCUT', 'KAN_STOK_DURUMU', 'Mevcut', 'M', 'M', 'M', 'M', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_TALEP_ACIL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_TALEP_ACIL', 'KAN_TALEP_ACILIYET_SEVIYESI', 'Acil', 'A', 'A', 'A', 'A', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_TALEP_NORMAL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_TALEP_NORMAL', 'KAN_TALEP_ACILIYET_SEVIYESI', 'Normal', 'N', 'N', 'N', 'N', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_NEDEN_AMELIYAT')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_NEDEN_AMELIYAT', 'KAN_TALEP_NEDENI', 'Ameliyat', 'A', 'A', 'A', 'A', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_ENDIK_ANEMI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_ENDIK_ANEMI', 'KAN_ENDIKASYON_TURU', 'Anemi', 'AN', 'AN', 'AN', 'AN', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KAN_RET_STOK_YOK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KAN_RET_STOK_YOK', 'KAN_TALEP_RET_NEDENI', 'Stok Yok', 'SY', 'SY', 'SY', 'SY', 'KLN-ADMIN', GETDATE());

-- DOGUM referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'DOGUM_NORMAL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('DOGUM_NORMAL', 'DOGUM_YONTEMI', 'Normal Doğum', 'N', 'N', 'N', 'N', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'DOGUM_SEZARYEN')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('DOGUM_SEZARYEN', 'DOGUM_YONTEMI', 'Sezaryen', 'S', 'S', 'S', 'S', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'CINSIYET_ERKEK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('CINSIYET_ERKEK', 'CINSIYET', 'Erkek', 'E', 'E', 'E', 'E', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'CINSIYET_KADIN')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('CINSIYET_KADIN', 'CINSIYET', 'Kadın', 'K', 'K', 'K', 'K', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'KOMPLIKASYON_YOK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('KOMPLIKASYON_YOK', 'KOMPLIKASYON_TANISI', 'Komplikasyon Yok', 'Y', 'Y', 'Y', 'Y', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'PROGNOZ_IYI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('PROGNOZ_IYI', 'PROGNOZ_BILGISI', 'İyi', 'I', 'I', 'I', 'I', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'SURMATURE_YOK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('SURMATURE_YOK', 'SURMATURE_BILGISI', 'Yok', 'Y', 'Y', 'Y', 'Y', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'K_VIT_UYGULANDI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('K_VIT_UYGULANDI', 'K_VITAMINI_UYGULANMA_DURUMU', 'Uygulandı', 'U', 'U', 'U', 'U', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'HEPATIT_YAPILDI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('HEPATIT_YAPILDI', 'BEBEGIN_HEPATIT_ASI_DURUMU', 'Yapıldı', 'Y', 'Y', 'Y', 'Y', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'ISITME_NORMAL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('ISITME_NORMAL', 'YENIDOGAN_ISITME_TARAMA_DURUMU', 'Normal', 'N', 'N', 'N', 'N', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'TOPUK_ALINDI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('TOPUK_ALINDI', 'TOPUK_KANI', 'Alındı', 'A', 'A', 'A', 'A', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'BEBEK_CANLI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('BEBEK_CANLI', 'BEBEGIN_YASAM_DURUMU', 'Canlı', 'C', 'C', 'C', 'C', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'SEZARYEN_YOK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('SEZARYEN_YOK', 'SEZARYEN_ENDIKASYONLAR', 'Endikasyon Yok', 'Y', 'Y', 'Y', 'Y', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'ROBSON_1')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('ROBSON_1', 'ROBSON_GRUBU', 'Grup 1', '1', '1', '1', '1', 'KLN-ADMIN', GETDATE());

-- VEZNE referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'TAHSIL_NAKIT')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('TAHSIL_NAKIT', 'TAHSIL_TURU', 'Nakit', 'N', 'N', 'N', 'N', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'TAHSIL_KREDI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('TAHSIL_KREDI', 'TAHSIL_TURU', 'Kredi Kartı', 'K', 'K', 'K', 'K', 'KLN-ADMIN', GETDATE());

-- RADYOLOJI referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'TETKIK_BEKLEMEDE')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('TETKIK_BEKLEMEDE', 'TETKIK_ISTENME_DURUMU', 'Beklemede', 'B', 'B', 'B', 'B', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'TETKIK_TAMAMLANDI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('TETKIK_TAMAMLANDI', 'TETKIK_ISTENME_DURUMU', 'Tamamlandı', 'T', 'T', 'T', 'T', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'RAPOR_FORMAT_METIN')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('RAPOR_FORMAT_METIN', 'RADYOLOJI_RAPOR_FORMATI', 'Metin', 'M', 'M', 'M', 'M', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'RAPOR_TIP_ANA')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('RAPOR_TIP_ANA', 'RAPOR_TIPI', 'Ana Rapor', 'A', 'A', 'A', 'A', 'KLN-ADMIN', GETDATE());

-- STOK referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'HAREKET_GIRIS')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('HAREKET_GIRIS', 'HAREKET_SEKLI', 'Giriş', 'G', 'G', 'G', 'G', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'HAREKET_CIKIS')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('HAREKET_CIKIS', 'HAREKET_SEKLI', 'Çıkış', 'C', 'C', 'C', 'C', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'IHALE_ACIK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('IHALE_ACIK', 'IHALE_TURU', 'Açık İhale', 'A', 'A', 'A', 'A', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'BUTCE_DONER')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('BUTCE_DONER', 'BUTCE_TURU', 'Döner Sermaye', 'D', 'D', 'D', 'D', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'STOK_ISTEK_BEKLEMEDE')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('STOK_ISTEK_BEKLEMEDE', 'STOK_ISTEK_DURUMU', 'Beklemede', 'B', 'B', 'B', 'B', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'STOK_ISTEK_ONAYLANDI')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('STOK_ISTEK_ONAYLANDI', 'STOK_ISTEK_DURUMU', 'Onaylandı', 'O', 'O', 'O', 'O', 'KLN-ADMIN', GETDATE());

-- Diger gerekli referans kodlari
IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'OLCU_ADET')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('OLCU_ADET', 'OLCU', 'Adet', 'AD', 'AD', 'AD', 'AD', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'SEVK_NEDENI_UZMANLIK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('SEVK_NEDENI_UZMANLIK', 'SEVK_NEDENI', 'Uzmanlık Gerektiren Durum', 'U', 'U', 'U', 'U', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'SEVK_TURU_ACIL')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('SEVK_TURU_ACIL', 'SEVK_TURU', 'Acil Sevk', 'A', 'A', 'A', 'A', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'IZLEM_1')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('IZLEM_1', 'KACINCI_IZLEM', '1. İzlem', '1', '1', '1', '1', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'GEBE_IZLEM_RUTIN')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('GEBE_IZLEM_RUTIN', 'GEBE_IZLEM_ISLEM_TURU', 'Rutin İzlem', 'R', 'R', 'R', 'R', 'KLN-ADMIN', GETDATE());

IF NOT EXISTS (SELECT 1 FROM REFERANS_KODLAR WHERE REFERANS_KODU = 'ONCEKI_DOGUM_ILK')
INSERT INTO REFERANS_KODLAR (REFERANS_KODU, REFERANS_TIPI, REFERANS_ADI, DEGER1, DEGER2, DEGER3, DEGER4, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
VALUES ('ONCEKI_DOGUM_ILK', 'ONCEKI_DOGUM_DURUMU', 'İlk Gebelik', 'I', 'I', 'I', 'I', 'KLN-ADMIN', GETDATE());

PRINT 'Referans kodlari eklendi.';
GO

-- =====================================================
-- BOLUM 2: TEMEL TABLOLAR (Level 1)
-- =====================================================

PRINT 'Level 1 tablolar seed ediliyor...';

-- 1. AMELIYAT (30 kayit)
IF NOT EXISTS (SELECT 1 FROM AMELIYAT WHERE AMELIYAT_KODU LIKE 'AML-SEED-%')
BEGIN
    PRINT 'AMELIYAT tablosu seed ediliyor...';

    DECLARE @i INT = 1;
    DECLARE @hastaKodu NVARCHAR(50);
    DECLARE @basvuruKodu NVARCHAR(50);
    DECLARE @birimKodu NVARCHAR(50);

    -- Mevcut HASTA ve HASTA_BASVURU kayitlarini al
    SELECT TOP 1 @hastaKodu = HASTA_KODU FROM HASTA;
    SELECT TOP 1 @basvuruKodu = HASTA_BASVURU_KODU FROM HASTA_BASVURU;
    SELECT TOP 1 @birimKodu = BIRIM_KODU FROM BIRIM;

    WHILE @i <= 30
    BEGIN
        INSERT INTO AMELIYAT (
            AMELIYAT_KODU, HASTA_KODU, HASTA_BASVURU_KODU, AMELIYAT_ADI, AMELIYAT_TURU,
            AMELIYAT_BASLAMA_ZAMANI, AMELIYAT_BITIS_ZAMANI, BIRIM_KODU, DEFTER_NUMARASI,
            AMELIYAT_DURUMU, ANESTEZI_TURU, ANESTEZI_NOTU, ANESTEZI_BASLAMA_ZAMANI,
            ANESTEZI_BITIS_ZAMANI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
        )
        VALUES (
            'AML-SEED-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            @hastaKodu,
            @basvuruKodu,
            CASE @i % 5
                WHEN 0 THEN 'Apandektomi'
                WHEN 1 THEN 'Kolesistektomi'
                WHEN 2 THEN 'Herni Onarımı'
                WHEN 3 THEN 'Artroskopi'
                ELSE 'Laparoskopik Cerrahi'
            END,
            CASE @i % 2 WHEN 0 THEN 'AML_TURU_MAJÖR' ELSE 'AML_TURU_MINÖR' END,
            DATEADD(DAY, -@i, DATEADD(HOUR, 8, GETDATE())),
            DATEADD(DAY, -@i, DATEADD(HOUR, 11, GETDATE())),
            @birimKodu,
            'DEF-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            'AML_DURUMU_TAMAMLANDI',
            CASE @i % 3 WHEN 0 THEN 'ANESTEZI_GENEL' WHEN 1 THEN 'ANESTEZI_LOKAL' ELSE 'ANESTEZI_SPINAL' END,
            'Anestezi normal seyretti.',
            DATEADD(DAY, -@i, DATEADD(HOUR, 7, GETDATE())),
            DATEADD(DAY, -@i, DATEADD(HOUR, 12, GETDATE())),
            'KLN-ADMIN',
            GETDATE()
        );
        SET @i = @i + 1;
    END;
    PRINT 'AMELIYAT: 30 kayit eklendi.';
END;
GO

-- 2. RECETE (30 kayit)
IF NOT EXISTS (SELECT 1 FROM RECETE WHERE RECETE_KODU LIKE 'RCT-SEED-%')
BEGIN
    PRINT 'RECETE tablosu seed ediliyor...';

    DECLARE @i INT = 1;
    DECLARE @hastaKodu NVARCHAR(50);
    DECLARE @basvuruKodu NVARCHAR(50);
    DECLARE @hekimKodu NVARCHAR(50);

    SELECT TOP 1 @hastaKodu = HASTA_KODU FROM HASTA;
    SELECT TOP 1 @basvuruKodu = HASTA_BASVURU_KODU FROM HASTA_BASVURU;
    SELECT TOP 1 @hekimKodu = PERSONEL_KODU FROM PERSONEL;

    WHILE @i <= 30
    BEGIN
        INSERT INTO RECETE (
            RECETE_KODU, HASTA_BASVURU_KODU, HASTA_KODU, RECETE_ZAMANI, RECETE_TURU,
            HEKIM_KODU, DEFTER_NUMARASI, MEDULA_E_RECETE_NUMARASI, RECETE_E_IMZA_DURUMU,
            EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
        )
        VALUES (
            'RCT-SEED-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            @basvuruKodu,
            @hastaKodu,
            DATEADD(DAY, -@i, GETDATE()),
            CASE @i % 3 WHEN 0 THEN 'RCT_TURU_NORMAL' WHEN 1 THEN 'RCT_TURU_KIRMIZI' ELSE 'RCT_TURU_YESIL' END,
            @hekimKodu,
            'RCT-DEF-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            'MED-' + CAST(1000000000 + @i AS NVARCHAR(15)),
            CASE @i % 2 WHEN 0 THEN 'IMZALI' ELSE 'IMZASIZ' END,
            'KLN-ADMIN',
            GETDATE()
        );
        SET @i = @i + 1;
    END;
    PRINT 'RECETE: 30 kayit eklendi.';
END;
GO

-- 3. KAN_BAGISCI (30 kayit)
IF NOT EXISTS (SELECT 1 FROM KAN_BAGISCI WHERE KAN_BAGISCI_KODU LIKE 'KBG-SEED-%')
BEGIN
    PRINT 'KAN_BAGISCI tablosu seed ediliyor...';

    DECLARE @i INT = 1;

    WHILE @i <= 30
    BEGIN
        INSERT INTO KAN_BAGISCI (
            KAN_BAGISCI_KODU, TC_KIMLIK_NUMARASI, AD, SOYADI, DOGUM_TARIHI, CINSIYET,
            KAN_GRUBU, TELEFON_NUMARASI, ADRES, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
        )
        VALUES (
            'KBG-SEED-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            '1' + RIGHT('0000000000' + CAST(10000000000 + @i AS NVARCHAR(11)), 10),
            CASE @i % 5 WHEN 0 THEN 'Ahmet' WHEN 1 THEN 'Mehmet' WHEN 2 THEN 'Ali' WHEN 3 THEN 'Ayşe' ELSE 'Fatma' END,
            CASE @i % 4 WHEN 0 THEN 'Yılmaz' WHEN 1 THEN 'Kaya' WHEN 2 THEN 'Demir' ELSE 'Çelik' END,
            DATEADD(YEAR, -(20 + @i), GETDATE()),
            CASE @i % 2 WHEN 0 THEN 'E' ELSE 'K' END,
            CASE @i % 4 WHEN 0 THEN 'KAN_GRUBU_A_RH_POZ' WHEN 1 THEN 'KAN_GRUBU_B_RH_POZ' WHEN 2 THEN 'KAN_GRUBU_0_RH_POZ' ELSE 'KAN_GRUBU_AB_RH_POZ' END,
            '555' + RIGHT('0000000' + CAST(1000000 + @i AS NVARCHAR(7)), 7),
            'Bağışçı Adresi ' + CAST(@i AS NVARCHAR(5)) + ', Ankara',
            'KLN-ADMIN',
            GETDATE()
        );
        SET @i = @i + 1;
    END;
    PRINT 'KAN_BAGISCI: 30 kayit eklendi.';
END;
GO

-- 4. KAN_TALEP (30 kayit)
IF NOT EXISTS (SELECT 1 FROM KAN_TALEP WHERE KAN_TALEP_KODU LIKE 'KTL-SEED-%')
BEGIN
    PRINT 'KAN_TALEP tablosu seed ediliyor...';

    DECLARE @i INT = 1;
    DECLARE @hastaKodu NVARCHAR(50);
    DECLARE @basvuruKodu NVARCHAR(50);
    DECLARE @birimKodu NVARCHAR(50);
    DECLARE @hekimKodu NVARCHAR(50);

    SELECT TOP 1 @hastaKodu = HASTA_KODU FROM HASTA;
    SELECT TOP 1 @basvuruKodu = HASTA_BASVURU_KODU FROM HASTA_BASVURU;
    SELECT TOP 1 @birimKodu = BIRIM_KODU FROM BIRIM;
    SELECT TOP 1 @hekimKodu = PERSONEL_KODU FROM PERSONEL;

    WHILE @i <= 30
    BEGIN
        INSERT INTO KAN_TALEP (
            KAN_TALEP_KODU, HASTA_KODU, HASTA_BASVURU_KODU, KAN_TALEP_ZAMANI, KAN_TALEP_ACIKLAMA,
            KAN_TALEP_NEDENI, KAN_ISTEYEN_BIRIM_KODU, ISTEYEN_HEKIM_KODU, ISTENEN_KAN_GRUBU,
            PLANLANAN_TRANSFUZYON_ZAMANI, PLANLANAN_TRANSFUZYON_SURESI, KAN_TALEP_ACILIYET_SEVIYESI,
            KAN_ACIL_ACIKLAMA, KAN_TALEP_OZEL_DURUM, HEMATOKRIT_ORANI, TROMBOSIT_SAYISI,
            KAN_ENDIKASYON_TURU, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
        )
        VALUES (
            'KTL-SEED-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            @hastaKodu,
            @basvuruKodu,
            DATEADD(DAY, -@i, GETDATE()),
            'Kan talebi açıklaması ' + CAST(@i AS NVARCHAR(5)),
            'KAN_NEDEN_AMELIYAT',
            @birimKodu,
            @hekimKodu,
            CASE @i % 4 WHEN 0 THEN 'KAN_GRUBU_A_RH_POZ' WHEN 1 THEN 'KAN_GRUBU_B_RH_POZ' WHEN 2 THEN 'KAN_GRUBU_0_RH_POZ' ELSE 'KAN_GRUBU_AB_RH_POZ' END,
            DATEADD(DAY, 1 - @i, GETDATE()),
            '60',
            CASE @i % 2 WHEN 0 THEN 'KAN_TALEP_ACIL' ELSE 'KAN_TALEP_NORMAL' END,
            'Acil durum açıklaması',
            'Özel durum yok',
            CAST(35 + (@i % 10) AS NVARCHAR(5)),
            CAST(150000 + (@i * 1000) AS NVARCHAR(10)),
            'KAN_ENDIK_ANEMI',
            'KLN-ADMIN',
            GETDATE()
        );
        SET @i = @i + 1;
    END;
    PRINT 'KAN_TALEP: 30 kayit eklendi.';
END;
GO

-- 5. RADYOLOJI (30 kayit)
IF NOT EXISTS (SELECT 1 FROM RADYOLOJI WHERE RADYOLOJI_KODU LIKE 'RAD-SEED-%')
BEGIN
    PRINT 'RADYOLOJI tablosu seed ediliyor...';

    DECLARE @i INT = 1;
    DECLARE @hastaKodu NVARCHAR(50);
    DECLARE @basvuruKodu NVARCHAR(50);
    DECLARE @birimKodu NVARCHAR(50);
    DECLARE @cihazKodu NVARCHAR(50);
    DECLARE @kullaniciKodu NVARCHAR(50);
    DECLARE @personelKodu NVARCHAR(50);

    SELECT TOP 1 @hastaKodu = HASTA_KODU FROM HASTA;
    SELECT TOP 1 @basvuruKodu = HASTA_BASVURU_KODU FROM HASTA_BASVURU;
    SELECT TOP 1 @birimKodu = BIRIM_KODU FROM BIRIM;
    SELECT TOP 1 @cihazKodu = CIHAZ_KODU FROM CIHAZ;
    SELECT TOP 1 @kullaniciKodu = KULLANICI_KODU FROM KULLANICI;
    SELECT TOP 1 @personelKodu = PERSONEL_KODU FROM PERSONEL;

    WHILE @i <= 30
    BEGIN
        INSERT INTO RADYOLOJI (
            RADYOLOJI_KODU, HASTA_KODU, HASTA_BASVURU_KODU, BIRIM_KODU, TETKIK_CEKIM_KABUL_ZAMANI,
            BARKOD, BARKOD_ZAMANI, CIHAZ_KODU, CALISMA_BASLAMA_ZAMANI, CALISMA_BITIS_ZAMANI,
            KABUL_EDEN_KULLANICI_KODU, TETKIK_CEKEN_TEKNISYEN_KODU, LOINC_KODU, TETKIK_ISTENME_DURUMU,
            ERISIM_NUMARASI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
        )
        VALUES (
            'RAD-SEED-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            @hastaKodu,
            @basvuruKodu,
            @birimKodu,
            DATEADD(DAY, -@i, DATEADD(HOUR, 9, GETDATE())),
            'BC-RAD-' + RIGHT('00000000' + CAST(@i AS NVARCHAR(8)), 8),
            DATEADD(DAY, -@i, DATEADD(HOUR, 8, GETDATE())),
            @cihazKodu,
            DATEADD(DAY, -@i, DATEADD(HOUR, 9, GETDATE())),
            DATEADD(DAY, -@i, DATEADD(HOUR, 10, GETDATE())),
            @kullaniciKodu,
            @personelKodu,
            'LOINC-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            'TETKIK_TAMAMLANDI',
            'ACC-' + RIGHT('00000000' + CAST(@i AS NVARCHAR(8)), 8),
            'KLN-ADMIN',
            GETDATE()
        );
        SET @i = @i + 1;
    END;
    PRINT 'RADYOLOJI: 30 kayit eklendi.';
END;
GO

-- 6. VEZNE (30 kayit)
IF NOT EXISTS (SELECT 1 FROM VEZNE WHERE VEZNE_KODU LIKE 'VZN-SEED-%')
BEGIN
    PRINT 'VEZNE tablosu seed ediliyor...';

    DECLARE @i INT = 1;
    DECLARE @hastaKodu NVARCHAR(50);
    DECLARE @basvuruKodu NVARCHAR(50);
    DECLARE @birimKodu NVARCHAR(50);
    DECLARE @firmaKodu NVARCHAR(50);

    SELECT TOP 1 @hastaKodu = HASTA_KODU FROM HASTA;
    SELECT TOP 1 @basvuruKodu = HASTA_BASVURU_KODU FROM HASTA_BASVURU;
    SELECT TOP 1 @birimKodu = BIRIM_KODU FROM BIRIM;
    SELECT TOP 1 @firmaKodu = FIRMA_KODU FROM FIRMA;

    WHILE @i <= 30
    BEGIN
        INSERT INTO VEZNE (
            VEZNE_KODU, HASTA_KODU, HASTA_BASVURU_KODU, MAKBUZ_NUMARASI, VEZNE_OZEL_NUMARASI,
            VEZNE_GIRIS_CIKIS_BILGISI, MAKBUZ_ZAMANI, VEZNE_BIRIM_KODU, MAKBUZ_SERI_NUMARASI,
            TAHSIL_TURU, MAKBUZ_TUTARI, ACIKLAMA, MAKBUZ_SAHIBI_ADRESI, FIRMA_ADI, FIRMA_KODU,
            EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
        )
        VALUES (
            'VZN-SEED-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            @hastaKodu,
            @basvuruKodu,
            'MKB-' + CAST(2024000000 + @i AS NVARCHAR(15)),
            'VON-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            CASE @i % 2 WHEN 0 THEN 'GIRIS' ELSE 'CIKIS' END,
            DATEADD(DAY, -@i, GETDATE()),
            @birimKodu,
            'SER-' + RIGHT('000' + CAST(@i AS NVARCHAR(3)), 3),
            CASE @i % 2 WHEN 0 THEN 'TAHSIL_NAKIT' ELSE 'TAHSIL_KREDI' END,
            CAST(100 + (@i * 50) AS NVARCHAR(10)),
            'Vezne işlemi açıklaması ' + CAST(@i AS NVARCHAR(5)),
            'Makbuz sahibi adresi ' + CAST(@i AS NVARCHAR(5)),
            'Test Firma ' + CAST(@i AS NVARCHAR(5)),
            @firmaKodu,
            'KLN-ADMIN',
            GETDATE()
        );
        SET @i = @i + 1;
    END;
    PRINT 'VEZNE: 30 kayit eklendi.';
END;
GO

-- 7. STOK_ISTEK (30 kayit)
IF NOT EXISTS (SELECT 1 FROM STOK_ISTEK WHERE STOK_ISTEK_KODU LIKE 'SI-SEED-%')
BEGIN
    PRINT 'STOK_ISTEK tablosu seed ediliyor...';

    DECLARE @i INT = 1;
    DECLARE @hastaKodu NVARCHAR(50);
    DECLARE @basvuruKodu NVARCHAR(50);
    DECLARE @depoKodu NVARCHAR(50);
    DECLARE @personelKodu NVARCHAR(50);

    SELECT TOP 1 @hastaKodu = HASTA_KODU FROM HASTA;
    SELECT TOP 1 @basvuruKodu = HASTA_BASVURU_KODU FROM HASTA_BASVURU;
    SELECT TOP 1 @depoKodu = DEPO_KODU FROM DEPO;
    SELECT TOP 1 @personelKodu = PERSONEL_KODU FROM PERSONEL;

    WHILE @i <= 30
    BEGIN
        INSERT INTO STOK_ISTEK (
            STOK_ISTEK_KODU, HASTA_KODU, HASTA_BASVURU_KODU, DEPO_KODU, ISTEYEN_PERSONEL_KODU,
            STOK_ISTEK_DURUMU, STOK_ISTEK_HEKIM_ACIKLAMA, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
        )
        VALUES (
            'SI-SEED-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            @hastaKodu,
            @basvuruKodu,
            @depoKodu,
            @personelKodu,
            CASE @i % 2 WHEN 0 THEN 'STOK_ISTEK_BEKLEMEDE' ELSE 'STOK_ISTEK_ONAYLANDI' END,
            'Stok istek açıklaması ' + CAST(@i AS NVARCHAR(5)),
            'KLN-ADMIN',
            GETDATE()
        );
        SET @i = @i + 1;
    END;
    PRINT 'STOK_ISTEK: 30 kayit eklendi.';
END;
GO

-- 8. STOK_FIS (30 kayit)
IF NOT EXISTS (SELECT 1 FROM STOK_FIS WHERE STOK_FIS_KODU LIKE 'SF-SEED-%')
BEGIN
    PRINT 'STOK_FIS tablosu seed ediliyor...';

    DECLARE @i INT = 1;
    DECLARE @hastaKodu NVARCHAR(50);
    DECLARE @basvuruKodu NVARCHAR(50);
    DECLARE @depoKodu NVARCHAR(50);
    DECLARE @personelKodu NVARCHAR(50);
    DECLARE @firmaKodu NVARCHAR(50);

    SELECT TOP 1 @hastaKodu = HASTA_KODU FROM HASTA;
    SELECT TOP 1 @basvuruKodu = HASTA_BASVURU_KODU FROM HASTA_BASVURU;
    SELECT TOP 1 @depoKodu = DEPO_KODU FROM DEPO;
    SELECT TOP 1 @personelKodu = PERSONEL_KODU FROM PERSONEL;
    SELECT TOP 1 @firmaKodu = FIRMA_KODU FROM FIRMA;

    WHILE @i <= 30
    BEGIN
        INSERT INTO STOK_FIS (
            STOK_FIS_KODU, HASTA_KODU, HASTA_BASVURU_KODU, BAGLI_STOK_FIS_KODU, DEPO_KODU,
            HAREKET_TURU, MKYS_AYNIYAT_MAKBUZ_KODU, HAREKET_TARIHI, SHCEK_PAYI, HAZINE_PAYI,
            SAGLIK_BAKANLIGI_PAYI, BEDELSIZ_FIS, FIS_TUTARI, HAREKET_SEKLI, ISLEMI_YAPAN_PERSONEL_KODU,
            ISLEM_ZAMANI, FIRMA_KODU, IHALE_NUMARASI, IHALE_TARIHI, IHALE_TURU, MUAYENE_KABUL_NUMARASI,
            MUAYENE_TARIHI, TESLIM_EDEN_KISI, TESLIM_EDEN_KISI_UNVANI, BUTCE_TURU, FATURA_NUMARASI,
            FATURA_ZAMANI, IRSALIYE_NUMARASI, IRSALIYE_TARIHI, MKYS_KURUM_KODU,
            EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI
        )
        VALUES (
            'SF-SEED-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            @hastaKodu,
            @basvuruKodu,
            'SF-SEED-' + RIGHT('00000' + CAST((@i % 10) + 1 AS NVARCHAR(5)), 5),
            @depoKodu,
            CASE @i % 2 WHEN 0 THEN 'GIRIS' ELSE 'CIKIS' END,
            'MKYS-' + RIGHT('00000000' + CAST(@i AS NVARCHAR(8)), 8),
            DATEADD(DAY, -@i, GETDATE()),
            '5',
            '3',
            '2',
            CASE @i % 3 WHEN 0 THEN 'EVET' ELSE 'HAYIR' END,
            CAST(1000 + (@i * 100) AS NVARCHAR(10)),
            CASE @i % 2 WHEN 0 THEN 'HAREKET_GIRIS' ELSE 'HAREKET_CIKIS' END,
            @personelKodu,
            DATEADD(DAY, -@i, GETDATE()),
            @firmaKodu,
            'IHL-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            DATEADD(DAY, -@i - 30, GETDATE()),
            'IHALE_ACIK',
            'MKK-' + RIGHT('00000' + CAST(@i AS NVARCHAR(5)), 5),
            DATEADD(DAY, -@i - 15, GETDATE()),
            'Teslim Eden ' + CAST(@i AS NVARCHAR(5)),
            'Memur',
            'BUTCE_DONER',
            'FAT-' + RIGHT('00000000' + CAST(@i AS NVARCHAR(8)), 8),
            DATEADD(DAY, -@i - 5, GETDATE()),
            'IRS-' + RIGHT('00000000' + CAST(@i AS NVARCHAR(8)), 8),
            DATEADD(DAY, -@i - 7, GETDATE()),
            'MKYS-KRM-001',
            'KLN-ADMIN',
            GETDATE()
        );
        SET @i = @i + 1;
    END;
    PRINT 'STOK_FIS: 30 kayit eklendi.';
END;
GO

PRINT 'Level 1 tablolar tamamlandi.';
GO
