namespace Server.Application.Vem.PersonelBordro;

public class PersonelBordroDto
{
    public string? PERSONEL_BORDRO_KODU { get; set; }
    public string? REFERANS_TABLO_ADI { get; set; }
    public string? YIL { get; set; }
    public string? AY { get; set; }
    public string? PERSONEL_KODU { get; set; }
    public string? BORDRO_TURU { get; set; }
    public string? BORDRO_NUMARASI { get; set; }
    public string? MAAS_DERECESI { get; set; }
    public string? MAAS_KADEMESI { get; set; }
    public string? MAAS_GOSTERGESI { get; set; }
    public string? MAAS_EK_GOSTERGESI { get; set; }
    public string? EMEKLI_DERECESI { get; set; }
    public string? EMEKLI_KADEMESI { get; set; }
    public string? EMEKLI_GOSTERGESI { get; set; }
    public string? EMEKLI_EK_GOSTERGESI { get; set; }
    public string? TABAN_AYLIK_TUTARI { get; set; }
    public string? AYLIK_TUTARI { get; set; }
    public string? KIDEM_TUTARI { get; set; }
    public string? EK_GOSTERGE_TUTARI { get; set; }
    public string? YAN_ODEME_TUTARI { get; set; }
    public string? OZEL_HIZMET_TUTARI { get; set; }
    public string? AILE_YARDIMI_TUTARI { get; set; }
    public string? COCUK_YARDIMI_TUTARI { get; set; }
    public string? COCUK_SAYISI_6_YAS_ALTI { get; set; }
    public string? COCUK_SAYISI_6_YAS_USTU { get; set; }
    public string? AGI_ESAS_COCUK_SAYISI { get; set; }
    public string? ES_CALISMA_DURUMU { get; set; }
    public string? BES_FIRMA_KODU { get; set; }
    public string? BES_ORANI { get; set; }
    public string? BES_KESINTI_TUTARI { get; set; }
    public string? YABANCI_DIL_TAZMINATI_TUTARI { get; set; }
    public string? YABANCI_DIL_BILGISI { get; set; }
    public string? YABANCI_DIL_PUANI { get; set; }
    public string? SENDIKA_ODENEGI_TUTARI { get; set; }
    public string? SENDIKA_BILGISI { get; set; }
    public string? SENDIKA_SIRA_NUMARASI { get; set; }
    public string? SENDIKA_KESINTI_ORANI { get; set; }
    public string? SENDIKA_AIDATI_TUTARI { get; set; }
    public string? DEVLET_EMEKLI_KESENEGI { get; set; }
    public string? SAHIS_EMEKLI_KESENEGI { get; set; }
    public string? EMEKLI_KESENEGI_MATRAHI_TUTARI { get; set; }
    public string? OZEL_SIGORTA_TUTARI { get; set; }
    public string? VERGI_INDIRIMI_TUTARI { get; set; }
    public string? DAMGA_VERGISI_TUTARI { get; set; }
    public string? GELIR_VERGISI_TUTARI { get; set; }
    public string? GELIR_VERGISI_MATRAHI_TUTARI { get; set; }
    public string? KUMULATIF_GELIR_VERGISI_TUTARI { get; set; }
    public string? ICRA_TUTARI { get; set; }
    public string? NAFAKA_TUTARI { get; set; }
    public string? YUZDE_YUZ_TUTARI { get; set; }
    public string? DOGU_TAZMINATI_TUTARI { get; set; }
    public string? SGK_SAHIS_TUTARI { get; set; }
    public string? SGK_ISVEREN_TUTARI { get; set; }
    public string? SGK_MATRAHI_TUTARI { get; set; }
    public string? KEFALET_TUTARI { get; set; }
    public string? SOZLESME_UCRETI_TUTARI { get; set; }
    public string? LOJMAN_KESINTISI_TUTARI { get; set; }
    public string? ASGARI_GECIM_INDIRIMI_TUTARI { get; set; }
    public string? ISSIZLIK_SAHIS_TUTARI { get; set; }
    public string? ISSIZLIK_ISVEREN_TUTARI { get; set; }
    public string? ISSIZLIK_PRIMI_MATRAHI_TUTARI { get; set; }
    public string? MALULLUK_DEVLET_TUTARI { get; set; }
    public string? MALULLUK_SAHIS_TUTARI { get; set; }
    public string? GIYECEK_YARDIMI_TUTARI { get; set; }
    public string? FARK_TAZMINATI_TUTARI { get; set; }
    public string? HIZMET_ZAMMI_TUTARI { get; set; }
    public string? VASITA_YARDIMI_TUTARI { get; set; }
    public string? KIRA_YARDIMI_TUTARI { get; set; }
    public string? YEMEK_YARDIMI_TUTARI { get; set; }
    public string? FAZLA_MESAI_TUTARI { get; set; }
    public string? NOBET_BIRIM_UCRET_TUTARI { get; set; }
    public string? NOBET_BIRIM_UCRET_20_TUTARI { get; set; }
    public string? NOBET_BIRIM_UCRET_50_TUTARI { get; set; }
    public string? NOBET_SAATI { get; set; }
    public string? NOBET_20_SAATI { get; set; }
    public string? NOBET_50_SAATI { get; set; }
    public string? YEVMIYE_TUTARI { get; set; }
    public string? CALISMA_SAATI { get; set; }
    public string? TAHAKKUK_TOPLAMI { get; set; }
    public string? NET_TUTAR { get; set; }
    public string? KESINTI_TOPLAMI { get; set; }
}

