-- =============================================================================
-- LBYS SQL Views Creation Script
-- Generated for all 141 LBYS tables
-- Schema: [dbo] (referencing [Lbys] tables)
-- Naming Convention: VEM_TABLENAME
-- =============================================================================

-- AMELIYAT
CREATE OR ALTER VIEW [dbo].[VEM_AMELIYAT] AS
SELECT * FROM [Lbys].[AMELIYAT];
GO

-- AMELIYAT_EKIP
CREATE OR ALTER VIEW [dbo].[VEM_AMELIYAT_EKIP] AS
SELECT * FROM [Lbys].[AMELIYAT_EKIP];
GO

-- AMELIYAT_ISLEM
CREATE OR ALTER VIEW [dbo].[VEM_AMELIYAT_ISLEM] AS
SELECT * FROM [Lbys].[AMELIYAT_ISLEM];
GO

-- ANLIK_YATAN_HASTA
CREATE OR ALTER VIEW [dbo].[VEM_ANLIK_YATAN_HASTA] AS
SELECT * FROM [Lbys].[ANLIK_YATAN_HASTA];
GO

-- ANTIBIYOTIK_SONUC
CREATE OR ALTER VIEW [dbo].[VEM_ANTIBIYOTIK_SONUC] AS
SELECT * FROM [Lbys].[ANTIBIYOTIK_SONUC];
GO

-- ASI_BILGISI
CREATE OR ALTER VIEW [dbo].[VEM_ASI_BILGISI] AS
SELECT * FROM [Lbys].[ASI_BILGISI];
GO

-- BAKTERI_SONUC
CREATE OR ALTER VIEW [dbo].[VEM_BAKTERI_SONUC] AS
SELECT * FROM [Lbys].[BAKTERI_SONUC];
GO

-- BASVURU_TANI
CREATE OR ALTER VIEW [dbo].[VEM_BASVURU_TANI] AS
SELECT * FROM [Lbys].[BASVURU_TANI];
GO

-- BASVURU_YEMEK
CREATE OR ALTER VIEW [dbo].[VEM_BASVURU_YEMEK] AS
SELECT * FROM [Lbys].[BASVURU_YEMEK];
GO

-- BEBEK_COCUK_IZLEM
CREATE OR ALTER VIEW [dbo].[VEM_BEBEK_COCUK_IZLEM] AS
SELECT * FROM [Lbys].[BEBEK_COCUK_IZLEM];
GO

-- BILDIRIMI_ZORUNLU
CREATE OR ALTER VIEW [dbo].[VEM_BILDIRIMI_ZORUNLU] AS
SELECT * FROM [Lbys].[BILDIRIMI_ZORUNLU];
GO

-- BINA
CREATE OR ALTER VIEW [dbo].[VEM_BINA] AS
SELECT * FROM [Lbys].[BINA];
GO

-- BIRIM
CREATE OR ALTER VIEW [dbo].[VEM_BIRIM] AS
SELECT * FROM [Lbys].[BIRIM];
GO

-- CIHAZ
CREATE OR ALTER VIEW [dbo].[VEM_CIHAZ] AS
SELECT * FROM [Lbys].[CIHAZ];
GO

-- COCUK_DIYABET
CREATE OR ALTER VIEW [dbo].[VEM_COCUK_DIYABET] AS
SELECT * FROM [Lbys].[COCUK_DIYABET];
GO

-- DEPO
CREATE OR ALTER VIEW [dbo].[VEM_DEPO] AS
SELECT * FROM [Lbys].[DEPO];
GO

-- DIS_TAAHHUT
CREATE OR ALTER VIEW [dbo].[VEM_DIS_TAAHHUT] AS
SELECT * FROM [Lbys].[DIS_TAAHHUT];
GO

-- DIS_TAAHHUT_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_DIS_TAAHHUT_DETAY] AS
SELECT * FROM [Lbys].[DIS_TAAHHUT_DETAY];
GO

-- DISPROTEZ
CREATE OR ALTER VIEW [dbo].[VEM_DISPROTEZ] AS
SELECT * FROM [Lbys].[DISPROTEZ];
GO

-- DISPROTEZ_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_DISPROTEZ_DETAY] AS
SELECT * FROM [Lbys].[DISPROTEZ_DETAY];
GO

-- DIYABET
CREATE OR ALTER VIEW [dbo].[VEM_DIYABET] AS
SELECT * FROM [Lbys].[DIYABET];
GO

-- DOGUM
CREATE OR ALTER VIEW [dbo].[VEM_DOGUM] AS
SELECT * FROM [Lbys].[DOGUM];
GO

-- DOGUM_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_DOGUM_DETAY] AS
SELECT * FROM [Lbys].[DOGUM_DETAY];
GO

-- DOKTOR_MESAJI
CREATE OR ALTER VIEW [dbo].[VEM_DOKTOR_MESAJI] AS
SELECT * FROM [Lbys].[DOKTOR_MESAJI];
GO

-- EK_ODEME
CREATE OR ALTER VIEW [dbo].[VEM_EK_ODEME] AS
SELECT * FROM [Lbys].[EK_ODEME];
GO

-- EK_ODEME_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_EK_ODEME_DETAY] AS
SELECT * FROM [Lbys].[EK_ODEME_DETAY];
GO

-- EK_ODEME_DONEM
CREATE OR ALTER VIEW [dbo].[VEM_EK_ODEME_DONEM] AS
SELECT * FROM [Lbys].[EK_ODEME_DONEM];
GO

-- EVDE_SAGLIK_IZLEM
CREATE OR ALTER VIEW [dbo].[VEM_EVDE_SAGLIK_IZLEM] AS
SELECT * FROM [Lbys].[EVDE_SAGLIK_IZLEM];
GO

-- FATURA
CREATE OR ALTER VIEW [dbo].[VEM_FATURA] AS
SELECT * FROM [Lbys].[FATURA];
GO

-- FIRMA
CREATE OR ALTER VIEW [dbo].[VEM_FIRMA] AS
SELECT * FROM [Lbys].[FIRMA];
GO

-- GEBE_IZLEM
CREATE OR ALTER VIEW [dbo].[VEM_GEBE_IZLEM] AS
SELECT * FROM [Lbys].[GEBE_IZLEM];
GO

-- GETAT
CREATE OR ALTER VIEW [dbo].[VEM_GETAT] AS
SELECT * FROM [Lbys].[GETAT];
GO

-- GRUP_UYELIK
CREATE OR ALTER VIEW [dbo].[VEM_GRUP_UYELIK] AS
SELECT * FROM [Lbys].[GRUP_UYELIK];
GO

-- HASTA
CREATE OR ALTER VIEW [dbo].[VEM_HASTA] AS
SELECT * FROM [Lbys].[HASTA];
GO

-- HASTA_ADLI_RAPOR
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_ADLI_RAPOR] AS
SELECT * FROM [Lbys].[HASTA_ADLI_RAPOR];
GO

-- HASTA_ARSIV
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_ARSIV] AS
SELECT * FROM [Lbys].[HASTA_ARSIV];
GO

-- HASTA_ARSIV_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_ARSIV_DETAY] AS
SELECT * FROM [Lbys].[HASTA_ARSIV_DETAY];
GO

-- HASTA_BASVURU
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_BASVURU] AS
SELECT * FROM [Lbys].[HASTA_BASVURU];
GO

-- HASTA_BORC
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_BORC] AS
SELECT * FROM [Lbys].[HASTA_BORC];
GO

-- HASTA_DIS
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_DIS] AS
SELECT * FROM [Lbys].[HASTA_DIS];
GO

-- HASTA_EPIKRIZ
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_EPIKRIZ] AS
SELECT * FROM [Lbys].[HASTA_EPIKRIZ];
GO

-- HASTA_FOTOGRAF
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_FOTOGRAF] AS
SELECT * FROM [Lbys].[HASTA_FOTOGRAF];
GO

-- HASTA_GIZLILIK
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_GIZLILIK] AS
SELECT * FROM [Lbys].[HASTA_GIZLILIK];
GO

-- HASTA_HIZMET
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_HIZMET] AS
SELECT * FROM [Lbys].[HASTA_HIZMET];
GO

-- HASTA_ILETISIM
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_ILETISIM] AS
SELECT * FROM [Lbys].[HASTA_ILETISIM];
GO

-- HASTA_MALZEME
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_MALZEME] AS
SELECT * FROM [Lbys].[HASTA_MALZEME];
GO

-- HASTA_NOTLARI
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_NOTLARI] AS
SELECT * FROM [Lbys].[HASTA_NOTLARI];
GO

-- HASTA_OLUM
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_OLUM] AS
SELECT * FROM [Lbys].[HASTA_OLUM];
GO

-- HASTA_SEANS
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_SEANS] AS
SELECT * FROM [Lbys].[HASTA_SEANS];
GO

-- HASTA_SEVK
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_SEVK] AS
SELECT * FROM [Lbys].[HASTA_SEVK];
GO

-- HASTA_TIBBI_BILGI
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_TIBBI_BILGI] AS
SELECT * FROM [Lbys].[HASTA_TIBBI_BILGI];
GO

-- HASTA_UYARI
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_UYARI] AS
SELECT * FROM [Lbys].[HASTA_UYARI];
GO

-- HASTA_VENTILATOR
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_VENTILATOR] AS
SELECT * FROM [Lbys].[HASTA_VENTILATOR];
GO

-- HASTA_VITAL_FIZIKI_BULGU
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_VITAL_FIZIKI_BULGU] AS
SELECT * FROM [Lbys].[HASTA_VITAL_FIZIKI_BULGU];
GO

-- HASTA_YATAK
CREATE OR ALTER VIEW [dbo].[VEM_HASTA_YATAK] AS
SELECT * FROM [Lbys].[HASTA_YATAK];
GO

-- HEMOGLOBINOPATI
CREATE OR ALTER VIEW [dbo].[VEM_HEMOGLOBINOPATI] AS
SELECT * FROM [Lbys].[HEMOGLOBINOPATI];
GO

-- HEMSIRE_BAKIM
CREATE OR ALTER VIEW [dbo].[VEM_HEMSIRE_BAKIM] AS
SELECT * FROM [Lbys].[HEMSIRE_BAKIM];
GO

-- HIZMET
CREATE OR ALTER VIEW [dbo].[VEM_HIZMET] AS
SELECT * FROM [Lbys].[HIZMET];
GO

-- ICMAL
CREATE OR ALTER VIEW [dbo].[VEM_ICMAL] AS
SELECT * FROM [Lbys].[ICMAL];
GO

-- ILAC_UYUM
CREATE OR ALTER VIEW [dbo].[VEM_ILAC_UYUM] AS
SELECT * FROM [Lbys].[ILAC_UYUM];
GO

-- INTIHAR_IZLEM
CREATE OR ALTER VIEW [dbo].[VEM_INTIHAR_IZLEM] AS
SELECT * FROM [Lbys].[INTIHAR_IZLEM];
GO

-- KADIN_IZLEM
CREATE OR ALTER VIEW [dbo].[VEM_KADIN_IZLEM] AS
SELECT * FROM [Lbys].[KADIN_IZLEM];
GO

-- KAN_BAGISCI
CREATE OR ALTER VIEW [dbo].[VEM_KAN_BAGISCI] AS
SELECT * FROM [Lbys].[KAN_BAGISCI];
GO

-- KAN_CIKIS
CREATE OR ALTER VIEW [dbo].[VEM_KAN_CIKIS] AS
SELECT * FROM [Lbys].[KAN_CIKIS];
GO

-- KAN_STOK
CREATE OR ALTER VIEW [dbo].[VEM_KAN_STOK] AS
SELECT * FROM [Lbys].[KAN_STOK];
GO

-- KAN_TALEP
CREATE OR ALTER VIEW [dbo].[VEM_KAN_TALEP] AS
SELECT * FROM [Lbys].[KAN_TALEP];
GO

-- KAN_TALEP_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_KAN_TALEP_DETAY] AS
SELECT * FROM [Lbys].[KAN_TALEP_DETAY];
GO

-- KAN_URUN
CREATE OR ALTER VIEW [dbo].[VEM_KAN_URUN] AS
SELECT * FROM [Lbys].[KAN_URUN];
GO

-- KAN_URUN_IMHA
CREATE OR ALTER VIEW [dbo].[VEM_KAN_URUN_IMHA] AS
SELECT * FROM [Lbys].[KAN_URUN_IMHA];
GO

-- KLINIK_SEYIR
CREATE OR ALTER VIEW [dbo].[VEM_KLINIK_SEYIR] AS
SELECT * FROM [Lbys].[KLINIK_SEYIR];
GO

-- KONSULTASYON
CREATE OR ALTER VIEW [dbo].[VEM_KONSULTASYON] AS
SELECT * FROM [Lbys].[KONSULTASYON];
GO

-- KUDUZ_IZLEM
CREATE OR ALTER VIEW [dbo].[VEM_KUDUZ_IZLEM] AS
SELECT * FROM [Lbys].[KUDUZ_IZLEM];
GO

-- KULLANICI
CREATE OR ALTER VIEW [dbo].[VEM_KULLANICI] AS
SELECT * FROM [Lbys].[KULLANICI];
GO

-- KULLANICI_GRUP
CREATE OR ALTER VIEW [dbo].[VEM_KULLANICI_GRUP] AS
SELECT * FROM [Lbys].[KULLANICI_GRUP];
GO

-- KURUL
CREATE OR ALTER VIEW [dbo].[VEM_KURUL] AS
SELECT * FROM [Lbys].[KURUL];
GO

-- KURUL_ASKERI
CREATE OR ALTER VIEW [dbo].[VEM_KURUL_ASKERI] AS
SELECT * FROM [Lbys].[KURUL_ASKERI];
GO

-- KURUL_ENGELLI
CREATE OR ALTER VIEW [dbo].[VEM_KURUL_ENGELLI] AS
SELECT * FROM [Lbys].[KURUL_ENGELLI];
GO

-- KURUL_ETKEN_MADDE
CREATE OR ALTER VIEW [dbo].[VEM_KURUL_ETKEN_MADDE] AS
SELECT * FROM [Lbys].[KURUL_ETKEN_MADDE];
GO

-- KURUL_HEKIM
CREATE OR ALTER VIEW [dbo].[VEM_KURUL_HEKIM] AS
SELECT * FROM [Lbys].[KURUL_HEKIM];
GO

-- KURUL_RAPOR
CREATE OR ALTER VIEW [dbo].[VEM_KURUL_RAPOR] AS
SELECT * FROM [Lbys].[KURUL_RAPOR];
GO

-- KURUL_TESHIS
CREATE OR ALTER VIEW [dbo].[VEM_KURUL_TESHIS] AS
SELECT * FROM [Lbys].[KURUL_TESHIS];
GO

-- KURUM
CREATE OR ALTER VIEW [dbo].[VEM_KURUM] AS
SELECT * FROM [Lbys].[KURUM];
GO

-- LOHUSA_IZLEM
CREATE OR ALTER VIEW [dbo].[VEM_LOHUSA_IZLEM] AS
SELECT * FROM [Lbys].[LOHUSA_IZLEM];
GO

-- MADDE_BAGIMLILIGI
CREATE OR ALTER VIEW [dbo].[VEM_MADDE_BAGIMLILIGI] AS
SELECT * FROM [Lbys].[MADDE_BAGIMLILIGI];
GO

-- MEDULA_TAKIP
CREATE OR ALTER VIEW [dbo].[VEM_MEDULA_TAKIP] AS
SELECT * FROM [Lbys].[MEDULA_TAKIP];
GO

-- NOBETCI_PERSONEL_BILGISI
CREATE OR ALTER VIEW [dbo].[VEM_NOBETCI_PERSONEL_BILGISI] AS
SELECT * FROM [Lbys].[NOBETCI_PERSONEL_BILGISI];
GO

-- OBEZITE_IZLEM
CREATE OR ALTER VIEW [dbo].[VEM_OBEZITE_IZLEM] AS
SELECT * FROM [Lbys].[OBEZITE_IZLEM];
GO

-- ODA
CREATE OR ALTER VIEW [dbo].[VEM_ODA] AS
SELECT * FROM [Lbys].[ODA];
GO

-- OPTIK_RECETE
CREATE OR ALTER VIEW [dbo].[VEM_OPTIK_RECETE] AS
SELECT * FROM [Lbys].[OPTIK_RECETE];
GO

-- ORTODONTI_ICON_SKOR
CREATE OR ALTER VIEW [dbo].[VEM_ORTODONTI_ICON_SKOR] AS
SELECT * FROM [Lbys].[ORTODONTI_ICON_SKOR];
GO

-- PATOLOJI
CREATE OR ALTER VIEW [dbo].[VEM_PATOLOJI] AS
SELECT * FROM [Lbys].[PATOLOJI];
GO

-- PERSONEL
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL] AS
SELECT * FROM [Lbys].[PERSONEL];
GO

-- PERSONEL_BAKMAKLA_YUKUMLU
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_BAKMAKLA_YUKUMLU] AS
SELECT * FROM [Lbys].[PERSONEL_BAKMAKLA_YUKUMLU];
GO

-- PERSONEL_BANKA
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_BANKA] AS
SELECT * FROM [Lbys].[PERSONEL_BANKA];
GO

-- PERSONEL_BORDRO
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_BORDRO] AS
SELECT * FROM [Lbys].[PERSONEL_BORDRO];
GO

-- PERSONEL_BORDRO_SONDURUM
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_BORDRO_SONDURUM] AS
SELECT * FROM [Lbys].[PERSONEL_BORDRO_SONDURUM];
GO

-- PERSONEL_EGITIM
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_EGITIM] AS
SELECT * FROM [Lbys].[PERSONEL_EGITIM];
GO

-- PERSONEL_GOREVLENDIRME
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_GOREVLENDIRME] AS
SELECT * FROM [Lbys].[PERSONEL_GOREVLENDIRME];
GO

-- PERSONEL_IZIN
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_IZIN] AS
SELECT * FROM [Lbys].[PERSONEL_IZIN];
GO

-- PERSONEL_IZIN_DURUMU
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_IZIN_DURUMU] AS
SELECT * FROM [Lbys].[PERSONEL_IZIN_DURUMU];
GO

-- PERSONEL_ODUL_CEZA
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_ODUL_CEZA] AS
SELECT * FROM [Lbys].[PERSONEL_ODUL_CEZA];
GO

-- PERSONEL_OGRENIM
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_OGRENIM] AS
SELECT * FROM [Lbys].[PERSONEL_OGRENIM];
GO

-- PERSONEL_YANDAL
CREATE OR ALTER VIEW [dbo].[VEM_PERSONEL_YANDAL] AS
SELECT * FROM [Lbys].[PERSONEL_YANDAL];
GO

-- RADYOLOJI
CREATE OR ALTER VIEW [dbo].[VEM_RADYOLOJI] AS
SELECT * FROM [Lbys].[RADYOLOJI];
GO

-- RADYOLOJI_SONUC
CREATE OR ALTER VIEW [dbo].[VEM_RADYOLOJI_SONUC] AS
SELECT * FROM [Lbys].[RADYOLOJI_SONUC];
GO

-- RANDEVU
CREATE OR ALTER VIEW [dbo].[VEM_RANDEVU] AS
SELECT * FROM [Lbys].[RANDEVU];
GO

-- RECETE
CREATE OR ALTER VIEW [dbo].[VEM_RECETE] AS
SELECT * FROM [Lbys].[RECETE];
GO

-- RECETE_ILAC
CREATE OR ALTER VIEW [dbo].[VEM_RECETE_ILAC] AS
SELECT * FROM [Lbys].[RECETE_ILAC];
GO

-- RECETE_ILAC_ACIKLAMA
CREATE OR ALTER VIEW [dbo].[VEM_RECETE_ILAC_ACIKLAMA] AS
SELECT * FROM [Lbys].[RECETE_ILAC_ACIKLAMA];
GO

-- REFERANS_KODLAR
CREATE OR ALTER VIEW [dbo].[VEM_REFERANS_KODLAR] AS
SELECT * FROM [Lbys].[REFERANS_KODLAR];
GO

-- RISK_SKORLAMA
CREATE OR ALTER VIEW [dbo].[VEM_RISK_SKORLAMA] AS
SELECT * FROM [Lbys].[RISK_SKORLAMA];
GO

-- RISK_SKORLAMA_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_RISK_SKORLAMA_DETAY] AS
SELECT * FROM [Lbys].[RISK_SKORLAMA_DETAY];
GO

-- SILINEN_KAYITLAR
CREATE OR ALTER VIEW [dbo].[VEM_SILINEN_KAYITLAR] AS
SELECT * FROM [Lbys].[SILINEN_KAYITLAR];
GO

-- STERILIZASYON_CIKIS
CREATE OR ALTER VIEW [dbo].[VEM_STERILIZASYON_CIKIS] AS
SELECT * FROM [Lbys].[STERILIZASYON_CIKIS];
GO

-- STERILIZASYON_GIRIS
CREATE OR ALTER VIEW [dbo].[VEM_STERILIZASYON_GIRIS] AS
SELECT * FROM [Lbys].[STERILIZASYON_GIRIS];
GO

-- STERILIZASYON_PAKET
CREATE OR ALTER VIEW [dbo].[VEM_STERILIZASYON_PAKET] AS
SELECT * FROM [Lbys].[STERILIZASYON_PAKET];
GO

-- STERILIZASYON_PAKET_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_STERILIZASYON_PAKET_DETAY] AS
SELECT * FROM [Lbys].[STERILIZASYON_PAKET_DETAY];
GO

-- STERILIZASYON_SET
CREATE OR ALTER VIEW [dbo].[VEM_STERILIZASYON_SET] AS
SELECT * FROM [Lbys].[STERILIZASYON_SET];
GO

-- STERILIZASYON_SET_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_STERILIZASYON_SET_DETAY] AS
SELECT * FROM [Lbys].[STERILIZASYON_SET_DETAY];
GO

-- STERILIZASYON_STOK_DURUM
CREATE OR ALTER VIEW [dbo].[VEM_STERILIZASYON_STOK_DURUM] AS
SELECT * FROM [Lbys].[STERILIZASYON_STOK_DURUM];
GO

-- STERILIZASYON_YIKAMA
CREATE OR ALTER VIEW [dbo].[VEM_STERILIZASYON_YIKAMA] AS
SELECT * FROM [Lbys].[STERILIZASYON_YIKAMA];
GO

-- STOK_DURUM
CREATE OR ALTER VIEW [dbo].[VEM_STOK_DURUM] AS
SELECT * FROM [Lbys].[STOK_DURUM];
GO

-- STOK_EHU_TAKIP
CREATE OR ALTER VIEW [dbo].[VEM_STOK_EHU_TAKIP] AS
SELECT * FROM [Lbys].[STOK_EHU_TAKIP];
GO

-- STOK_FIS
CREATE OR ALTER VIEW [dbo].[VEM_STOK_FIS] AS
SELECT * FROM [Lbys].[STOK_FIS];
GO

-- STOK_HAREKET
CREATE OR ALTER VIEW [dbo].[VEM_STOK_HAREKET] AS
SELECT * FROM [Lbys].[STOK_HAREKET];
GO

-- STOK_ISTEK
CREATE OR ALTER VIEW [dbo].[VEM_STOK_ISTEK] AS
SELECT * FROM [Lbys].[STOK_ISTEK];
GO

-- STOK_ISTEK_HAREKET
CREATE OR ALTER VIEW [dbo].[VEM_STOK_ISTEK_HAREKET] AS
SELECT * FROM [Lbys].[STOK_ISTEK_HAREKET];
GO

-- STOK_ISTEK_UYGULAMA
CREATE OR ALTER VIEW [dbo].[VEM_STOK_ISTEK_UYGULAMA] AS
SELECT * FROM [Lbys].[STOK_ISTEK_UYGULAMA];
GO

-- STOK_KART
CREATE OR ALTER VIEW [dbo].[VEM_STOK_KART] AS
SELECT * FROM [Lbys].[STOK_KART];
GO

-- SYS_PAKET
CREATE OR ALTER VIEW [dbo].[VEM_SYS_PAKET] AS
SELECT * FROM [Lbys].[SYS_PAKET];
GO

-- TETKIK
CREATE OR ALTER VIEW [dbo].[VEM_TETKIK] AS
SELECT * FROM [Lbys].[TETKIK];
GO

-- TETKIK_CIHAZ_ESLESME
CREATE OR ALTER VIEW [dbo].[VEM_TETKIK_CIHAZ_ESLESME] AS
SELECT * FROM [Lbys].[TETKIK_CIHAZ_ESLESME];
GO

-- TETKIK_NUMUNE
CREATE OR ALTER VIEW [dbo].[VEM_TETKIK_NUMUNE] AS
SELECT * FROM [Lbys].[TETKIK_NUMUNE];
GO

-- TETKIK_PARAMETRE
CREATE OR ALTER VIEW [dbo].[VEM_TETKIK_PARAMETRE] AS
SELECT * FROM [Lbys].[TETKIK_PARAMETRE];
GO

-- TETKIK_REFERANS_ARALIK
CREATE OR ALTER VIEW [dbo].[VEM_TETKIK_REFERANS_ARALIK] AS
SELECT * FROM [Lbys].[TETKIK_REFERANS_ARALIK];
GO

-- TETKIK_SONUC
CREATE OR ALTER VIEW [dbo].[VEM_TETKIK_SONUC] AS
SELECT * FROM [Lbys].[TETKIK_SONUC];
GO

-- TIBBI_ORDER
CREATE OR ALTER VIEW [dbo].[VEM_TIBBI_ORDER] AS
SELECT * FROM [Lbys].[TIBBI_ORDER];
GO

-- TIBBI_ORDER_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_TIBBI_ORDER_DETAY] AS
SELECT * FROM [Lbys].[TIBBI_ORDER_DETAY];
GO

-- VEZNE
CREATE OR ALTER VIEW [dbo].[VEM_VEZNE] AS
SELECT * FROM [Lbys].[VEZNE];
GO

-- VEZNE_DETAY
CREATE OR ALTER VIEW [dbo].[VEM_VEZNE_DETAY] AS
SELECT * FROM [Lbys].[VEZNE_DETAY];
GO

-- YATAK
CREATE OR ALTER VIEW [dbo].[VEM_YATAK] AS
SELECT * FROM [Lbys].[YATAK];
GO

-- =============================================================================
-- End of Script
-- Total Views Created: 141
-- =============================================================================
