-- =============================================================================
-- dbo SQL Views DROP Script
-- Drops all VEM views from [dbo] schema
-- =============================================================================

DROP VIEW IF EXISTS [dbo].[VEM_AMELIYAT];
GO
DROP VIEW IF EXISTS [dbo].[VEM_AMELIYAT_EKIP];
GO
DROP VIEW IF EXISTS [dbo].[VEM_AMELIYAT_ISLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_ANLIK_YATAN_HASTA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_ANTIBIYOTIK_SONUC];
GO
DROP VIEW IF EXISTS [dbo].[VEM_ASI_BILGISI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_BAKTERI_SONUC];
GO
DROP VIEW IF EXISTS [dbo].[VEM_BASVURU_TANI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_BASVURU_YEMEK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_BEBEK_COCUK_IZLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_BILDIRIMI_ZORUNLU];
GO
DROP VIEW IF EXISTS [dbo].[VEM_BINA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_BIRIM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_CIHAZ];
GO
DROP VIEW IF EXISTS [dbo].[VEM_COCUK_DIYABET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DEPO];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DIS_TAAHHUT];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DIS_TAAHHUT_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DISPROTEZ];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DISPROTEZ_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DIYABET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DOGUM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DOGUM_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_DOKTOR_MESAJI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_EK_ODEME];
GO
DROP VIEW IF EXISTS [dbo].[VEM_EK_ODEME_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_EK_ODEME_DONEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_EVDE_SAGLIK_IZLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_FATURA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_FIRMA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_GEBE_IZLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_GETAT];
GO
DROP VIEW IF EXISTS [dbo].[VEM_GRUP_UYELIK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_ADLI_RAPOR];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_ARSIV];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_ARSIV_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_BASVURU];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_BORC];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_DIS];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_EPIKRIZ];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_FOTOGRAF];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_GIZLILIK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_HIZMET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_ILETISIM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_MALZEME];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_NOTLARI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_OLUM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_SEANS];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_SEVK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_TIBBI_BILGI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_UYARI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_VENTILATOR];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_VITAL_FIZIKI_BULGU];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HASTA_YATAK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HEMOGLOBINOPATI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HEMSIRE_BAKIM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_HIZMET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_ICMAL];
GO
DROP VIEW IF EXISTS [dbo].[VEM_ILAC_UYUM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_INTIHAR_IZLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KADIN_IZLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KAN_BAGISCI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KAN_CIKIS];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KAN_STOK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KAN_TALEP];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KAN_TALEP_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KAN_URUN];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KAN_URUN_IMHA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KLINIK_SEYIR];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KONSULTASYON];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KUDUZ_IZLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KULLANICI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KULLANICI_GRUP];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KURUL];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KURUL_ASKERI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KURUL_ENGELLI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KURUL_ETKEN_MADDE];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KURUL_HEKIM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KURUL_RAPOR];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KURUL_TESHIS];
GO
DROP VIEW IF EXISTS [dbo].[VEM_KURUM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_LOHUSA_IZLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_MADDE_BAGIMLILIGI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_MEDULA_TAKIP];
GO
DROP VIEW IF EXISTS [dbo].[VEM_NOBETCI_PERSONEL_BILGISI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_OBEZITE_IZLEM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_ODA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_OPTIK_RECETE];
GO
DROP VIEW IF EXISTS [dbo].[VEM_ORTODONTI_ICON_SKOR];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PATOLOJI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_BAKMAKLA_YUKUMLU];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_BANKA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_BORDRO];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_BORDRO_SONDURUM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_EGITIM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_GOREVLENDIRME];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_IZIN];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_IZIN_DURUMU];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_ODUL_CEZA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_OGRENIM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_PERSONEL_YANDAL];
GO
DROP VIEW IF EXISTS [dbo].[VEM_RADYOLOJI];
GO
DROP VIEW IF EXISTS [dbo].[VEM_RADYOLOJI_SONUC];
GO
DROP VIEW IF EXISTS [dbo].[VEM_RANDEVU];
GO
DROP VIEW IF EXISTS [dbo].[VEM_RECETE];
GO
DROP VIEW IF EXISTS [dbo].[VEM_RECETE_ILAC];
GO
DROP VIEW IF EXISTS [dbo].[VEM_RECETE_ILAC_ACIKLAMA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_REFERANS_KODLAR];
GO
DROP VIEW IF EXISTS [dbo].[VEM_RISK_SKORLAMA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_RISK_SKORLAMA_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_SILINEN_KAYITLAR];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STERILIZASYON_CIKIS];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STERILIZASYON_GIRIS];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STERILIZASYON_PAKET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STERILIZASYON_PAKET_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STERILIZASYON_SET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STERILIZASYON_SET_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STERILIZASYON_STOK_DURUM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STERILIZASYON_YIKAMA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STOK_DURUM];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STOK_EHU_TAKIP];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STOK_FIS];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STOK_HAREKET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STOK_ISTEK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STOK_ISTEK_HAREKET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STOK_ISTEK_UYGULAMA];
GO
DROP VIEW IF EXISTS [dbo].[VEM_STOK_KART];
GO
DROP VIEW IF EXISTS [dbo].[VEM_SYS_PAKET];
GO
DROP VIEW IF EXISTS [dbo].[VEM_TETKIK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_TETKIK_CIHAZ_ESLESME];
GO
DROP VIEW IF EXISTS [dbo].[VEM_TETKIK_NUMUNE];
GO
DROP VIEW IF EXISTS [dbo].[VEM_TETKIK_PARAMETRE];
GO
DROP VIEW IF EXISTS [dbo].[VEM_TETKIK_REFERANS_ARALIK];
GO
DROP VIEW IF EXISTS [dbo].[VEM_TETKIK_SONUC];
GO
DROP VIEW IF EXISTS [dbo].[VEM_TIBBI_ORDER];
GO
DROP VIEW IF EXISTS [dbo].[VEM_TIBBI_ORDER_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_VEZNE];
GO
DROP VIEW IF EXISTS [dbo].[VEM_VEZNE_DETAY];
GO
DROP VIEW IF EXISTS [dbo].[VEM_YATAK];
GO

-- =============================================================================
-- End of Drop Script
-- Total Views Dropped: 141
-- =============================================================================
