-- =============================================================================
-- Drop REFERANS_TABLO_ADI column from all Lbys tables
-- Tables affected: 114
-- =============================================================================

-- AMELIYAT_EKIP
ALTER TABLE [Lbys].[AMELIYAT_EKIP] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- AMELIYAT_ISLEM
ALTER TABLE [Lbys].[AMELIYAT_ISLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- ANLIK_YATAN_HASTA
ALTER TABLE [Lbys].[ANLIK_YATAN_HASTA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- ANTIBIYOTIK_SONUC
ALTER TABLE [Lbys].[ANTIBIYOTIK_SONUC] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- ASI_BILGISI
ALTER TABLE [Lbys].[ASI_BILGISI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- BAKTERI_SONUC
ALTER TABLE [Lbys].[BAKTERI_SONUC] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- BASVURU_YEMEK
ALTER TABLE [Lbys].[BASVURU_YEMEK] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- BEBEK_COCUK_IZLEM
ALTER TABLE [Lbys].[BEBEK_COCUK_IZLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- BILDIRIMI_ZORUNLU
ALTER TABLE [Lbys].[BILDIRIMI_ZORUNLU] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- COCUK_DIYABET
ALTER TABLE [Lbys].[COCUK_DIYABET] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- DIS_TAAHHUT
ALTER TABLE [Lbys].[DIS_TAAHHUT] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- DIS_TAAHHUT_DETAY
ALTER TABLE [Lbys].[DIS_TAAHHUT_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- DISPROTEZ
ALTER TABLE [Lbys].[DISPROTEZ] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- DISPROTEZ_DETAY
ALTER TABLE [Lbys].[DISPROTEZ_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- DIYABET
ALTER TABLE [Lbys].[DIYABET] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- DOGUM
ALTER TABLE [Lbys].[DOGUM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- DOGUM_DETAY
ALTER TABLE [Lbys].[DOGUM_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- DOKTOR_MESAJI
ALTER TABLE [Lbys].[DOKTOR_MESAJI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- EK_ODEME
ALTER TABLE [Lbys].[EK_ODEME] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- EK_ODEME_DETAY
ALTER TABLE [Lbys].[EK_ODEME_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- EK_ODEME_DONEM
ALTER TABLE [Lbys].[EK_ODEME_DONEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- EVDE_SAGLIK_IZLEM
ALTER TABLE [Lbys].[EVDE_SAGLIK_IZLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- FIRMA
ALTER TABLE [Lbys].[FIRMA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- GEBE_IZLEM
ALTER TABLE [Lbys].[GEBE_IZLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- GETAT
ALTER TABLE [Lbys].[GETAT] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- GRUP_UYELIK
ALTER TABLE [Lbys].[GRUP_UYELIK] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_ADLI_RAPOR
ALTER TABLE [Lbys].[HASTA_ADLI_RAPOR] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_ARSIV
ALTER TABLE [Lbys].[HASTA_ARSIV] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_ARSIV_DETAY
ALTER TABLE [Lbys].[HASTA_ARSIV_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_BORC
ALTER TABLE [Lbys].[HASTA_BORC] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_DIS
ALTER TABLE [Lbys].[HASTA_DIS] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_EPIKRIZ
ALTER TABLE [Lbys].[HASTA_EPIKRIZ] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_FOTOGRAF
ALTER TABLE [Lbys].[HASTA_FOTOGRAF] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_GIZLILIK
ALTER TABLE [Lbys].[HASTA_GIZLILIK] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_ILETISIM
ALTER TABLE [Lbys].[HASTA_ILETISIM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_MALZEME
ALTER TABLE [Lbys].[HASTA_MALZEME] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_NOTLARI
ALTER TABLE [Lbys].[HASTA_NOTLARI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_OLUM
ALTER TABLE [Lbys].[HASTA_OLUM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_SEANS
ALTER TABLE [Lbys].[HASTA_SEANS] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_SEVK
ALTER TABLE [Lbys].[HASTA_SEVK] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_TIBBI_BILGI
ALTER TABLE [Lbys].[HASTA_TIBBI_BILGI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_UYARI
ALTER TABLE [Lbys].[HASTA_UYARI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_VENTILATOR
ALTER TABLE [Lbys].[HASTA_VENTILATOR] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HASTA_VITAL_FIZIKI_BULGU
ALTER TABLE [Lbys].[HASTA_VITAL_FIZIKI_BULGU] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HEMOGLOBINOPATI
ALTER TABLE [Lbys].[HEMOGLOBINOPATI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- HEMSIRE_BAKIM
ALTER TABLE [Lbys].[HEMSIRE_BAKIM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- ILAC_UYUM
ALTER TABLE [Lbys].[ILAC_UYUM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- INTIHAR_IZLEM
ALTER TABLE [Lbys].[INTIHAR_IZLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KADIN_IZLEM
ALTER TABLE [Lbys].[KADIN_IZLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KAN_BAGISCI
ALTER TABLE [Lbys].[KAN_BAGISCI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KAN_CIKIS
ALTER TABLE [Lbys].[KAN_CIKIS] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KAN_STOK
ALTER TABLE [Lbys].[KAN_STOK] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KAN_TALEP
ALTER TABLE [Lbys].[KAN_TALEP] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KAN_TALEP_DETAY
ALTER TABLE [Lbys].[KAN_TALEP_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KAN_URUN
ALTER TABLE [Lbys].[KAN_URUN] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KAN_URUN_IMHA
ALTER TABLE [Lbys].[KAN_URUN_IMHA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KLINIK_SEYIR
ALTER TABLE [Lbys].[KLINIK_SEYIR] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KONSULTASYON
ALTER TABLE [Lbys].[KONSULTASYON] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KUDUZ_IZLEM
ALTER TABLE [Lbys].[KUDUZ_IZLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KULLANICI_GRUP
ALTER TABLE [Lbys].[KULLANICI_GRUP] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KURUL
ALTER TABLE [Lbys].[KURUL] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KURUL_ASKERI
ALTER TABLE [Lbys].[KURUL_ASKERI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KURUL_ENGELLI
ALTER TABLE [Lbys].[KURUL_ENGELLI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KURUL_ETKEN_MADDE
ALTER TABLE [Lbys].[KURUL_ETKEN_MADDE] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KURUL_HEKIM
ALTER TABLE [Lbys].[KURUL_HEKIM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KURUL_RAPOR
ALTER TABLE [Lbys].[KURUL_RAPOR] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- KURUL_TESHIS
ALTER TABLE [Lbys].[KURUL_TESHIS] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- LOHUSA_IZLEM
ALTER TABLE [Lbys].[LOHUSA_IZLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- MADDE_BAGIMLILIGI
ALTER TABLE [Lbys].[MADDE_BAGIMLILIGI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- MEDULA_TAKIP
ALTER TABLE [Lbys].[MEDULA_TAKIP] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- NOBETCI_PERSONEL_BILGISI
ALTER TABLE [Lbys].[NOBETCI_PERSONEL_BILGISI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- OBEZITE_IZLEM
ALTER TABLE [Lbys].[OBEZITE_IZLEM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- OPTIK_RECETE
ALTER TABLE [Lbys].[OPTIK_RECETE] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- ORTODONTI_ICON_SKOR
ALTER TABLE [Lbys].[ORTODONTI_ICON_SKOR] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PATOLOJI
ALTER TABLE [Lbys].[PATOLOJI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_BAKMAKLA_YUKUMLU
ALTER TABLE [Lbys].[PERSONEL_BAKMAKLA_YUKUMLU] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_BANKA
ALTER TABLE [Lbys].[PERSONEL_BANKA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_BORDRO
ALTER TABLE [Lbys].[PERSONEL_BORDRO] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_BORDRO_SONDURUM
ALTER TABLE [Lbys].[PERSONEL_BORDRO_SONDURUM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_EGITIM
ALTER TABLE [Lbys].[PERSONEL_EGITIM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_GOREVLENDIRME
ALTER TABLE [Lbys].[PERSONEL_GOREVLENDIRME] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_IZIN
ALTER TABLE [Lbys].[PERSONEL_IZIN] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_IZIN_DURUMU
ALTER TABLE [Lbys].[PERSONEL_IZIN_DURUMU] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_ODUL_CEZA
ALTER TABLE [Lbys].[PERSONEL_ODUL_CEZA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_OGRENIM
ALTER TABLE [Lbys].[PERSONEL_OGRENIM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- PERSONEL_YANDAL
ALTER TABLE [Lbys].[PERSONEL_YANDAL] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- RADYOLOJI
ALTER TABLE [Lbys].[RADYOLOJI] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- RADYOLOJI_SONUC
ALTER TABLE [Lbys].[RADYOLOJI_SONUC] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- RECETE_ILAC
ALTER TABLE [Lbys].[RECETE_ILAC] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- RECETE_ILAC_ACIKLAMA
ALTER TABLE [Lbys].[RECETE_ILAC_ACIKLAMA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- RISK_SKORLAMA
ALTER TABLE [Lbys].[RISK_SKORLAMA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- RISK_SKORLAMA_DETAY
ALTER TABLE [Lbys].[RISK_SKORLAMA_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STERILIZASYON_CIKIS
ALTER TABLE [Lbys].[STERILIZASYON_CIKIS] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STERILIZASYON_GIRIS
ALTER TABLE [Lbys].[STERILIZASYON_GIRIS] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STERILIZASYON_PAKET
ALTER TABLE [Lbys].[STERILIZASYON_PAKET] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STERILIZASYON_PAKET_DETAY
ALTER TABLE [Lbys].[STERILIZASYON_PAKET_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STERILIZASYON_SET
ALTER TABLE [Lbys].[STERILIZASYON_SET] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STERILIZASYON_SET_DETAY
ALTER TABLE [Lbys].[STERILIZASYON_SET_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STERILIZASYON_STOK_DURUM
ALTER TABLE [Lbys].[STERILIZASYON_STOK_DURUM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STERILIZASYON_YIKAMA
ALTER TABLE [Lbys].[STERILIZASYON_YIKAMA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STOK_DURUM
ALTER TABLE [Lbys].[STOK_DURUM] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STOK_EHU_TAKIP
ALTER TABLE [Lbys].[STOK_EHU_TAKIP] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STOK_FIS
ALTER TABLE [Lbys].[STOK_FIS] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STOK_HAREKET
ALTER TABLE [Lbys].[STOK_HAREKET] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STOK_ISTEK
ALTER TABLE [Lbys].[STOK_ISTEK] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STOK_ISTEK_HAREKET
ALTER TABLE [Lbys].[STOK_ISTEK_HAREKET] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- STOK_ISTEK_UYGULAMA
ALTER TABLE [Lbys].[STOK_ISTEK_UYGULAMA] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- SYS_PAKET
ALTER TABLE [Lbys].[SYS_PAKET] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- TETKIK_CIHAZ_ESLESME
ALTER TABLE [Lbys].[TETKIK_CIHAZ_ESLESME] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- TETKIK_REFERANS_ARALIK
ALTER TABLE [Lbys].[TETKIK_REFERANS_ARALIK] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- TIBBI_ORDER
ALTER TABLE [Lbys].[TIBBI_ORDER] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- TIBBI_ORDER_DETAY
ALTER TABLE [Lbys].[TIBBI_ORDER_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- VEZNE
ALTER TABLE [Lbys].[VEZNE] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- VEZNE_DETAY
ALTER TABLE [Lbys].[VEZNE_DETAY] DROP COLUMN [REFERANS_TABLO_ADI];
GO

-- =============================================================================
-- End of Script - Total columns dropped: 114
-- =============================================================================