-- =============================================================================
-- VEM Temel Demo Veri Seed Script
-- Sadece basit tablolar icin
-- =============================================================================

USE TESTDATA;
GO

-- =============================================================================
-- 1. HASTA_ILETISIM - Iletisim bilgileri
-- =============================================================================
INSERT INTO [Lbys].[HASTA_ILETISIM]
(HASTA_ILETISIM_KODU, REFERANS_TABLO_ADI, HASTA_KODU, HASTA_BASVURU_KODU, ADRES_TIPI, ADRES_KODU_SEVIYESI,
 BEYAN_ADRESI, NVI_ADRES, ADRES_NUMARASI, IL_KODU, ILCE_KODU, BUCAK_KODU, KOY_KODU, MAHALLE_KODU,
 CSBM_KODU, DIS_KAPI_NUMARASI, IC_KAPI_NUMARASI, EV_TELEFONU, CEP_TELEFONU, IS_TELEFONU,
 EPOSTA_ADRESI, EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
SELECT TOP 30
    N'HI-' + CAST(ROW_NUMBER() OVER (ORDER BY h.HASTA_KODU) AS NVARCHAR(10)),
    N'HASTA_ILETISIM',
    h.HASTA_KODU,
    b.HASTA_BASVURU_KODU,
    N'1', N'1',
    N'Test Adresi', N'Test NVI', N'1', N'34', N'1', N'1', N'1', N'1',
    N'1', N'10', N'5', N'02121234567', N'05321234567', N'02129876543',
    N'test@email.com', N'SYSTEM', GETDATE()
FROM [Lbys].[HASTA] h
INNER JOIN [Lbys].[HASTA_BASVURU] b ON h.HASTA_KODU = b.HASTA_KODU
WHERE h.HASTA_KODU NOT IN (SELECT HASTA_KODU FROM [Lbys].[HASTA_ILETISIM] WHERE HASTA_KODU IS NOT NULL);
GO

-- =============================================================================
-- 2. ASI_BILGISI
-- =============================================================================
INSERT INTO [Lbys].[ASI_BILGISI]
(ASI_BILGISI_KODU, REFERANS_TABLO_ADI, HASTA_KODU, HASTA_BASVURU_KODU, ASI_KODU, ASININ_DOZU,
 ASININ_UYGULAMA_SEKLI, ASI_UYGULAMA_YERI, ASI_SORGU_NUMARASI, ASI_ISLEM_TURU,
 BILGI_ALINAN_KISI_AD_SOYADI, BILGI_ALINAN_KISI_TELEFON, ASI_YAPILMA_ZAMANI,
 EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
SELECT TOP 25
    N'ASI-' + CAST(ROW_NUMBER() OVER (ORDER BY h.HASTA_KODU) AS NVARCHAR(10)),
    N'ASI_BILGISI',
    h.HASTA_KODU,
    b.HASTA_BASVURU_KODU,
    N'1', N'1', N'1', N'1',
    N'ASI-SRG-' + CAST(ROW_NUMBER() OVER (ORDER BY h.HASTA_KODU) AS NVARCHAR(10)),
    N'1',
    N'Test Kisi', N'05001234567',
    DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 365, GETDATE()),
    N'SYSTEM', GETDATE()
FROM [Lbys].[HASTA] h
INNER JOIN [Lbys].[HASTA_BASVURU] b ON h.HASTA_KODU = b.HASTA_KODU
WHERE h.HASTA_KODU NOT IN (SELECT HASTA_KODU FROM [Lbys].[ASI_BILGISI] WHERE HASTA_KODU IS NOT NULL);
GO

-- =============================================================================
-- 3. GEBE_IZLEM
-- =============================================================================
INSERT INTO [Lbys].[GEBE_IZLEM]
(GEBE_IZLEM_KODU, REFERANS_TABLO_ADI, HASTA_KODU, HASTA_BASVURU_KODU,
 KACINCI_GEBE_IZLEM, SON_ADET_TARIHI, ONCEKI_DOGUM_DURUMU, GEBE_IZLEM_ISLEM_TURU,
 GESTASYONEL_DIYABET_TARAMASI, IDRARDA_PROTEIN, HEMOGLOBIN_DEGERI,
 DEMIR_LOJISTIGI_VE_DESTEGI, DVITAMINI_LOJISTIGI_VE_DESTEGI, KONJENITAL_ANOMALI_VARLIGI,
 FETUS_KALP_SESI, DIASTOLIK_KAN_BASINCI_DEGERI, SISTOLIK_KAN_BASINCI_DEGERI,
 GEBELIKTE_RISK_FAKTORLERI, BC_BEYIN_GELISIM_RISKLERI, PSIKOLOJIK_GELISIM_RISK_EGITIM,
 RISK_FAKTORLERINE_MUDAHALE, RISK_ALTINDAKI_OLGU_TAKIBI, ACIKLAMA,
 EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
SELECT TOP 20
    N'GI-' + CAST(ROW_NUMBER() OVER (ORDER BY h.HASTA_KODU) AS NVARCHAR(10)),
    N'GEBE_IZLEM',
    h.HASTA_KODU,
    b.HASTA_BASVURU_KODU,
    N'1', DATEADD(MONTH, -3, GETDATE()), N'0', N'1',
    N'1', N'1', N'12.5',
    N'1', N'1', N'1',
    N'140', N'80', N'120',
    N'1', N'1', N'1',
    N'1', N'1', N'Test Aciklama',
    N'SYSTEM', GETDATE()
FROM [Lbys].[HASTA] h
INNER JOIN [Lbys].[HASTA_BASVURU] b ON h.HASTA_KODU = b.HASTA_KODU
WHERE h.HASTA_KODU NOT IN (SELECT HASTA_KODU FROM [Lbys].[GEBE_IZLEM] WHERE HASTA_KODU IS NOT NULL);
GO

-- =============================================================================
-- 4. HEMSIRE_BAKIM
-- =============================================================================
INSERT INTO [Lbys].[HEMSIRE_BAKIM]
(HEMSIRE_BAKIM_KODU, REFERANS_TABLO_ADI, HASTA_KODU, HASTA_BASVURU_KODU,
 BIRIM_KODU, HEMSIRE_KODU, HEMSIRELIK_TANI_KODU, HEMSIRELIK_GIRISIMI,
 HEMSIRE_BAKIM_HEDEF_SONUC, BAKIM_NOTU, BAKIM_KAYIT_ZAMANI,
 EKLEYEN_KULLANICI_KODU, KAYIT_ZAMANI)
SELECT TOP 25
    N'HB-' + CAST(ROW_NUMBER() OVER (ORDER BY b.HASTA_BASVURU_KODU) AS NVARCHAR(10)),
    N'HEMSIRE_BAKIM',
    b.HASTA_KODU,
    b.HASTA_BASVURU_KODU,
    b.BIRIM_KODU,
    (SELECT TOP 1 PERSONEL_KODU FROM [Lbys].[PERSONEL] ORDER BY NEWID()),
    N'1', N'1', N'1', N'Bakim notu',
    GETDATE(),
    N'SYSTEM', GETDATE()
FROM [Lbys].[HASTA_BASVURU] b
WHERE b.BIRIM_KODU IS NOT NULL
  AND b.HASTA_BASVURU_KODU NOT IN (SELECT HASTA_BASVURU_KODU FROM [Lbys].[HEMSIRE_BAKIM] WHERE HASTA_BASVURU_KODU IS NOT NULL);
GO

-- =============================================================================
-- 5. ANLIK_YATAN_HASTA
-- =============================================================================
INSERT INTO [Lbys].[ANLIK_YATAN_HASTA]
(ANLIK_YATAN_HASTA_KODU, REFERANS_TABLO_ADI, HASTA_KODU, HASTA_BASVURU_KODU,
 HEKIM_KODU, YATIS_PROTOKOL_NUMARASI, BIRIM_KODU, YATIS_ZAMANI)
SELECT TOP 20
    N'AYH-' + CAST(ROW_NUMBER() OVER (ORDER BY b.HASTA_BASVURU_KODU) AS NVARCHAR(10)),
    N'ANLIK_YATAN_HASTA',
    b.HASTA_KODU,
    b.HASTA_BASVURU_KODU,
    b.HEKIM_KODU,
    N'YP-' + CAST(ROW_NUMBER() OVER (ORDER BY b.HASTA_BASVURU_KODU) AS NVARCHAR(10)),
    b.BIRIM_KODU,
    DATEADD(DAY, -ABS(CHECKSUM(NEWID())) % 10, GETDATE())
FROM [Lbys].[HASTA_BASVURU] b
WHERE b.HEKIM_KODU IS NOT NULL
  AND b.BIRIM_KODU IS NOT NULL
  AND b.HASTA_BASVURU_KODU NOT IN (SELECT HASTA_BASVURU_KODU FROM [Lbys].[ANLIK_YATAN_HASTA] WHERE HASTA_BASVURU_KODU IS NOT NULL);
GO

PRINT 'Temel demo veri seed islemi tamamlandi!';
GO

-- Sonuclari kontrol et
SELECT 'HASTA_ILETISIM' as Tablo, COUNT(*) as Kayit FROM [Lbys].[HASTA_ILETISIM] UNION ALL
SELECT 'ASI_BILGISI', COUNT(*) FROM [Lbys].[ASI_BILGISI] UNION ALL
SELECT 'GEBE_IZLEM', COUNT(*) FROM [Lbys].[GEBE_IZLEM] UNION ALL
SELECT 'HEMSIRE_BAKIM', COUNT(*) FROM [Lbys].[HEMSIRE_BAKIM] UNION ALL
SELECT 'ANLIK_YATAN_HASTA', COUNT(*) FROM [Lbys].[ANLIK_YATAN_HASTA]
ORDER BY Tablo;
GO
