-- =============================================================================
-- Table Updates Script - Add/Remove Fields
-- Generated from table_changes.json
-- =============================================================================

-- =============================================================================
-- STEP 1: Drop Foreign Keys and Indexes on columns to be removed
-- =============================================================================

-- PERSONEL FK/IX
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PERSONEL_BIRIM_BIRIM_KODU')
    ALTER TABLE [Lbys].[PERSONEL] DROP CONSTRAINT [FK_PERSONEL_BIRIM_BIRIM_KODU];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PERSONEL_BIRIM_KODU' AND object_id = OBJECT_ID('[Lbys].[PERSONEL]'))
    DROP INDEX [IX_PERSONEL_BIRIM_KODU] ON [Lbys].[PERSONEL];
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PERSONEL_REFERANS_KODLAR_UZMANLIK_KODU')
    ALTER TABLE [Lbys].[PERSONEL] DROP CONSTRAINT [FK_PERSONEL_REFERANS_KODLAR_UZMANLIK_KODU];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PERSONEL_UZMANLIK_KODU' AND object_id = OBJECT_ID('[Lbys].[PERSONEL]'))
    DROP INDEX [IX_PERSONEL_UZMANLIK_KODU] ON [Lbys].[PERSONEL];
GO

-- HASTA_BASVURU FK/IX
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HASTA_BASVURU_REFERANS_KODLAR_BASVURU_SEKLI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP CONSTRAINT [FK_HASTA_BASVURU_REFERANS_KODLAR_BASVURU_SEKLI];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HASTA_BASVURU_BASVURU_SEKLI' AND object_id = OBJECT_ID('[Lbys].[HASTA_BASVURU]'))
    DROP INDEX [IX_HASTA_BASVURU_BASVURU_SEKLI] ON [Lbys].[HASTA_BASVURU];
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HASTA_BASVURU_REFERANS_KODLAR_BASVURU_TURU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP CONSTRAINT [FK_HASTA_BASVURU_REFERANS_KODLAR_BASVURU_TURU];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HASTA_BASVURU_BASVURU_TURU' AND object_id = OBJECT_ID('[Lbys].[HASTA_BASVURU]'))
    DROP INDEX [IX_HASTA_BASVURU_BASVURU_TURU] ON [Lbys].[HASTA_BASVURU];
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HASTA_BASVURU_PERSONEL_DOKTOR_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP CONSTRAINT [FK_HASTA_BASVURU_PERSONEL_DOKTOR_KODU];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HASTA_BASVURU_DOKTOR_KODU' AND object_id = OBJECT_ID('[Lbys].[HASTA_BASVURU]'))
    DROP INDEX [IX_HASTA_BASVURU_DOKTOR_KODU] ON [Lbys].[HASTA_BASVURU];
GO

-- KURUM FK/IX
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_KURUM_REFERANS_KODLAR_KURUM_TURU')
    ALTER TABLE [Lbys].[KURUM] DROP CONSTRAINT [FK_KURUM_REFERANS_KODLAR_KURUM_TURU];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_KURUM_KURUM_TURU' AND object_id = OBJECT_ID('[Lbys].[KURUM]'))
    DROP INDEX [IX_KURUM_KURUM_TURU] ON [Lbys].[KURUM];
GO

-- BIRIM FK/IX
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_BIRIM_KURUM_KURUM_KODU')
    ALTER TABLE [Lbys].[BIRIM] DROP CONSTRAINT [FK_BIRIM_KURUM_KURUM_KODU];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_BIRIM_KURUM_KODU' AND object_id = OBJECT_ID('[Lbys].[BIRIM]'))
    DROP INDEX [IX_BIRIM_KURUM_KODU] ON [Lbys].[BIRIM];
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_BIRIM_BIRIM_UST_BIRIM_KODU')
    ALTER TABLE [Lbys].[BIRIM] DROP CONSTRAINT [FK_BIRIM_BIRIM_UST_BIRIM_KODU];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_BIRIM_UST_BIRIM_KODU' AND object_id = OBJECT_ID('[Lbys].[BIRIM]'))
    DROP INDEX [IX_BIRIM_UST_BIRIM_KODU] ON [Lbys].[BIRIM];
GO

-- HASTA FK/IX
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HASTA_REFERANS_KODLAR_MEDENI_HAL')
    ALTER TABLE [Lbys].[HASTA] DROP CONSTRAINT [FK_HASTA_REFERANS_KODLAR_MEDENI_HAL];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HASTA_MEDENI_HAL' AND object_id = OBJECT_ID('[Lbys].[HASTA]'))
    DROP INDEX [IX_HASTA_MEDENI_HAL] ON [Lbys].[HASTA];
GO
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_HASTA_REFERANS_KODLAR_SOSYAL_GUVENCE')
    ALTER TABLE [Lbys].[HASTA] DROP CONSTRAINT [FK_HASTA_REFERANS_KODLAR_SOSYAL_GUVENCE];
GO
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_HASTA_SOSYAL_GUVENCE' AND object_id = OBJECT_ID('[Lbys].[HASTA]'))
    DROP INDEX [IX_HASTA_SOSYAL_GUVENCE] ON [Lbys].[HASTA];
GO

-- =============================================================================
-- STEP 2: Add new columns and remove old columns
-- =============================================================================

-- PERSONEL
-- Add: 49 fields, Remove: 11 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ACIK_ADRES')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ACIK_ADRES] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ADRES_KODU_SEVIYESI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ADRES_KODU_SEVIYESI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ADRES_TIPI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ADRES_TIPI] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'AKADEMIK_UNVAN')
    ALTER TABLE [Lbys].[PERSONEL] ADD [AKADEMIK_UNVAN] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'AKTIFLIK_BILGISI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [AKTIFLIK_BILGISI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ANNE_ADI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ANNE_ADI] NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ASALET_ALMA_TARIHI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ASALET_ALMA_TARIHI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ASKERLIK_DURUMU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ASKERLIK_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'BABA_ADI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [BABA_ADI] NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'CALISMA_DURUMU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [CALISMA_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'CALISTIGI_BIRIM_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [CALISTIGI_BIRIM_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'CEP_TELEFONU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [CEP_TELEFONU] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'DEVLET_HIZMET_YUKUMLULUK_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [DEVLET_HIZMET_YUKUMLULUK_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'DIPLOMA_NUMARASI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [DIPLOMA_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'DOGUM_YERI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [DOGUM_YERI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'EMEKLI_SICIL_NUMARASI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [EMEKLI_SICIL_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'EMEKLI_TERFI_TARIHI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [EMEKLI_TERFI_TARIHI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ENGELLILIK_DURUMU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ENGELLILIK_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'EPOSTA_ADRESI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [EPOSTA_ADRESI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'EV_TELEFONU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [EV_TELEFONU] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'FOTOGRAF_BILGISI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [FOTOGRAF_BILGISI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'FOTOGRAF_DOSYA_YOLU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [FOTOGRAF_DOSYA_YOLU] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'HEKIM_MEDULA_SIFRESI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [HEKIM_MEDULA_SIFRESI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'IL_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [IL_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ILCE_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ILCE_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ILK_ISE_BASLAMA_TARIHI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ILK_ISE_BASLAMA_TARIHI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'IMZA_UNVAN_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [IMZA_UNVAN_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'IS_DURUMU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [IS_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ISTEN_AYRILMA_ACIKLAMASI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ISTEN_AYRILMA_ACIKLAMASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ISTEN_AYRILMA_NEDENI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ISTEN_AYRILMA_NEDENI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ISTEN_AYRILMA_TARIHI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ISTEN_AYRILMA_TARIHI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'KADRO_UNVAN_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [KADRO_UNVAN_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'KADROLU_GOREV_YERI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [KADROLU_GOREV_YERI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'KAN_GRUBU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [KAN_GRUBU] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'KLINIK_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [KLINIK_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'MEDULA_BRANS_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [MEDULA_BRANS_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'MEMURIYET_TIPI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [MEMURIYET_TIPI] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'MEMURIYETE_BASLAMA_TARIHI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [MEMURIYETE_BASLAMA_TARIHI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'OGRENIM_DURUMU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [OGRENIM_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ONCEKI_SOYADI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ONCEKI_SOYADI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'PERSONEL_GOREV_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [PERSONEL_GOREV_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'PERSONEL_SICIL_NUMARASI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [PERSONEL_SICIL_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'SAGLIK_TESISINE_BASLAMA_TARIHI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [SAGLIK_TESISINE_BASLAMA_TARIHI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'SOYADI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [SOYADI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'TC_KIMLIK_NUMARASI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [TC_KIMLIK_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'TERFI_TARIHI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [TERFI_TARIHI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'TESCIL_NUMARASI')
    ALTER TABLE [Lbys].[PERSONEL] ADD [TESCIL_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ULKE_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [ULKE_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'UNVAN_KODU')
    ALTER TABLE [Lbys].[PERSONEL] ADD [UNVAN_KODU] NVARCHAR(50) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [AKTIF];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'BIRIM_KODU')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [BIRIM_KODU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'DIPLOMA_NO')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [DIPLOMA_NO];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'DIPLOMA_TESCIL_NO')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [DIPLOMA_TESCIL_NO];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'EMAIL')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [EMAIL];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'ISE_BASLAMA_TARIHI')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [ISE_BASLAMA_TARIHI];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'SOYAD')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [SOYAD];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'TC_KIMLIK_NO')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [TC_KIMLIK_NO];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'TELEFON')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [TELEFON];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'UNVAN')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [UNVAN];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'PERSONEL' AND COLUMN_NAME = 'UZMANLIK_KODU')
    ALTER TABLE [Lbys].[PERSONEL] DROP COLUMN [UZMANLIK_KODU];
GO

-- KULLANICI
-- Add: 6 fields, Remove: 1 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KULLANICI' AND COLUMN_NAME = 'AD')
    ALTER TABLE [Lbys].[KULLANICI] ADD [AD] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KULLANICI' AND COLUMN_NAME = 'AKTIFLIK_BILGISI')
    ALTER TABLE [Lbys].[KULLANICI] ADD [AKTIFLIK_BILGISI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KULLANICI' AND COLUMN_NAME = 'PAROLA')
    ALTER TABLE [Lbys].[KULLANICI] ADD [PAROLA] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KULLANICI' AND COLUMN_NAME = 'PAROLA_SIFRELEME_TURU')
    ALTER TABLE [Lbys].[KULLANICI] ADD [PAROLA_SIFRELEME_TURU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KULLANICI' AND COLUMN_NAME = 'SOYADI')
    ALTER TABLE [Lbys].[KULLANICI] ADD [SOYADI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KULLANICI' AND COLUMN_NAME = 'TC_KIMLIK_NUMARASI')
    ALTER TABLE [Lbys].[KULLANICI] ADD [TC_KIMLIK_NUMARASI] NVARCHAR(100) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KULLANICI' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[KULLANICI] DROP COLUMN [AKTIF];
GO

-- HASTA_BASVURU
-- Add: 43 fields, Remove: 12 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'ADLI_VAKA_GELIS_SEKLI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [ADLI_VAKA_GELIS_SEKLI] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'AMBULANS_PLAKA_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [AMBULANS_PLAKA_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'AMBULANS_TAKIP_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [AMBULANS_TAKIP_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'ARAC_TURU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [ARAC_TURU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'ASISTAN_HEKIM_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [ASISTAN_HEKIM_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'BAGLI_OLDUGU_BASVURU_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [BAGLI_OLDUGU_BASVURU_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'BASVURU_DURUMU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [BASVURU_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'BASVURU_PROTOKOL_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [BASVURU_PROTOKOL_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'CIKIS_VEREN_HEKIM_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [CIKIS_VEREN_HEKIM_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'CIKIS_ZAMANI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [CIKIS_ZAMANI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'DEFTER_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [DEFTER_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'DIYABET_EGITIMI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [DIYABET_EGITIMI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'DIYABET_KOMPLIKASYONLARI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [DIYABET_KOMPLIKASYONLARI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'GEBLIZ_BILDIRIM_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [GEBLIZ_BILDIRIM_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'GELDIGI_ULKE_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [GELDIGI_ULKE_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'GENCLIK_SAGLIGI_ISLEMLERI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [GENCLIK_SAGLIGI_ISLEMLERI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'GUNLUK_SIRA_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [GUNLUK_SIRA_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'HASTA_KABUL_ZAMANI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [HASTA_KABUL_ZAMANI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'HAYATI_TEHLIKE_DURUMU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [HAYATI_TEHLIKE_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'HEKIM_BASVURU_NOTU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [HEKIM_BASVURU_NOTU] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'HEKIM_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [HEKIM_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'HIZMET_SUNUCU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [HIZMET_SUNUCU] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'KABUL_SEKLI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [KABUL_SEKLI] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'KAYIT_YERI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [KAYIT_YERI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'KURUM_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [KURUM_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'MUAYENE_BASLAMA_ZAMANI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [MUAYENE_BASLAMA_ZAMANI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'MUAYENE_BITIS_ZAMANI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [MUAYENE_BITIS_ZAMANI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'MUAYENE_ONCELIK_SIRASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [MUAYENE_ONCELIK_SIRASI] INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'MUAYENE_TURU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [MUAYENE_TURU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'OLAY_AFET_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [OLAY_AFET_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'ONLINE_PROTOKOL_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [ONLINE_PROTOKOL_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SAGLIK_TURIZMI_ULKE_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [SAGLIK_TURIZMI_ULKE_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SEVK_TANISI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [SEVK_TANISI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SEVK_ZAMANI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [SEVK_ZAMANI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SOSYAL_GUVENCE_DURUMU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [SOSYAL_GUVENCE_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SYS_REFERANS_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [SYS_REFERANS_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SYS_TAKIP_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [SYS_TAKIP_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'TAMAMLAYICI_KURUM_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [TAMAMLAYICI_KURUM_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'TRIAJ_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [TRIAJ_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'VAKA_TURU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [VAKA_TURU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'YABANCI_HASTA_TURU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [YABANCI_HASTA_TURU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'YATIS_BILGISI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [YATIS_BILGISI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'YATIS_PROTOKOL_NUMARASI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] ADD [YATIS_PROTOKOL_NUMARASI] NVARCHAR(100) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [AKTIF];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'BASVURU_SEKLI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [BASVURU_SEKLI];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'BASVURU_TARIHI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [BASVURU_TARIHI];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'BASVURU_TURU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [BASVURU_TURU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'CIKIS_TARIHI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [CIKIS_TARIHI];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'DOKTOR_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [DOKTOR_KODU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'PROVIZYON_TIPI')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [PROVIZYON_TIPI];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SEVK_EDEN_KURUM')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [SEVK_EDEN_KURUM];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SIKAYET')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [SIKAYET];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'SONUC_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [SONUC_KODU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'TAKIP_NO')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [TAKIP_NO];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA_BASVURU' AND COLUMN_NAME = 'TANI_KODU')
    ALTER TABLE [Lbys].[HASTA_BASVURU] DROP COLUMN [TANI_KODU];
GO

-- CIHAZ
-- Add: 1 fields, Remove: 1 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'CIHAZ' AND COLUMN_NAME = 'AKTIFLIK_BILGISI')
    ALTER TABLE [Lbys].[CIHAZ] ADD [AKTIFLIK_BILGISI] NVARCHAR(500) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'CIHAZ' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[CIHAZ] DROP COLUMN [AKTIF];
GO

-- HIZMET
-- Add: 1 fields, Remove: 1 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HIZMET' AND COLUMN_NAME = 'AKTIFLIK_BILGISI')
    ALTER TABLE [Lbys].[HIZMET] ADD [AKTIFLIK_BILGISI] NVARCHAR(500) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HIZMET' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[HIZMET] DROP COLUMN [AKTIF];
GO

-- KURUM
-- Add: 8 fields, Remove: 8 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'AKTIFLIK_BILGISI')
    ALTER TABLE [Lbys].[KURUM] ADD [AKTIFLIK_BILGISI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'AYAKTAN_BUTCE_KODU')
    ALTER TABLE [Lbys].[KURUM] ADD [AYAKTAN_BUTCE_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'DEVREDILEN_KURUM')
    ALTER TABLE [Lbys].[KURUM] ADD [DEVREDILEN_KURUM] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'GUNUBIRLIK_BUTCE_KODU')
    ALTER TABLE [Lbys].[KURUM] ADD [GUNUBIRLIK_BUTCE_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'HASTA_KURUM_TURU')
    ALTER TABLE [Lbys].[KURUM] ADD [HASTA_KURUM_TURU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'KURUM_ADRESI')
    ALTER TABLE [Lbys].[KURUM] ADD [KURUM_ADRESI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'SKRS_KURUM_KODU')
    ALTER TABLE [Lbys].[KURUM] ADD [SKRS_KURUM_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'YATAN_BUTCE_KODU')
    ALTER TABLE [Lbys].[KURUM] ADD [YATAN_BUTCE_KODU] NVARCHAR(50) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'ADRES')
    ALTER TABLE [Lbys].[KURUM] DROP COLUMN [ADRES];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'EMAIL')
    ALTER TABLE [Lbys].[KURUM] DROP COLUMN [EMAIL];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'IL_KODU')
    ALTER TABLE [Lbys].[KURUM] DROP COLUMN [IL_KODU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'ILCE_KODU')
    ALTER TABLE [Lbys].[KURUM] DROP COLUMN [ILCE_KODU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'KURUM_TURU')
    ALTER TABLE [Lbys].[KURUM] DROP COLUMN [KURUM_TURU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'TELEFON')
    ALTER TABLE [Lbys].[KURUM] DROP COLUMN [TELEFON];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'VERGI_DAIRESI')
    ALTER TABLE [Lbys].[KURUM] DROP COLUMN [VERGI_DAIRESI];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'KURUM' AND COLUMN_NAME = 'VERGI_NO')
    ALTER TABLE [Lbys].[KURUM] DROP COLUMN [VERGI_NO];
GO

-- BIRIM
-- Add: 8 fields, Remove: 3 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'AKTIFLIK_BILGISI')
    ALTER TABLE [Lbys].[BIRIM] ADD [AKTIFLIK_BILGISI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'BINA_KODU')
    ALTER TABLE [Lbys].[BIRIM] ADD [BINA_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'KLINIK_KODU')
    ALTER TABLE [Lbys].[BIRIM] ADD [KLINIK_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'MEDULA_BRANS_KODU')
    ALTER TABLE [Lbys].[BIRIM] ADD [MEDULA_BRANS_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'MHRS_ADI')
    ALTER TABLE [Lbys].[BIRIM] ADD [MHRS_ADI] NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'MHRS_KODU')
    ALTER TABLE [Lbys].[BIRIM] ADD [MHRS_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'MKYS_KODU')
    ALTER TABLE [Lbys].[BIRIM] ADD [MKYS_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'YATAK_SAYISI')
    ALTER TABLE [Lbys].[BIRIM] ADD [YATAK_SAYISI] INT NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[BIRIM] DROP COLUMN [AKTIF];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'KURUM_KODU')
    ALTER TABLE [Lbys].[BIRIM] DROP COLUMN [KURUM_KODU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'BIRIM' AND COLUMN_NAME = 'UST_BIRIM_KODU')
    ALTER TABLE [Lbys].[BIRIM] DROP COLUMN [UST_BIRIM_KODU];
GO

-- DEPO
-- Add: 2 fields, Remove: 1 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'DEPO' AND COLUMN_NAME = 'AKTIFLIK_BILGISI')
    ALTER TABLE [Lbys].[DEPO] ADD [AKTIFLIK_BILGISI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'DEPO' AND COLUMN_NAME = 'MKYS_KULLANICI_SIFRESI')
    ALTER TABLE [Lbys].[DEPO] ADD [MKYS_KULLANICI_SIFRESI] NVARCHAR(500) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'DEPO' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[DEPO] DROP COLUMN [AKTIF];
GO

-- HASTA
-- Add: 19 fields, Remove: 15 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'ANNE_ADI')
    ALTER TABLE [Lbys].[HASTA] ADD [ANNE_ADI] NVARCHAR(200) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'ANNE_HASTA_KODU')
    ALTER TABLE [Lbys].[HASTA] ADD [ANNE_HASTA_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'ANNE_TC_KIMLIK_NUMARASI')
    ALTER TABLE [Lbys].[HASTA] ADD [ANNE_TC_KIMLIK_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'BABA_HASTA_KODU')
    ALTER TABLE [Lbys].[HASTA] ADD [BABA_HASTA_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'BABA_TC_KIMLIK_NUMARASI')
    ALTER TABLE [Lbys].[HASTA] ADD [BABA_TC_KIMLIK_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'BEYAN_DOGUM_TARIHI')
    ALTER TABLE [Lbys].[HASTA] ADD [BEYAN_DOGUM_TARIHI] DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'DOGUM_SIRASI')
    ALTER TABLE [Lbys].[HASTA] ADD [DOGUM_SIRASI] INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'ENGELLILIK_DURUMU')
    ALTER TABLE [Lbys].[HASTA] ADD [ENGELLILIK_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'HASTA_TIPI')
    ALTER TABLE [Lbys].[HASTA] ADD [HASTA_TIPI] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'KIMLIKSIZ_HASTA_BILGISI')
    ALTER TABLE [Lbys].[HASTA] ADD [KIMLIKSIZ_HASTA_BILGISI] NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'MEDENI_HALI')
    ALTER TABLE [Lbys].[HASTA] ADD [MEDENI_HALI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'MUAYENE_ONCELIK_SIRASI')
    ALTER TABLE [Lbys].[HASTA] ADD [MUAYENE_ONCELIK_SIRASI] INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'OGRENIM_DURUMU')
    ALTER TABLE [Lbys].[HASTA] ADD [OGRENIM_DURUMU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'OLUM_YERI')
    ALTER TABLE [Lbys].[HASTA] ADD [OLUM_YERI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'PASAPORT_NUMARASI')
    ALTER TABLE [Lbys].[HASTA] ADD [PASAPORT_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'SON_KURUM_KODU')
    ALTER TABLE [Lbys].[HASTA] ADD [SON_KURUM_KODU] NVARCHAR(50) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'SOYADI')
    ALTER TABLE [Lbys].[HASTA] ADD [SOYADI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'TC_KIMLIK_NUMARASI')
    ALTER TABLE [Lbys].[HASTA] ADD [TC_KIMLIK_NUMARASI] NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'YUPASS_NUMARASI')
    ALTER TABLE [Lbys].[HASTA] ADD [YUPASS_NUMARASI] NVARCHAR(100) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'ADRES')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [ADRES];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [AKTIF];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'ANA_ADI')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [ANA_ADI];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'CEP_TELEFON')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [CEP_TELEFON];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'EGITIM_DURUMU')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [EGITIM_DURUMU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'EMAIL')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [EMAIL];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'IL_KODU')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [IL_KODU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'ILCE_KODU')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [ILCE_KODU];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'MEDENI_HAL')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [MEDENI_HAL];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'PROTOKOL_NO')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [PROTOKOL_NO];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'SIGORTA_NO')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [SIGORTA_NO];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'SOSYAL_GUVENCE')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [SOSYAL_GUVENCE];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'SOYAD')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [SOYAD];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'TC_KIMLIK_NO')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [TC_KIMLIK_NO];
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'HASTA' AND COLUMN_NAME = 'TELEFON')
    ALTER TABLE [Lbys].[HASTA] DROP COLUMN [TELEFON];
GO

-- TETKIK
-- Add: 1 fields, Remove: 1 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'TETKIK' AND COLUMN_NAME = 'IPTAL_DURUMU')
    ALTER TABLE [Lbys].[TETKIK] ADD [IPTAL_DURUMU] NVARCHAR(50) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'TETKIK' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[TETKIK] DROP COLUMN [AKTIF];
GO

-- TETKIK_PARAMETRE
-- Add: 1 fields, Remove: 1 fields

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'TETKIK_PARAMETRE' AND COLUMN_NAME = 'IPTAL_DURUMU')
    ALTER TABLE [Lbys].[TETKIK_PARAMETRE] ADD [IPTAL_DURUMU] NVARCHAR(50) NULL;
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = 'TETKIK_PARAMETRE' AND COLUMN_NAME = 'AKTIF')
    ALTER TABLE [Lbys].[TETKIK_PARAMETRE] DROP COLUMN [AKTIF];
GO

-- =============================================================================
-- End of Script
-- =============================================================================