-- NULL değerleri 'BELİRTİLMEDİ' olarak güncelleme scripti
-- Tarih: 2026-01-10
-- Açıklama: Eksik referans kodları olan kolonlardaki NULL değerler 'BELİRTİLMEDİ' olarak güncellenir

USE [TESTDATA]
GO

SET NOCOUNT ON;
DECLARE @sql NVARCHAR(MAX);
DECLARE @table NVARCHAR(128);
DECLARE @column NVARCHAR(128);
DECLARE @updated INT;

-- Dinamik UPDATE prosedürü
CREATE TABLE #UpdateLog (
    TableName NVARCHAR(128),
    ColumnName NVARCHAR(128),
    RowsUpdated INT,
    Status NVARCHAR(50)
);

-- Helper procedure
DECLARE @updates TABLE (ID INT IDENTITY(1,1), TableName NVARCHAR(128), ColumnName NVARCHAR(128));

INSERT INTO @updates (TableName, ColumnName) VALUES
('YATAK', 'YATAK_TURU'),
('YATAK', 'YOGUN_BAKIM_YATAK_SEVIYESI'),
('TIBBI_ORDER_DETAY', 'TIBBI_ORDER_IPTAL_NEDENI'),
('TETKIK_SONUC', 'NUMUNE_RET_NEDENI'),
('TETKIK_SONUC', 'TETKIK_SONUCU_DURUMU'),
('TETKIK_REFERANS_ARALIK', 'TETKIK_CINSIYET'),
('TETKIK_NUMUNE', 'NUMUNE_RET_NEDENI'),
('STOK_KART', 'MALZEME_TIPI'),
('STOK_ISTEK_UYGULAMA', 'ISTEK_IPTAL_NEDENI'),
('STOK_ISTEK_HAREKET', 'ISTENEN_ILAC_JENERIK_KODU'),
('STOK_ISTEK_HAREKET', 'STOK_ISTEK_RET_NEDENI'),
('STOK_HAREKET', 'OLCU_KODU'),
('STOK_EHU_TAKIP', 'EHU_RET_NEDENI'),
('STOK_DURUM', 'OLCU_KODU'),
('STERILIZASYON_YIKAMA', 'YIKAMA_TURU'),
('STERILIZASYON_PAKET_DETAY', 'OLCU_KODU'),
('RISK_SKORLAMA_DETAY', 'RISK_SKORLAMA_ALT_TURU'),
('RISK_SKORLAMA', 'RISK_SKORLAMA_TURU'),
('RECETE_ILAC_ACIKLAMA', 'ILAC_ACIKLAMA_TURU'),
('RECETE', 'RECETE_ALT_TURU'),
('RANDEVU', 'RANDEVU_ALT_TURU'),
('PERSONEL_ODUL_CEZA', 'ODUL_CEZA_TURU'),
('PERSONEL_IZIN', 'IZIN_TURU'),
('PERSONEL_EGITIM', 'PERSONEL_EGITIM_TURU'),
('PERSONEL_EGITIM', 'SERTIFIKA_TIPI'),
('PERSONEL_BAKMAKLA_YUKUMLU', 'YAKINLIK_DERECESI'),
('PERSONEL_BAKMAKLA_YUKUMLU', 'ENGELLILIK_DURUMU'),
('PERSONEL', 'ADRES_TIPI'),
('PERSONEL', 'ADRES_KODU_SEVIYESI'),
('PERSONEL', 'ASKERLIK_DURUMU'),
('PERSONEL', 'KLINIKLER'),
('PERSONEL', 'CALISMA_DURUMU'),
('PERSONEL', 'IS_DURUMU'),
('PERSONEL', 'MEMURIYET_TIPI'),
('PERSONEL', 'ISTEN_AYRILMA_NEDENI'),
('PERSONEL', 'KADRO_UNVAN_KODU'),
('PERSONEL', 'IMZA_UNVAN_KODU'),
('PERSONEL', 'AKADEMIK_UNVAN'),
('PERSONEL', 'KURUMLAR'),
('PERSONEL', 'ENGELLILIK_DURUMU'),
('PATOLOJI', 'PATOLOJI_RAPOR_TURU'),
('PATOLOJI', 'NUMUNENIN_ALINDIGI_DOKUNUN_TEMEL_OZELLIGI'),
('PATOLOJI', 'NUMUNE_ALINMA_SEKLI'),
('PATOLOJI', 'PATOLOJI_PREPARATI_DURUMU'),
('PATOLOJI', 'NUMUNE_ALINMA_YERI'),
('PATOLOJI', 'PATOLOJIK_TANI_MORFOLOJI_KODU'),
('PATOLOJI', 'PATOLOJIK_TANI_YERLESIM_YERI'),
('PATOLOJI', 'SONUC_ICERIK_TURU'),
('OPTIK_RECETE', 'GOZLUK_RECETE_TIPI'),
('OPTIK_RECETE', 'GOZLUK_TURU'),
('OPTIK_RECETE', 'SAG_CAM_TIPI'),
('OPTIK_RECETE', 'SAG_CAM_RENGI'),
('OPTIK_RECETE', 'SOL_CAM_TIPI'),
('OPTIK_RECETE', 'SOL_CAM_RENGI'),
('OPTIK_RECETE', 'TELESKOPIK_GOZLUK_TIPI'),
('OPTIK_RECETE', 'TELESKOPIK_GOZLUK_TURU'),
('OBEZITE_IZLEM', 'MORBIT_OBEZ_HASTA_LENFATIK_ODEM_VARLIGI'),
('NOBETCI_PERSONEL_BILGISI', 'KURUMLAR'),
('NOBETCI_PERSONEL_BILGISI', 'KLINIKLER'),
('MEDULA_TAKIP', 'PROVIZYON_TURU'),
('MEDULA_TAKIP', 'TAKIP_TIPI'),
('MEDULA_TAKIP', 'TEDAVI_TIPI'),
('MEDULA_TAKIP', 'TEDAVI_SEKLI'),
('MADDE_BAGIMLILIGI', 'BILGI_ALINAN_KISI'),
('MADDE_BAGIMLILIGI', 'DANISMA_TEDAVI_HIZMET_ALMA_DURUMU'),
('MADDE_BAGIMLILIGI', 'IKAME_TEDAVISI_GORME_DURUMU'),
('MADDE_BAGIMLILIGI', 'COCUKLARIYLA_YASAM_DURUMU'),
('MADDE_BAGIMLILIGI', 'YASAMINDA_ENJEKSIYON_YOLU_ILE_MADDE_KULLANIM_DURUMU'),
('MADDE_BAGIMLILIGI', 'TEST_YAPILMA_DURUMU'),
('MADDE_BAGIMLILIGI', 'TEDAVI_SONUCU'),
('MADDE_BAGIMLILIGI', 'UYGULANAN_TEDAVI_TURU'),
('MADDE_BAGIMLILIGI', 'KULLANILAN_MADDE'),
('LOHUSA_IZLEM', 'KACINCI_LOHUSA_IZLEM'),
('LOHUSA_IZLEM', 'KURUMLAR'),
('LOHUSA_IZLEM', 'D_VITAMINI_LOJISTIGI_VE_DESTEGI'),
('LOHUSA_IZLEM', 'POSTPARTUM_DEPRESYON'),
('LOHUSA_IZLEM', 'UTERUS_INVOLUSYON'),
('LOHUSA_IZLEM', 'SEYIR_TEHLIKE_ISARETI'),
('LOHUSA_IZLEM', 'KADIN_SAGLIGI_ISLEMLERI'),
('KURUM', 'HASTA_KURUM_TURU'),
('KURUM', 'KURUMLAR'),
('KURUL_ETKEN_MADDE', 'ILAC_PERIYOT_BIRIMI'),
('KURUL_ASKERI', 'DURUM'),
('KURUL_ASKERI', 'ASAL_HASTALIK'),
('KURUL_ASKERI', 'ASAL_HASTALIK_TIPI'),
('KULLANICI', 'PAROLA_SIFRELEME_TURU'),
('KUDUZ_IZLEM', 'PROFILAKSI_TAMAMLANMA_DURUMU'),
('KUDUZ_IZLEM', 'UYGULANAN_KUDUZ_PROFILAKSISI'),
('KLINIK_SEYIR', 'DURUM'),
('KADIN_IZLEM', 'KULLANILAN_AILE_PLANLAMASI_YONTEMI'),
('KADIN_IZLEM', 'BIR_ONCEKI_KULLANILAN_AILE_PLANLAMASI_YONTEM'),
('KADIN_IZLEM', 'AILE_PLANLAMASI_YONTEMI_LOJISTIGI'),
('KADIN_IZLEM', 'KADIN_SAGLIGI_ISLEMLERI'),
('INTIHAR_IZLEM', 'INTIHAR_GIRISIMI_YADA_KRIZ_NEDENLERI'),
('ILAC_UYUM', 'ILAC_UYUMSUZLUK_TURU'),
('ILAC_UYUM', 'BIRINCI_ILAC_BARKODU'),
('ILAC_UYUM', 'BIRINCI_ETKEN_MADDE_KODU'),
('ILAC_UYUM', 'IKINCI_ILAC_BARKODU'),
('ILAC_UYUM', 'IKINCI_ETKEN_MADDE_KODU'),
('ILAC_UYUM', 'BESIN_KODU'),
('ILAC_UYUM', 'RENK_SEVIYE_KODU'),
('HIZMET', 'ISLEM_GRUBU'),
('HIZMET', 'HIZMET_ISLEM_TURU'),
('HIZMET', 'TIBBI_ISLEM_PUAN_BILGISI'),
('HEMSIRE_BAKIM', 'HEMSIRELIK_TANI_KODU'),
('HEMOGLOBINOPATI', 'HEMOGLOBINOPATI_TARAMA_TESTI_SONUCU'),
('HEMOGLOBINOPATI', 'HEMOGLOBINOPATI_TEST_SONUCU_HASTALIK_TURU'),
('HEMOGLOBINOPATI', 'HEMOGLOBINOPATI_TEST_SONUCU_TASIYICILIK_TURU'),
('HASTA_SEVK', 'SEVK_NEDENI'),
('HASTA_SEVK', 'SEVK_SEKLI'),
('HASTA_SEVK', 'SEVK_VASITASI_KODU'),
('HASTA_SEVK', 'SEVK_TEDAVI_TIPI'),
('HASTA_SEANS', 'SEANS_ISLEM_TURU'),
('HASTA_SEANS', 'ANTIHIPERTANSIF_ILAC_DURUMU'),
('HASTA_SEANS', 'ONCEKI_RRT_YONTEMI'),
('HASTA_SEANS', 'HEMODIYALIZE_GECME_NEDENLERI'),
('HASTA_SEANS', 'DAMAR_ERISIM_YOLU'),
('HASTA_SEANS', 'DIYALIZE_GIRME_SIKLIGI'),
('HASTA_SEANS', 'DIYALIZOR_ALANI'),
('HASTA_SEANS', 'DIYALIZOR_TIPI'),
('HASTA_SEANS', 'KAN_AKIM_HIZI'),
('HASTA_SEANS', 'AGIRLIK_OLCUM_ZAMANI'),
('HASTA_SEANS', 'KULLANILAN_DIYALIZ_TEDAVISI'),
('HASTA_SEANS', 'PERITONEAL_GECIRGENLIK_DURUMU'),
('HASTA_SEANS', 'PERITON_KACINCI_KATETER'),
('HASTA_SEANS', 'PERITON_KATETER_TIPI'),
('HASTA_SEANS', 'PERITON_KATETER_YONTEMI'),
('HASTA_SEANS', 'PERITON_TUNEL_YONU'),
('HASTA_SEANS', 'SINEKALSET'),
('HASTA_SEANS', 'TEDAVININ_SEYRI'),
('HASTA_SEANS', 'AKTIF_VITAMIN_D_KULLANIMI'),
('HASTA_SEANS', 'ANEMI_TEDAVISI_YONTEMI'),
('HASTA_SEANS', 'FOSFOR_BAGLAYICI_AJAN'),
('HASTA_SEANS', 'PERITON_KOMPLIKASYON'),
('HASTA_MALZEME', 'HIZMET_FATURA_DURUMU'),
('HASTA_ILETISIM', 'ADRES_TIPI'),
('HASTA_ILETISIM', 'ADRES_KODU_SEVIYESI'),
('HASTA_ILETISIM', 'BUCAK_KODU'),
('HASTA_ILETISIM', 'KOY_KODU'),
('HASTA_ILETISIM', 'MAHALLE_KODU'),
('HASTA_HIZMET', 'HASTA_HIZMET_DURUMU'),
('HASTA_HIZMET', 'HIZMET_FATURA_DURUMU'),
('HASTA_HIZMET', 'TIBBI_ISLEM_PUAN_BILGISI'),
('HASTA_DIS', 'DIS_ISLEM_TURU'),
('HASTA_DIS', 'MEVCUT_DIS_DURUMU'),
('HASTA_DIS', 'DIS_KODU'),
('HASTA_DIS', 'CENE_BOLGESI'),
('HASTA_BASVURU', 'MUAYENE_ONCELIK_SIRASI'),
('HASTA_BASVURU', 'KURUMLAR'),
('HASTA_BASVURU', 'OLAY_AFET_KODU'),
('HASTA_BASVURU', 'HAYATI_TEHLIKE_DURUMU'),
('HASTA_BASVURU', 'KABUL_SEKLI'),
('HASTA_BASVURU', 'SOSYAL_GUVENCE_DURUMU'),
('HASTA_BASVURU', 'VAKA_TURU'),
('HASTA_BASVURU', 'ADLI_VAKA_GELIS_SEKLI'),
('HASTA_BASVURU', 'ARAC_TURU'),
('HASTA_BASVURU', 'TRIAJ_KODU'),
('HASTA_BASVURU', 'YATIS_BILGISI'),
('HASTA_BASVURU', 'BASVURU_DURUMU'),
('HASTA_BASVURU', 'MUAYENE_TURU'),
('HASTA_BASVURU', 'YABANCI_HASTA_TURU'),
('HASTA_BASVURU', 'GENCLIK_SAGLIGI_ISLEMLERI'),
('HASTA_ARSIV', 'DEFTER_TURU'),
('HASTA', 'HASTA_TIPI'),
('HASTA', 'MESLEK'),
('HASTA', 'MUAYENE_ONCELIK_SIRASI'),
('HASTA', 'ENGELLILIK_DURUMU'),
('GEBE_IZLEM', 'D_VITAMINI_LOJISTIGI_VE_DESTEGI'),
('GEBE_IZLEM', 'BEBEGIN_COCUGUN_BEYIN_GELISIMINI_ETKILEYEBILECEK_RISKLER'),
('GEBE_IZLEM', 'BEBEGIN_COCUGUN_PSIKOLOJIK_GELISIMINDEKI_RISKLERE_YONELIK_EGITIMLER'),
('GEBE_IZLEM', 'BEBEGIN_COCUGUN_RISK_FAKTORLERINE_YAPILAN_MUDAHALE'),
('GEBE_IZLEM', 'BEBEK_COCUKTA_SIK_IZLEME_ALINAN_RISK_ALTINDAKI_OLGUNUN_TAKIBI'),
('EVDE_SAGLIK_IZLEM', 'AGRI'),
('EVDE_SAGLIK_IZLEM', 'AYDINLATMA'),
('EVDE_SAGLIK_IZLEM', 'BAKIM_VE_DESTEK_IHTIYACI'),
('EVDE_SAGLIK_IZLEM', 'BASI_DEGERLENDIRMESI'),
('EVDE_SAGLIK_IZLEM', 'BASVURU_TURU'),
('EVDE_SAGLIK_IZLEM', 'BESLENME'),
('EVDE_SAGLIK_IZLEM', 'EV_HIJYENI'),
('EVDE_SAGLIK_IZLEM', 'GUVENLIK'),
('EVDE_SAGLIK_IZLEM', 'ISINMA'),
('EVDE_SAGLIK_IZLEM', 'KISISEL_BAKIM'),
('EVDE_SAGLIK_IZLEM', 'KISISEL_HIJYEN'),
('EVDE_SAGLIK_IZLEM', 'KONUT_TIPI'),
('EVDE_SAGLIK_IZLEM', 'KULLANILAN_HELA_TIPI'),
('EVDE_SAGLIK_IZLEM', 'YATAGA_BAGIMLILIK'),
('EVDE_SAGLIK_IZLEM', 'KULLANDIGI_YARDIMCI_ARACLAR'),
('EVDE_SAGLIK_IZLEM', 'PSIKOLOJIK_DURUM_DEGERLENDIRME'),
('EVDE_SAGLIK_IZLEM', 'EVDE_SAGLIK_HIZMETININ_SONLANDIRILMASI'),
('EVDE_SAGLIK_IZLEM', 'EVDE_SAGLIK_HIZMETLERI_HASTA_NAKLI'),
('EVDE_SAGLIK_IZLEM', 'BIR_SONRAKI_HIZMET_IHTIYACI'),
('EVDE_SAGLIK_IZLEM', 'VERILEN_EGITIMLER'),
('EK_ODEME_DETAY', 'KLINIKLER'),
('DOGUM_DETAY', 'PROGNOZ_BILGISI'),
('DOGUM_DETAY', 'SURMATURE_BILGISI'),
('DOGUM_DETAY', 'K_VITAMINI_UYGULANMA_DURUMU'),
('DOGUM_DETAY', 'BEBEGIN_HEPATIT_ASI_DURUMU'),
('DOGUM_DETAY', 'YENIDOGAN_ISITME_TARAMA_DURUMU'),
('DOGUM_DETAY', 'SEZARYEN_ENDIKASYONLAR'),
('DOGUM_DETAY', 'ROBSON_GRUP'),
('DISPROTEZ_DETAY', 'DISPROTEZ_IS_TURU_ASAMA_KODU'),
('DISPROTEZ_DETAY', 'ASAMA_RPT_SEBEBI'),
('DIS_TAAHHUT_DETAY', 'DIS_KODU'),
('DIS_TAAHHUT_DETAY', 'CENE_KODU'),
('COCUK_DIYABET', 'DIYABET_ESLIK_EDEN_HASTALIK'),
('COCUK_DIYABET', 'DIYET_TEDAVISI_TIBBI_BESLENME_TEDAVISI'),
('CIHAZ', 'CIHAZ_GRUBU'),
('BIRIM', 'KLINIKLER'),
('BINA', 'KURUMLAR'),
('BILDIRIMI_ZORUNLU', 'INTIHAR_GIRISIMI_YADA_KRIZ_NEDENLERI'),
('BEBEK_COCUK_IZLEM', 'D_VITAMINI_LOJISTIGI_VE_DESTEGI'),
('BEBEK_COCUK_IZLEM', 'KURUMLAR'),
('BEBEK_COCUK_IZLEM', 'GELISIM_TABLOSU_BILGILERININ_SORGULANMASI'),
('BEBEK_COCUK_IZLEM', 'BEBEGIN_COCUGUN_BEYIN_GELISIMINI_ETKILEYEBILECEK_RISKLER'),
('BEBEK_COCUK_IZLEM', 'BEBEGIN_COCUGUN_PSIKOLOJIK_GELISIMINDEKI_RISKLERE_YONELIK_EGITIMLER'),
('BEBEK_COCUK_IZLEM', 'BEBEGIN_COCUGUN_RISK_FAKTORLERINE_YAPILAN_MUDAHALE'),
('ASI_BILGISI', 'ASI_KODU'),
('ASI_BILGISI', 'ASININ_DOZU'),
('ASI_BILGISI', 'ASININ_UYGULAMA_SEKLI'),
('ASI_BILGISI', 'ASI_UYGULAMA_YERI');

DECLARE @id INT = 1;
DECLARE @maxId INT = (SELECT MAX(ID) FROM @updates);

WHILE @id <= @maxId
BEGIN
    SELECT @table = TableName, @column = ColumnName FROM @updates WHERE ID = @id;

    -- Kolon var mı kontrol et
    IF EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'Lbys'
        AND TABLE_NAME = @table
        AND COLUMN_NAME = @column
    )
    BEGIN
        SET @sql = N'UPDATE [Lbys].[' + @table + N'] SET [' + @column + N'] = N''BELİRTİLMEDİ'' WHERE [' + @column + N'] IS NULL';

        BEGIN TRY
            EXEC sp_executesql @sql;
            SET @updated = @@ROWCOUNT;
            INSERT INTO #UpdateLog VALUES (@table, @column, @updated, 'SUCCESS');
        END TRY
        BEGIN CATCH
            INSERT INTO #UpdateLog VALUES (@table, @column, 0, 'ERROR: ' + ERROR_MESSAGE());
        END CATCH
    END
    ELSE
    BEGIN
        INSERT INTO #UpdateLog VALUES (@table, @column, 0, 'COLUMN_NOT_FOUND');
    END

    SET @id = @id + 1;
END

-- Sonuçları göster
SELECT * FROM #UpdateLog ORDER BY Status DESC, TableName, ColumnName;

-- Özet
SELECT
    Status,
    COUNT(*) as Count,
    SUM(RowsUpdated) as TotalRowsUpdated
FROM #UpdateLog
GROUP BY Status;

DROP TABLE #UpdateLog;

PRINT 'İşlem tamamlandı.';
GO

-- YATAK
UPDATE [Lbys].[YATAK] SET YATAK_TURU = 'BELİRTİLMEDİ' WHERE YATAK_TURU IS NULL;
UPDATE [Lbys].[YATAK] SET YOGUN_BAKIM_YATAK_SEVIYESI = 'BELİRTİLMEDİ' WHERE YOGUN_BAKIM_YATAK_SEVIYESI IS NULL;

-- TIBBI_ORDER_DETAY
UPDATE [Lbys].[TIBBI_ORDER_DETAY] SET TIBBI_ORDER_IPTAL_NEDENI = 'BELİRTİLMEDİ' WHERE TIBBI_ORDER_IPTAL_NEDENI IS NULL;

-- TETKIK_SONUC
UPDATE [Lbys].[TETKIK_SONUC] SET NUMUNE_RET_NEDENI = 'BELİRTİLMEDİ' WHERE NUMUNE_RET_NEDENI IS NULL;
UPDATE [Lbys].[TETKIK_SONUC] SET TETKIK_SONUCU_DURUMU = 'BELİRTİLMEDİ' WHERE TETKIK_SONUCU_DURUMU IS NULL;

-- TETKIK_REFERANS_ARALIK
UPDATE [Lbys].[TETKIK_REFERANS_ARALIK] SET TETKIK_CINSIYET = 'BELİRTİLMEDİ' WHERE TETKIK_CINSIYET IS NULL;

-- TETKIK_NUMUNE
UPDATE [Lbys].[TETKIK_NUMUNE] SET NUMUNE_RET_NEDENI = 'BELİRTİLMEDİ' WHERE NUMUNE_RET_NEDENI IS NULL;

-- STOK_KART
UPDATE [Lbys].[STOK_KART] SET MALZEME_TIPI = 'BELİRTİLMEDİ' WHERE MALZEME_TIPI IS NULL;

-- STOK_ISTEK_UYGULAMA
UPDATE [Lbys].[STOK_ISTEK_UYGULAMA] SET ISTEK_IPTAL_NEDENI = 'BELİRTİLMEDİ' WHERE ISTEK_IPTAL_NEDENI IS NULL;

-- STOK_ISTEK_HAREKET
UPDATE [Lbys].[STOK_ISTEK_HAREKET] SET ISTENEN_ILAC_JENERIK_KODU = 'BELİRTİLMEDİ' WHERE ISTENEN_ILAC_JENERIK_KODU IS NULL;
UPDATE [Lbys].[STOK_ISTEK_HAREKET] SET STOK_ISTEK_RET_NEDENI = 'BELİRTİLMEDİ' WHERE STOK_ISTEK_RET_NEDENI IS NULL;

-- STOK_HAREKET
UPDATE [Lbys].[STOK_HAREKET] SET OLCU_KODU = 'BELİRTİLMEDİ' WHERE OLCU_KODU IS NULL;

-- STOK_EHU_TAKIP
UPDATE [Lbys].[STOK_EHU_TAKIP] SET EHU_RET_NEDENI = 'BELİRTİLMEDİ' WHERE EHU_RET_NEDENI IS NULL;

-- STOK_DURUM
UPDATE [Lbys].[STOK_DURUM] SET OLCU_KODU = 'BELİRTİLMEDİ' WHERE OLCU_KODU IS NULL;

-- STERILIZASYON_YIKAMA
UPDATE [Lbys].[STERILIZASYON_YIKAMA] SET YIKAMA_TURU = 'BELİRTİLMEDİ' WHERE YIKAMA_TURU IS NULL;

-- STERILIZASYON_PAKET_DETAY
UPDATE [Lbys].[STERILIZASYON_PAKET_DETAY] SET OLCU_KODU = 'BELİRTİLMEDİ' WHERE OLCU_KODU IS NULL;

-- RISK_SKORLAMA_DETAY
UPDATE [Lbys].[RISK_SKORLAMA_DETAY] SET RISK_SKORLAMA_ALT_TURU = 'BELİRTİLMEDİ' WHERE RISK_SKORLAMA_ALT_TURU IS NULL;

-- RISK_SKORLAMA
UPDATE [Lbys].[RISK_SKORLAMA] SET RISK_SKORLAMA_TURU = 'BELİRTİLMEDİ' WHERE RISK_SKORLAMA_TURU IS NULL;

-- RECETE_ILAC_ACIKLAMA
UPDATE [Lbys].[RECETE_ILAC_ACIKLAMA] SET ILAC_ACIKLAMA_TURU = 'BELİRTİLMEDİ' WHERE ILAC_ACIKLAMA_TURU IS NULL;

-- RECETE
UPDATE [Lbys].[RECETE] SET RECETE_ALT_TURU = 'BELİRTİLMEDİ' WHERE RECETE_ALT_TURU IS NULL;

-- RANDEVU
UPDATE [Lbys].[RANDEVU] SET RANDEVU_ALT_TURU = 'BELİRTİLMEDİ' WHERE RANDEVU_ALT_TURU IS NULL;

-- PERSONEL_ODUL_CEZA
UPDATE [Lbys].[PERSONEL_ODUL_CEZA] SET ODUL_CEZA_TURU = 'BELİRTİLMEDİ' WHERE ODUL_CEZA_TURU IS NULL;

-- PERSONEL_IZIN
UPDATE [Lbys].[PERSONEL_IZIN] SET IZIN_TURU = 'BELİRTİLMEDİ' WHERE IZIN_TURU IS NULL;

-- PERSONEL_EGITIM
UPDATE [Lbys].[PERSONEL_EGITIM] SET PERSONEL_EGITIM_TURU = 'BELİRTİLMEDİ' WHERE PERSONEL_EGITIM_TURU IS NULL;
UPDATE [Lbys].[PERSONEL_EGITIM] SET SERTIFIKA_TIPI = 'BELİRTİLMEDİ' WHERE SERTIFIKA_TIPI IS NULL;

-- PERSONEL_BAKMAKLA_YUKUMLU
UPDATE [Lbys].[PERSONEL_BAKMAKLA_YUKUMLU] SET YAKINLIK_DERECESI = 'BELİRTİLMEDİ' WHERE YAKINLIK_DERECESI IS NULL;
UPDATE [Lbys].[PERSONEL_BAKMAKLA_YUKUMLU] SET ENGELLILIK_DURUMU = 'BELİRTİLMEDİ' WHERE ENGELLILIK_DURUMU IS NULL;

-- PERSONEL
UPDATE [Lbys].[PERSONEL] SET ADRES_TIPI = 'BELİRTİLMEDİ' WHERE ADRES_TIPI IS NULL;
UPDATE [Lbys].[PERSONEL] SET ADRES_KODU_SEVIYESI = 'BELİRTİLMEDİ' WHERE ADRES_KODU_SEVIYESI IS NULL;
UPDATE [Lbys].[PERSONEL] SET ASKERLIK_DURUMU = 'BELİRTİLMEDİ' WHERE ASKERLIK_DURUMU IS NULL;
UPDATE [Lbys].[PERSONEL] SET KLINIKLER = 'BELİRTİLMEDİ' WHERE KLINIKLER IS NULL;
UPDATE [Lbys].[PERSONEL] SET CALISMA_DURUMU = 'BELİRTİLMEDİ' WHERE CALISMA_DURUMU IS NULL;
UPDATE [Lbys].[PERSONEL] SET IS_DURUMU = 'BELİRTİLMEDİ' WHERE IS_DURUMU IS NULL;
UPDATE [Lbys].[PERSONEL] SET MEMURIYET_TIPI = 'BELİRTİLMEDİ' WHERE MEMURIYET_TIPI IS NULL;
UPDATE [Lbys].[PERSONEL] SET ISTEN_AYRILMA_NEDENI = 'BELİRTİLMEDİ' WHERE ISTEN_AYRILMA_NEDENI IS NULL;
UPDATE [Lbys].[PERSONEL] SET KADRO_UNVAN_KODU = 'BELİRTİLMEDİ' WHERE KADRO_UNVAN_KODU IS NULL;
UPDATE [Lbys].[PERSONEL] SET IMZA_UNVAN_KODU = 'BELİRTİLMEDİ' WHERE IMZA_UNVAN_KODU IS NULL;
UPDATE [Lbys].[PERSONEL] SET AKADEMIK_UNVAN = 'BELİRTİLMEDİ' WHERE AKADEMIK_UNVAN IS NULL;
UPDATE [Lbys].[PERSONEL] SET KURUMLAR = 'BELİRTİLMEDİ' WHERE KURUMLAR IS NULL;
UPDATE [Lbys].[PERSONEL] SET ENGELLILIK_DURUMU = 'BELİRTİLMEDİ' WHERE ENGELLILIK_DURUMU IS NULL;

-- PATOLOJI
UPDATE [Lbys].[PATOLOJI] SET PATOLOJI_RAPOR_TURU = 'BELİRTİLMEDİ' WHERE PATOLOJI_RAPOR_TURU IS NULL;
UPDATE [Lbys].[PATOLOJI] SET NUMUNENIN_ALINDIGI_DOKUNUN_TEMEL_OZELLIGI = 'BELİRTİLMEDİ' WHERE NUMUNENIN_ALINDIGI_DOKUNUN_TEMEL_OZELLIGI IS NULL;
UPDATE [Lbys].[PATOLOJI] SET NUMUNE_ALINMA_SEKLI = 'BELİRTİLMEDİ' WHERE NUMUNE_ALINMA_SEKLI IS NULL;
UPDATE [Lbys].[PATOLOJI] SET PATOLOJI_PREPARATI_DURUMU = 'BELİRTİLMEDİ' WHERE PATOLOJI_PREPARATI_DURUMU IS NULL;
UPDATE [Lbys].[PATOLOJI] SET NUMUNE_ALINMA_YERI = 'BELİRTİLMEDİ' WHERE NUMUNE_ALINMA_YERI IS NULL;
UPDATE [Lbys].[PATOLOJI] SET PATOLOJIK_TANI_MORFOLOJI_KODU = 'BELİRTİLMEDİ' WHERE PATOLOJIK_TANI_MORFOLOJI_KODU IS NULL;
UPDATE [Lbys].[PATOLOJI] SET PATOLOJIK_TANI_YERLESIM_YERI = 'BELİRTİLMEDİ' WHERE PATOLOJIK_TANI_YERLESIM_YERI IS NULL;
UPDATE [Lbys].[PATOLOJI] SET SONUC_ICERIK_TURU = 'BELİRTİLMEDİ' WHERE SONUC_ICERIK_TURU IS NULL;

-- OPTIK_RECETE
UPDATE [Lbys].[OPTIK_RECETE] SET GOZLUK_RECETE_TIPI = 'BELİRTİLMEDİ' WHERE GOZLUK_RECETE_TIPI IS NULL;
UPDATE [Lbys].[OPTIK_RECETE] SET GOZLUK_TURU = 'BELİRTİLMEDİ' WHERE GOZLUK_TURU IS NULL;
UPDATE [Lbys].[OPTIK_RECETE] SET SAG_CAM_TIPI = 'BELİRTİLMEDİ' WHERE SAG_CAM_TIPI IS NULL;
UPDATE [Lbys].[OPTIK_RECETE] SET SAG_CAM_RENGI = 'BELİRTİLMEDİ' WHERE SAG_CAM_RENGI IS NULL;
UPDATE [Lbys].[OPTIK_RECETE] SET SOL_CAM_TIPI = 'BELİRTİLMEDİ' WHERE SOL_CAM_TIPI IS NULL;
UPDATE [Lbys].[OPTIK_RECETE] SET SOL_CAM_RENGI = 'BELİRTİLMEDİ' WHERE SOL_CAM_RENGI IS NULL;
UPDATE [Lbys].[OPTIK_RECETE] SET TELESKOPIK_GOZLUK_TIPI = 'BELİRTİLMEDİ' WHERE TELESKOPIK_GOZLUK_TIPI IS NULL;
UPDATE [Lbys].[OPTIK_RECETE] SET TELESKOPIK_GOZLUK_TURU = 'BELİRTİLMEDİ' WHERE TELESKOPIK_GOZLUK_TURU IS NULL;

-- OBEZITE_IZLEM
UPDATE [Lbys].[OBEZITE_IZLEM] SET MORBIT_OBEZ_HASTA_LENFATIK_ODEM_VARLIGI = 'BELİRTİLMEDİ' WHERE MORBIT_OBEZ_HASTA_LENFATIK_ODEM_VARLIGI IS NULL;

-- NOBETCI_PERSONEL_BILGISI
UPDATE [Lbys].[NOBETCI_PERSONEL_BILGISI] SET KURUMLAR = 'BELİRTİLMEDİ' WHERE KURUMLAR IS NULL;
UPDATE [Lbys].[NOBETCI_PERSONEL_BILGISI] SET KLINIKLER = 'BELİRTİLMEDİ' WHERE KLINIKLER IS NULL;

-- MEDULA_TAKIP
UPDATE [Lbys].[MEDULA_TAKIP] SET PROVIZYON_TURU = 'BELİRTİLMEDİ' WHERE PROVIZYON_TURU IS NULL;
UPDATE [Lbys].[MEDULA_TAKIP] SET TAKIP_TIPI = 'BELİRTİLMEDİ' WHERE TAKIP_TIPI IS NULL;
UPDATE [Lbys].[MEDULA_TAKIP] SET TEDAVI_TIPI = 'BELİRTİLMEDİ' WHERE TEDAVI_TIPI IS NULL;
UPDATE [Lbys].[MEDULA_TAKIP] SET TEDAVI_SEKLI = 'BELİRTİLMEDİ' WHERE TEDAVI_SEKLI IS NULL;

-- MADDE_BAGIMLILIGI
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET BILGI_ALINAN_KISI = 'BELİRTİLMEDİ' WHERE BILGI_ALINAN_KISI IS NULL;
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET DANISMA_TEDAVI_HIZMET_ALMA_DURUMU = 'BELİRTİLMEDİ' WHERE DANISMA_TEDAVI_HIZMET_ALMA_DURUMU IS NULL;
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET IKAME_TEDAVISI_GORME_DURUMU = 'BELİRTİLMEDİ' WHERE IKAME_TEDAVISI_GORME_DURUMU IS NULL;
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET COCUKLARIYLA_YASAM_DURUMU = 'BELİRTİLMEDİ' WHERE COCUKLARIYLA_YASAM_DURUMU IS NULL;
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET YASAMINDA_ENJEKSIYON_YOLU_ILE_MADDE_KULLANIM_DURUMU = 'BELİRTİLMEDİ' WHERE YASAMINDA_ENJEKSIYON_YOLU_ILE_MADDE_KULLANIM_DURUMU IS NULL;
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET TEST_YAPILMA_DURUMU = 'BELİRTİLMEDİ' WHERE TEST_YAPILMA_DURUMU IS NULL;
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET TEDAVI_SONUCU = 'BELİRTİLMEDİ' WHERE TEDAVI_SONUCU IS NULL;
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET UYGULANAN_TEDAVI_TURU = 'BELİRTİLMEDİ' WHERE UYGULANAN_TEDAVI_TURU IS NULL;
UPDATE [Lbys].[MADDE_BAGIMLILIGI] SET KULLANILAN_MADDE = 'BELİRTİLMEDİ' WHERE KULLANILAN_MADDE IS NULL;

-- LOHUSA_IZLEM
UPDATE [Lbys].[LOHUSA_IZLEM] SET KACINCI_LOHUSA_IZLEM = 'BELİRTİLMEDİ' WHERE KACINCI_LOHUSA_IZLEM IS NULL;
UPDATE [Lbys].[LOHUSA_IZLEM] SET KURUMLAR = 'BELİRTİLMEDİ' WHERE KURUMLAR IS NULL;
UPDATE [Lbys].[LOHUSA_IZLEM] SET D_VITAMINI_LOJISTIGI_VE_DESTEGI = 'BELİRTİLMEDİ' WHERE D_VITAMINI_LOJISTIGI_VE_DESTEGI IS NULL;
UPDATE [Lbys].[LOHUSA_IZLEM] SET POSTPARTUM_DEPRESYON = 'BELİRTİLMEDİ' WHERE POSTPARTUM_DEPRESYON IS NULL;
UPDATE [Lbys].[LOHUSA_IZLEM] SET UTERUS_INVOLUSYON = 'BELİRTİLMEDİ' WHERE UTERUS_INVOLUSYON IS NULL;
UPDATE [Lbys].[LOHUSA_IZLEM] SET SEYIR_TEHLIKE_ISARETI = 'BELİRTİLMEDİ' WHERE SEYIR_TEHLIKE_ISARETI IS NULL;
UPDATE [Lbys].[LOHUSA_IZLEM] SET KADIN_SAGLIGI_ISLEMLERI = 'BELİRTİLMEDİ' WHERE KADIN_SAGLIGI_ISLEMLERI IS NULL;

-- KURUM
UPDATE [Lbys].[KURUM] SET HASTA_KURUM_TURU = 'BELİRTİLMEDİ' WHERE HASTA_KURUM_TURU IS NULL;
UPDATE [Lbys].[KURUM] SET KURUMLAR = 'BELİRTİLMEDİ' WHERE KURUMLAR IS NULL;

-- KURUL_ETKEN_MADDE
UPDATE [Lbys].[KURUL_ETKEN_MADDE] SET ILAC_PERIYOT_BIRIMI = 'BELİRTİLMEDİ' WHERE ILAC_PERIYOT_BIRIMI IS NULL;

-- KURUL_ASKERI
UPDATE [Lbys].[KURUL_ASKERI] SET DURUM = 'BELİRTİLMEDİ' WHERE DURUM IS NULL;
UPDATE [Lbys].[KURUL_ASKERI] SET ASAL_HASTALIK = 'BELİRTİLMEDİ' WHERE ASAL_HASTALIK IS NULL;
UPDATE [Lbys].[KURUL_ASKERI] SET ASAL_HASTALIK_TIPI = 'BELİRTİLMEDİ' WHERE ASAL_HASTALIK_TIPI IS NULL;

-- KULLANICI
UPDATE [Lbys].[KULLANICI] SET PAROLA_SIFRELEME_TURU = 'BELİRTİLMEDİ' WHERE PAROLA_SIFRELEME_TURU IS NULL;

-- KUDUZ_IZLEM
UPDATE [Lbys].[KUDUZ_IZLEM] SET PROFILAKSI_TAMAMLANMA_DURUMU = 'BELİRTİLMEDİ' WHERE PROFILAKSI_TAMAMLANMA_DURUMU IS NULL;
UPDATE [Lbys].[KUDUZ_IZLEM] SET UYGULANAN_KUDUZ_PROFILAKSISI = 'BELİRTİLMEDİ' WHERE UYGULANAN_KUDUZ_PROFILAKSISI IS NULL;

-- KLINIK_SEYIR
UPDATE [Lbys].[KLINIK_SEYIR] SET DURUM = 'BELİRTİLMEDİ' WHERE DURUM IS NULL;

-- KADIN_IZLEM
UPDATE [Lbys].[KADIN_IZLEM] SET KULLANILAN_AILE_PLANLAMASI_YONTEMI = 'BELİRTİLMEDİ' WHERE KULLANILAN_AILE_PLANLAMASI_YONTEMI IS NULL;
UPDATE [Lbys].[KADIN_IZLEM] SET BIR_ONCEKI_KULLANILAN_AILE_PLANLAMASI_YONTEM = 'BELİRTİLMEDİ' WHERE BIR_ONCEKI_KULLANILAN_AILE_PLANLAMASI_YONTEM IS NULL;
UPDATE [Lbys].[KADIN_IZLEM] SET AILE_PLANLAMASI_YONTEMI_LOJISTIGI = 'BELİRTİLMEDİ' WHERE AILE_PLANLAMASI_YONTEMI_LOJISTIGI IS NULL;
UPDATE [Lbys].[KADIN_IZLEM] SET KADIN_SAGLIGI_ISLEMLERI = 'BELİRTİLMEDİ' WHERE KADIN_SAGLIGI_ISLEMLERI IS NULL;

-- INTIHAR_IZLEM
UPDATE [Lbys].[INTIHAR_IZLEM] SET INTIHAR_GIRISIMI_YADA_KRIZ_NEDENLERI = 'BELİRTİLMEDİ' WHERE INTIHAR_GIRISIMI_YADA_KRIZ_NEDENLERI IS NULL;

-- ILAC_UYUM
UPDATE [Lbys].[ILAC_UYUM] SET ILAC_UYUMSUZLUK_TURU = 'BELİRTİLMEDİ' WHERE ILAC_UYUMSUZLUK_TURU IS NULL;
UPDATE [Lbys].[ILAC_UYUM] SET BIRINCI_ILAC_BARKODU = 'BELİRTİLMEDİ' WHERE BIRINCI_ILAC_BARKODU IS NULL;
UPDATE [Lbys].[ILAC_UYUM] SET BIRINCI_ETKEN_MADDE_KODU = 'BELİRTİLMEDİ' WHERE BIRINCI_ETKEN_MADDE_KODU IS NULL;
UPDATE [Lbys].[ILAC_UYUM] SET IKINCI_ILAC_BARKODU = 'BELİRTİLMEDİ' WHERE IKINCI_ILAC_BARKODU IS NULL;
UPDATE [Lbys].[ILAC_UYUM] SET IKINCI_ETKEN_MADDE_KODU = 'BELİRTİLMEDİ' WHERE IKINCI_ETKEN_MADDE_KODU IS NULL;
UPDATE [Lbys].[ILAC_UYUM] SET BESIN_KODU = 'BELİRTİLMEDİ' WHERE BESIN_KODU IS NULL;
UPDATE [Lbys].[ILAC_UYUM] SET RENK_SEVIYE_KODU = 'BELİRTİLMEDİ' WHERE RENK_SEVIYE_KODU IS NULL;

-- HIZMET
UPDATE [Lbys].[HIZMET] SET ISLEM_GRUBU = 'BELİRTİLMEDİ' WHERE ISLEM_GRUBU IS NULL;
UPDATE [Lbys].[HIZMET] SET HIZMET_ISLEM_TURU = 'BELİRTİLMEDİ' WHERE HIZMET_ISLEM_TURU IS NULL;
UPDATE [Lbys].[HIZMET] SET TIBBI_ISLEM_PUAN_BILGISI = 'BELİRTİLMEDİ' WHERE TIBBI_ISLEM_PUAN_BILGISI IS NULL;

-- HEMSIRE_BAKIM
UPDATE [Lbys].[HEMSIRE_BAKIM] SET HEMSIRELIK_TANI_KODU = 'BELİRTİLMEDİ' WHERE HEMSIRELIK_TANI_KODU IS NULL;

-- HEMOGLOBINOPATI
UPDATE [Lbys].[HEMOGLOBINOPATI] SET HEMOGLOBINOPATI_TARAMA_TESTI_SONUCU = 'BELİRTİLMEDİ' WHERE HEMOGLOBINOPATI_TARAMA_TESTI_SONUCU IS NULL;
UPDATE [Lbys].[HEMOGLOBINOPATI] SET HEMOGLOBINOPATI_TEST_SONUCU_HASTALIK_TURU = 'BELİRTİLMEDİ' WHERE HEMOGLOBINOPATI_TEST_SONUCU_HASTALIK_TURU IS NULL;
UPDATE [Lbys].[HEMOGLOBINOPATI] SET HEMOGLOBINOPATI_TEST_SONUCU_TASIYICILIK_TURU = 'BELİRTİLMEDİ' WHERE HEMOGLOBINOPATI_TEST_SONUCU_TASIYICILIK_TURU IS NULL;

-- HASTA_SEVK
UPDATE [Lbys].[HASTA_SEVK] SET SEVK_NEDENI = 'BELİRTİLMEDİ' WHERE SEVK_NEDENI IS NULL;
UPDATE [Lbys].[HASTA_SEVK] SET SEVK_SEKLI = 'BELİRTİLMEDİ' WHERE SEVK_SEKLI IS NULL;
UPDATE [Lbys].[HASTA_SEVK] SET SEVK_VASITASI_KODU = 'BELİRTİLMEDİ' WHERE SEVK_VASITASI_KODU IS NULL;
UPDATE [Lbys].[HASTA_SEVK] SET SEVK_TEDAVI_TIPI = 'BELİRTİLMEDİ' WHERE SEVK_TEDAVI_TIPI IS NULL;

-- HASTA_SEANS
UPDATE [Lbys].[HASTA_SEANS] SET SEANS_ISLEM_TURU = 'BELİRTİLMEDİ' WHERE SEANS_ISLEM_TURU IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET ANTIHIPERTANSIF_ILAC_DURUMU = 'BELİRTİLMEDİ' WHERE ANTIHIPERTANSIF_ILAC_DURUMU IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET ONCEKI_RRT_YONTEMI = 'BELİRTİLMEDİ' WHERE ONCEKI_RRT_YONTEMI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET HEMODIYALIZE_GECME_NEDENLERI = 'BELİRTİLMEDİ' WHERE HEMODIYALIZE_GECME_NEDENLERI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET DAMAR_ERISIM_YOLU = 'BELİRTİLMEDİ' WHERE DAMAR_ERISIM_YOLU IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET DIYALIZE_GIRME_SIKLIGI = 'BELİRTİLMEDİ' WHERE DIYALIZE_GIRME_SIKLIGI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET DIYALIZOR_ALANI = 'BELİRTİLMEDİ' WHERE DIYALIZOR_ALANI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET DIYALIZOR_TIPI = 'BELİRTİLMEDİ' WHERE DIYALIZOR_TIPI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET KAN_AKIM_HIZI = 'BELİRTİLMEDİ' WHERE KAN_AKIM_HIZI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET AGIRLIK_OLCUM_ZAMANI = 'BELİRTİLMEDİ' WHERE AGIRLIK_OLCUM_ZAMANI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET KULLANILAN_DIYALIZ_TEDAVISI = 'BELİRTİLMEDİ' WHERE KULLANILAN_DIYALIZ_TEDAVISI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET PERITONEAL_GECIRGENLIK_DURUMU = 'BELİRTİLMEDİ' WHERE PERITONEAL_GECIRGENLIK_DURUMU IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET PERITON_KACINCI_KATETER = 'BELİRTİLMEDİ' WHERE PERITON_KACINCI_KATETER IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET PERITON_KATETER_TIPI = 'BELİRTİLMEDİ' WHERE PERITON_KATETER_TIPI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET PERITON_KATETER_YONTEMI = 'BELİRTİLMEDİ' WHERE PERITON_KATETER_YONTEMI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET PERITON_TUNEL_YONU = 'BELİRTİLMEDİ' WHERE PERITON_TUNEL_YONU IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET SINEKALSET = 'BELİRTİLMEDİ' WHERE SINEKALSET IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET TEDAVININ_SEYRI = 'BELİRTİLMEDİ' WHERE TEDAVININ_SEYRI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET AKTIF_VITAMIN_D_KULLANIMI = 'BELİRTİLMEDİ' WHERE AKTIF_VITAMIN_D_KULLANIMI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET ANEMI_TEDAVISI_YONTEMI = 'BELİRTİLMEDİ' WHERE ANEMI_TEDAVISI_YONTEMI IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET FOSFOR_BAGLAYICI_AJAN = 'BELİRTİLMEDİ' WHERE FOSFOR_BAGLAYICI_AJAN IS NULL;
UPDATE [Lbys].[HASTA_SEANS] SET PERITON_KOMPLIKASYON = 'BELİRTİLMEDİ' WHERE PERITON_KOMPLIKASYON IS NULL;

-- HASTA_MALZEME
UPDATE [Lbys].[HASTA_MALZEME] SET HIZMET_FATURA_DURUMU = 'BELİRTİLMEDİ' WHERE HIZMET_FATURA_DURUMU IS NULL;

-- HASTA_ILETISIM
UPDATE [Lbys].[HASTA_ILETISIM] SET ADRES_TIPI = 'BELİRTİLMEDİ' WHERE ADRES_TIPI IS NULL;
UPDATE [Lbys].[HASTA_ILETISIM] SET ADRES_KODU_SEVIYESI = 'BELİRTİLMEDİ' WHERE ADRES_KODU_SEVIYESI IS NULL;
UPDATE [Lbys].[HASTA_ILETISIM] SET BUCAK_KODU = 'BELİRTİLMEDİ' WHERE BUCAK_KODU IS NULL;
UPDATE [Lbys].[HASTA_ILETISIM] SET KOY_KODU = 'BELİRTİLMEDİ' WHERE KOY_KODU IS NULL;
UPDATE [Lbys].[HASTA_ILETISIM] SET MAHALLE_KODU = 'BELİRTİLMEDİ' WHERE MAHALLE_KODU IS NULL;

-- HASTA_HIZMET
UPDATE [Lbys].[HASTA_HIZMET] SET HASTA_HIZMET_DURUMU = 'BELİRTİLMEDİ' WHERE HASTA_HIZMET_DURUMU IS NULL;
UPDATE [Lbys].[HASTA_HIZMET] SET HIZMET_FATURA_DURUMU = 'BELİRTİLMEDİ' WHERE HIZMET_FATURA_DURUMU IS NULL;
UPDATE [Lbys].[HASTA_HIZMET] SET TIBBI_ISLEM_PUAN_BILGISI = 'BELİRTİLMEDİ' WHERE TIBBI_ISLEM_PUAN_BILGISI IS NULL;

-- HASTA_DIS
UPDATE [Lbys].[HASTA_DIS] SET DIS_ISLEM_TURU = 'BELİRTİLMEDİ' WHERE DIS_ISLEM_TURU IS NULL;
UPDATE [Lbys].[HASTA_DIS] SET MEVCUT_DIS_DURUMU = 'BELİRTİLMEDİ' WHERE MEVCUT_DIS_DURUMU IS NULL;
UPDATE [Lbys].[HASTA_DIS] SET DIS_KODU = 'BELİRTİLMEDİ' WHERE DIS_KODU IS NULL;
UPDATE [Lbys].[HASTA_DIS] SET CENE_BOLGESI = 'BELİRTİLMEDİ' WHERE CENE_BOLGESI IS NULL;

-- HASTA_BASVURU
UPDATE [Lbys].[HASTA_BASVURU] SET MUAYENE_ONCELIK_SIRASI = 'BELİRTİLMEDİ' WHERE MUAYENE_ONCELIK_SIRASI IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET KURUMLAR = 'BELİRTİLMEDİ' WHERE KURUMLAR IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET OLAY_AFET_KODU = 'BELİRTİLMEDİ' WHERE OLAY_AFET_KODU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET HAYATI_TEHLIKE_DURUMU = 'BELİRTİLMEDİ' WHERE HAYATI_TEHLIKE_DURUMU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET KABUL_SEKLI = 'BELİRTİLMEDİ' WHERE KABUL_SEKLI IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET SOSYAL_GUVENCE_DURUMU = 'BELİRTİLMEDİ' WHERE SOSYAL_GUVENCE_DURUMU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET VAKA_TURU = 'BELİRTİLMEDİ' WHERE VAKA_TURU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET ADLI_VAKA_GELIS_SEKLI = 'BELİRTİLMEDİ' WHERE ADLI_VAKA_GELIS_SEKLI IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET ARAC_TURU = 'BELİRTİLMEDİ' WHERE ARAC_TURU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET TRIAJ_KODU = 'BELİRTİLMEDİ' WHERE TRIAJ_KODU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET YATIS_BILGISI = 'BELİRTİLMEDİ' WHERE YATIS_BILGISI IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET BASVURU_DURUMU = 'BELİRTİLMEDİ' WHERE BASVURU_DURUMU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET MUAYENE_TURU = 'BELİRTİLMEDİ' WHERE MUAYENE_TURU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET YABANCI_HASTA_TURU = 'BELİRTİLMEDİ' WHERE YABANCI_HASTA_TURU IS NULL;
UPDATE [Lbys].[HASTA_BASVURU] SET GENCLIK_SAGLIGI_ISLEMLERI = 'BELİRTİLMEDİ' WHERE GENCLIK_SAGLIGI_ISLEMLERI IS NULL;

-- HASTA_ARSIV
UPDATE [Lbys].[HASTA_ARSIV] SET DEFTER_TURU = 'BELİRTİLMEDİ' WHERE DEFTER_TURU IS NULL;

-- HASTA
UPDATE [Lbys].[HASTA] SET HASTA_TIPI = 'BELİRTİLMEDİ' WHERE HASTA_TIPI IS NULL;
UPDATE [Lbys].[HASTA] SET MESLEK = 'BELİRTİLMEDİ' WHERE MESLEK IS NULL;
UPDATE [Lbys].[HASTA] SET MUAYENE_ONCELIK_SIRASI = 'BELİRTİLMEDİ' WHERE MUAYENE_ONCELIK_SIRASI IS NULL;
UPDATE [Lbys].[HASTA] SET ENGELLILIK_DURUMU = 'BELİRTİLMEDİ' WHERE ENGELLILIK_DURUMU IS NULL;

-- GEBE_IZLEM
UPDATE [Lbys].[GEBE_IZLEM] SET D_VITAMINI_LOJISTIGI_VE_DESTEGI = 'BELİRTİLMEDİ' WHERE D_VITAMINI_LOJISTIGI_VE_DESTEGI IS NULL;
UPDATE [Lbys].[GEBE_IZLEM] SET BEBEGIN_COCUGUN_BEYIN_GELISIMINI_ETKILEYEBILECEK_RISKLER = 'BELİRTİLMEDİ' WHERE BEBEGIN_COCUGUN_BEYIN_GELISIMINI_ETKILEYEBILECEK_RISKLER IS NULL;
UPDATE [Lbys].[GEBE_IZLEM] SET BEBEGIN_COCUGUN_PSIKOLOJIK_GELISIMINDEKI_RISKLERE_YONELIK_EGITIMLER = 'BELİRTİLMEDİ' WHERE BEBEGIN_COCUGUN_PSIKOLOJIK_GELISIMINDEKI_RISKLERE_YONELIK_EGITIMLER IS NULL;
UPDATE [Lbys].[GEBE_IZLEM] SET BEBEGIN_COCUGUN_RISK_FAKTORLERINE_YAPILAN_MUDAHALE = 'BELİRTİLMEDİ' WHERE BEBEGIN_COCUGUN_RISK_FAKTORLERINE_YAPILAN_MUDAHALE IS NULL;
UPDATE [Lbys].[GEBE_IZLEM] SET BEBEK_COCUKTA_SIK_IZLEME_ALINAN_RISK_ALTINDAKI_OLGUNUN_TAKIBI = 'BELİRTİLMEDİ' WHERE BEBEK_COCUKTA_SIK_IZLEME_ALINAN_RISK_ALTINDAKI_OLGUNUN_TAKIBI IS NULL;

-- EVDE_SAGLIK_IZLEM
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET AGRI = 'BELİRTİLMEDİ' WHERE AGRI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET AYDINLATMA = 'BELİRTİLMEDİ' WHERE AYDINLATMA IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET BAKIM_VE_DESTEK_IHTIYACI = 'BELİRTİLMEDİ' WHERE BAKIM_VE_DESTEK_IHTIYACI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET BASI_DEGERLENDIRMESI = 'BELİRTİLMEDİ' WHERE BASI_DEGERLENDIRMESI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET BASVURU_TURU = 'BELİRTİLMEDİ' WHERE BASVURU_TURU IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET BESLENME = 'BELİRTİLMEDİ' WHERE BESLENME IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET EV_HIJYENI = 'BELİRTİLMEDİ' WHERE EV_HIJYENI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET GUVENLIK = 'BELİRTİLMEDİ' WHERE GUVENLIK IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET ISINMA = 'BELİRTİLMEDİ' WHERE ISINMA IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET KISISEL_BAKIM = 'BELİRTİLMEDİ' WHERE KISISEL_BAKIM IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET KISISEL_HIJYEN = 'BELİRTİLMEDİ' WHERE KISISEL_HIJYEN IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET KONUT_TIPI = 'BELİRTİLMEDİ' WHERE KONUT_TIPI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET KULLANILAN_HELA_TIPI = 'BELİRTİLMEDİ' WHERE KULLANILAN_HELA_TIPI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET YATAGA_BAGIMLILIK = 'BELİRTİLMEDİ' WHERE YATAGA_BAGIMLILIK IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET KULLANDIGI_YARDIMCI_ARACLAR = 'BELİRTİLMEDİ' WHERE KULLANDIGI_YARDIMCI_ARACLAR IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET PSIKOLOJIK_DURUM_DEGERLENDIRME = 'BELİRTİLMEDİ' WHERE PSIKOLOJIK_DURUM_DEGERLENDIRME IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET EVDE_SAGLIK_HIZMETININ_SONLANDIRILMASI = 'BELİRTİLMEDİ' WHERE EVDE_SAGLIK_HIZMETININ_SONLANDIRILMASI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET EVDE_SAGLIK_HIZMETLERI_HASTA_NAKLI = 'BELİRTİLMEDİ' WHERE EVDE_SAGLIK_HIZMETLERI_HASTA_NAKLI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET BIR_SONRAKI_HIZMET_IHTIYACI = 'BELİRTİLMEDİ' WHERE BIR_SONRAKI_HIZMET_IHTIYACI IS NULL;
UPDATE [Lbys].[EVDE_SAGLIK_IZLEM] SET VERILEN_EGITIMLER = 'BELİRTİLMEDİ' WHERE VERILEN_EGITIMLER IS NULL;

-- EK_ODEME_DETAY
UPDATE [Lbys].[EK_ODEME_DETAY] SET KLINIKLER = 'BELİRTİLMEDİ' WHERE KLINIKLER IS NULL;

-- DOGUM_DETAY
UPDATE [Lbys].[DOGUM_DETAY] SET PROGNOZ_BILGISI = 'BELİRTİLMEDİ' WHERE PROGNOZ_BILGISI IS NULL;
UPDATE [Lbys].[DOGUM_DETAY] SET SURMATURE_BILGISI = 'BELİRTİLMEDİ' WHERE SURMATURE_BILGISI IS NULL;
UPDATE [Lbys].[DOGUM_DETAY] SET K_VITAMINI_UYGULANMA_DURUMU = 'BELİRTİLMEDİ' WHERE K_VITAMINI_UYGULANMA_DURUMU IS NULL;
UPDATE [Lbys].[DOGUM_DETAY] SET BEBEGIN_HEPATIT_ASI_DURUMU = 'BELİRTİLMEDİ' WHERE BEBEGIN_HEPATIT_ASI_DURUMU IS NULL;
UPDATE [Lbys].[DOGUM_DETAY] SET YENIDOGAN_ISITME_TARAMA_DURUMU = 'BELİRTİLMEDİ' WHERE YENIDOGAN_ISITME_TARAMA_DURUMU IS NULL;
UPDATE [Lbys].[DOGUM_DETAY] SET SEZARYEN_ENDIKASYONLAR = 'BELİRTİLMEDİ' WHERE SEZARYEN_ENDIKASYONLAR IS NULL;
UPDATE [Lbys].[DOGUM_DETAY] SET ROBSON_GRUP = 'BELİRTİLMEDİ' WHERE ROBSON_GRUP IS NULL;

-- DISPROTEZ_DETAY
UPDATE [Lbys].[DISPROTEZ_DETAY] SET DISPROTEZ_IS_TURU_ASAMA_KODU = 'BELİRTİLMEDİ' WHERE DISPROTEZ_IS_TURU_ASAMA_KODU IS NULL;
UPDATE [Lbys].[DISPROTEZ_DETAY] SET ASAMA_RPT_SEBEBI = 'BELİRTİLMEDİ' WHERE ASAMA_RPT_SEBEBI IS NULL;

-- DIS_TAAHHUT_DETAY
UPDATE [Lbys].[DIS_TAAHHUT_DETAY] SET DIS_KODU = 'BELİRTİLMEDİ' WHERE DIS_KODU IS NULL;
UPDATE [Lbys].[DIS_TAAHHUT_DETAY] SET CENE_KODU = 'BELİRTİLMEDİ' WHERE CENE_KODU IS NULL;

-- COCUK_DIYABET
UPDATE [Lbys].[COCUK_DIYABET] SET DIYABET_ESLIK_EDEN_HASTALIK = 'BELİRTİLMEDİ' WHERE DIYABET_ESLIK_EDEN_HASTALIK IS NULL;
UPDATE [Lbys].[COCUK_DIYABET] SET DIYET_TEDAVISI_TIBBI_BESLENME_TEDAVISI = 'BELİRTİLMEDİ' WHERE DIYET_TEDAVISI_TIBBI_BESLENME_TEDAVISI IS NULL;

-- CIHAZ
UPDATE [Lbys].[CIHAZ] SET CIHAZ_GRUBU = 'BELİRTİLMEDİ' WHERE CIHAZ_GRUBU IS NULL;

-- BIRIM
UPDATE [Lbys].[BIRIM] SET KLINIKLER = 'BELİRTİLMEDİ' WHERE KLINIKLER IS NULL;

-- BINA
UPDATE [Lbys].[BINA] SET KURUMLAR = 'BELİRTİLMEDİ' WHERE KURUMLAR IS NULL;

-- BILDIRIMI_ZORUNLU
UPDATE [Lbys].[BILDIRIMI_ZORUNLU] SET INTIHAR_GIRISIMI_YADA_KRIZ_NEDENLERI = 'BELİRTİLMEDİ' WHERE INTIHAR_GIRISIMI_YADA_KRIZ_NEDENLERI IS NULL;

-- BEBEK_COCUK_IZLEM
UPDATE [Lbys].[BEBEK_COCUK_IZLEM] SET D_VITAMINI_LOJISTIGI_VE_DESTEGI = 'BELİRTİLMEDİ' WHERE D_VITAMINI_LOJISTIGI_VE_DESTEGI IS NULL;
UPDATE [Lbys].[BEBEK_COCUK_IZLEM] SET KURUMLAR = 'BELİRTİLMEDİ' WHERE KURUMLAR IS NULL;
UPDATE [Lbys].[BEBEK_COCUK_IZLEM] SET GELISIM_TABLOSU_BILGILERININ_SORGULANMASI = 'BELİRTİLMEDİ' WHERE GELISIM_TABLOSU_BILGILERININ_SORGULANMASI IS NULL;
UPDATE [Lbys].[BEBEK_COCUK_IZLEM] SET BEBEGIN_COCUGUN_BEYIN_GELISIMINI_ETKILEYEBILECEK_RISKLER = 'BELİRTİLMEDİ' WHERE BEBEGIN_COCUGUN_BEYIN_GELISIMINI_ETKILEYEBILECEK_RISKLER IS NULL;
UPDATE [Lbys].[BEBEK_COCUK_IZLEM] SET BEBEGIN_COCUGUN_PSIKOLOJIK_GELISIMINDEKI_RISKLERE_YONELIK_EGITIMLER = 'BELİRTİLMEDİ' WHERE BEBEGIN_COCUGUN_PSIKOLOJIK_GELISIMINDEKI_RISKLERE_YONELIK_EGITIMLER IS NULL;
UPDATE [Lbys].[BEBEK_COCUK_IZLEM] SET BEBEGIN_COCUGUN_RISK_FAKTORLERINE_YAPILAN_MUDAHALE = 'BELİRTİLMEDİ' WHERE BEBEGIN_COCUGUN_RISK_FAKTORLERINE_YAPILAN_MUDAHALE IS NULL;

-- ASI_BILGISI
UPDATE [Lbys].[ASI_BILGISI] SET ASI_KODU = 'BELİRTİLMEDİ' WHERE ASI_KODU IS NULL;
UPDATE [Lbys].[ASI_BILGISI] SET ASININ_DOZU = 'BELİRTİLMEDİ' WHERE ASININ_DOZU IS NULL;
UPDATE [Lbys].[ASI_BILGISI] SET ASININ_UYGULAMA_SEKLI = 'BELİRTİLMEDİ' WHERE ASININ_UYGULAMA_SEKLI IS NULL;
UPDATE [Lbys].[ASI_BILGISI] SET ASI_UYGULAMA_YERI = 'BELİRTİLMEDİ' WHERE ASI_UYGULAMA_YERI IS NULL;

PRINT 'Tüm NULL değerler BELİRTİLMEDİ olarak güncellendi.';
GO
