-- Tüm tabloları güncelleyen kapsamlı script
-- Tarih: 2026-01-10
USE [TESTDATA]
GO

SET NOCOUNT ON;

-- Log tablosu
CREATE TABLE #UpdateLog (
    ID INT IDENTITY(1,1),
    TableName NVARCHAR(128),
    ColumnName NVARCHAR(128),
    RefKodTuru NVARCHAR(128),
    RowsUpdated INT,
    Status NVARCHAR(200)
);

-- Güncellenecek tablo/kolon listesi (veritabanındaki gerçek isimler)
DECLARE @updates TABLE (
    ID INT IDENTITY(1,1),
    TableName NVARCHAR(128),
    ColumnName NVARCHAR(128),
    RefKodTuru NVARCHAR(128)
);

INSERT INTO @updates (TableName, ColumnName, RefKodTuru) VALUES
-- ASI_BILGISI
('ASI_BILGISI', 'ASI_KODU', 'ASI_KODU'),
('ASI_BILGISI', 'ASININ_DOZU', 'ASININ_DOZU'),
('ASI_BILGISI', 'ASININ_UYGULAMA_SEKLI', 'ASININ_UYGULAMA_SEKLI'),
('ASI_BILGISI', 'ASI_UYGULAMA_YERI', 'ASI_UYGULAMA_YERI'),
('ASI_BILGISI', 'ASI_ISLEM_TURU', 'ASI_ISLEM_TURU'),
('ASI_BILGISI', 'ASI_OZEL_DURUM_NEDENI', 'ASI_OZEL_DURUM_NEDENI'),
('ASI_BILGISI', 'ASIE_NEDENLERI', 'ASI_NEDENLERI'),
('ASI_BILGISI', 'ASI_YAPILMAMA_DURUMU', 'ASI_YAPILMAMA_DURUMU'),
('ASI_BILGISI', 'ASI_YAPILMAMA_NEDENI', 'ASI_YAPILMAMA_NEDENI'),
-- BEBEK_COCUK_IZLEM
('BEBEK_COCUK_IZLEM', 'DVITAMINI_LOJISTIGI_VE_DESTEGI', 'D_VITAMINI_LOJISTIGI_VE_DESTEGI'),
('BEBEK_COCUK_IZLEM', 'IZLEMIN_YAPILDIGI_YER', 'KURUMLAR'),
('BEBEK_COCUK_IZLEM', 'GELISIM_TABLOSU_BILGILERI', 'GELISIM_TABLOSU_BILGILERININ_SORGULANMASI'),
('BEBEK_COCUK_IZLEM', 'BC_BEYIN_GELISIM_RISKLERI', 'BEBEGIN_COCUGUN_BEYIN_GELISIMINI_ETKILEYEBILECEK_RISKLER'),
('BEBEK_COCUK_IZLEM', 'BC_PSIKOLOJIK_RISK_EGITIM', 'BEBEGIN_COCUGUN_PSIKOLOJIK_GELISIMINDEKI_RISKLERE_YONELIK_EGITIMLER'),
('BEBEK_COCUK_IZLEM', 'BC_RISK_YAPILAN_MUDAHALE', 'BEBEGIN_COCUGUN_RISK_FAKTORLERINE_YAPILAN_MUDAHALE'),
-- BILDIRIMI_ZORUNLU
('BILDIRIMI_ZORUNLU', 'INTIHAR_GIRISIM_KRIZ_NEDENLERI', 'INTIHAR_GIRISIMI_YADA_KRIZ_NEDENLERI'),
-- BINA
('BINA', 'SKRS_KURUM_KODU', 'KURUMLAR'),
-- BIRIM - KLINIKLER kolonu yok, KLINIK_KODU var ama FK değil
-- CIHAZ
('CIHAZ', 'CIHAZ_GRUBU', 'CIHAZ_GRUBU'),
-- COCUK_DIYABET
('COCUK_DIYABET', 'ESLIKEDEN_HASTALIK', 'DIYABET_ESLIK_EDEN_HASTALIK'),
('COCUK_DIYABET', 'DIYET_TIBBI_BESLENME_TEDAVISI', 'DIYET_TEDAVISI_TIBBI_BESLENME_TEDAVISI'),
-- DIS_TAAHHUT_DETAY
('DIS_TAAHHUT_DETAY', 'DIS_KODU', 'DIS_KODU'),
('DIS_TAAHHUT_DETAY', 'CENE_KODU', 'CENE_KODU'),
-- DISPROTEZ_DETAY
('DISPROTEZ_DETAY', 'DISPROTEZ_IS_TURU_ASAMA_KODU', 'DISPROTEZ_IS_TURU_ASAMA_KODU'),
('DISPROTEZ_DETAY', 'ASAMA_RPT_SEBEBI', 'ASAMA_RPT_SEBEBI'),
-- DOGUM_DETAY
('DOGUM_DETAY', 'PROGNOZ_BILGISI', 'PROGNOZ_BILGISI'),
('DOGUM_DETAY', 'SURMATURE_BILGISI', 'SURMATURE_BILGISI'),
('DOGUM_DETAY', 'K_VITAMINI_UYGULANMA_DURUMU', 'K_VITAMINI_UYGULANMA_DURUMU'),
('DOGUM_DETAY', 'BEBEGIN_HEPATIT_ASI_DURUMU', 'BEBEGIN_HEPATIT_ASI_DURUMU'),
('DOGUM_DETAY', 'YENIDOGAN_ISITME_TARAMA_DURUMU', 'YENIDOGAN_ISITME_TARAMA_DURUMU'),
('DOGUM_DETAY', 'SEZARYEN_ENDIKASYONLAR', 'SEZARYEN_ENDIKASYONLAR'),
('DOGUM_DETAY', 'ROBSON_GRUBU', 'ROBSON_GRUP'),
-- EVDE_SAGLIK_IZLEM
('EVDE_SAGLIK_IZLEM', 'AGRI', 'AGRI'),
('EVDE_SAGLIK_IZLEM', 'AYDINLATMA', 'AYDINLATMA'),
('EVDE_SAGLIK_IZLEM', 'BAKIM_VE_DESTEK_IHTIYACI', 'BAKIM_VE_DESTEK_IHTIYACI'),
('EVDE_SAGLIK_IZLEM', 'BASI_DEGERLENDIRMESI', 'BASI_DEGERLENDIRMESI'),
('EVDE_SAGLIK_IZLEM', 'BASVURU_TURU', 'BASVURU_TURU'),
('EVDE_SAGLIK_IZLEM', 'BESLENME', 'BESLENME'),
('EVDE_SAGLIK_IZLEM', 'EV_HIJYENI', 'EV_HIJYENI'),
('EVDE_SAGLIK_IZLEM', 'GUVENLIK', 'GUVENLIK'),
('EVDE_SAGLIK_IZLEM', 'ISINMA', 'ISINMA'),
('EVDE_SAGLIK_IZLEM', 'KISISEL_BAKIM', 'KISISEL_BAKIM'),
('EVDE_SAGLIK_IZLEM', 'KISISEL_HIJYEN', 'KISISEL_HIJYEN'),
('EVDE_SAGLIK_IZLEM', 'KONUT_TIPI', 'KONUT_TIPI'),
('EVDE_SAGLIK_IZLEM', 'KULLANILAN_HELA_TIPI', 'KULLANILAN_HELA_TIPI'),
('EVDE_SAGLIK_IZLEM', 'YATAGA_BAGIMLILIK', 'YATAGA_BAGIMLILIK'),
('EVDE_SAGLIK_IZLEM', 'KULLANDIGI_YARDIMCI_ARACLAR', 'KULLANDIGI_YARDIMCI_ARACLAR'),
('EVDE_SAGLIK_IZLEM', 'PSIKOLOJIK_DURUM_DEGERLENDIRME', 'PSIKOLOJIK_DURUM_DEGERLENDIRME'),
('EVDE_SAGLIK_IZLEM', 'EVDE_SAGLIK_HIZMETININ_SONLANDIRILMASI', 'EVDE_SAGLIK_HIZMETININ_SONLANDIRILMASI'),
('EVDE_SAGLIK_IZLEM', 'EVDE_SAGLIK_HIZMETLERI_HASTA_NAKLI', 'EVDE_SAGLIK_HIZMETLERI_HASTA_NAKLI'),
('EVDE_SAGLIK_IZLEM', 'BIR_SONRAKI_HIZMET_IHTIYACI', 'BIR_SONRAKI_HIZMET_IHTIYACI'),
('EVDE_SAGLIK_IZLEM', 'VERILEN_EGITIMLER', 'VERILEN_EGITIMLER'),
-- GEBE_IZLEM
('GEBE_IZLEM', 'DVITAMINI_LOJISTIGI_VE_DESTEGI', 'D_VITAMINI_LOJISTIGI_VE_DESTEGI'),
('GEBE_IZLEM', 'BC_BEYIN_GELISIM_RISKLERI', 'BEBEGIN_COCUGUN_BEYIN_GELISIMINI_ETKILEYEBILECEK_RISKLER'),
('GEBE_IZLEM', 'BC_PSIKOLOJIK_RISK_EGITIM', 'BEBEGIN_COCUGUN_PSIKOLOJIK_GELISIMINDEKI_RISKLERE_YONELIK_EGITIMLER'),
('GEBE_IZLEM', 'BC_RISK_YAPILAN_MUDAHALE', 'BEBEGIN_COCUGUN_RISK_FAKTORLERINE_YAPILAN_MUDAHALE'),
('GEBE_IZLEM', 'BC_RISKLI_OLGU_TAKIBI', 'BEBEK_COCUKTA_SIK_IZLEME_ALINAN_RISK_ALTINDAKI_OLGUNUN_TAKIBI'),
-- HASTA
('HASTA', 'HASTA_TIPI', 'HASTA_TIPI'),
('HASTA', 'MESLEK', 'MESLEK'),
('HASTA', 'MUAYENE_ONCELIK_SIRASI', 'MUAYENE_ONCELIK_SIRASI'),
('HASTA', 'ENGELLILIK_DURUMU', 'ENGELLILIK_DURUMU'),
-- HASTA_ARSIV
('HASTA_ARSIV', 'DEFTER_TURU', 'DEFTER_TURU'),
-- HASTA_BASVURU
('HASTA_BASVURU', 'MUAYENE_ONCELIK_SIRASI', 'MUAYENE_ONCELIK_SIRASI'),
('HASTA_BASVURU', 'OLAY_AFET_KODU', 'OLAY_AFET_KODU'),
('HASTA_BASVURU', 'HAYATI_TEHLIKE_DURUMU', 'HAYATI_TEHLIKE_DURUMU'),
('HASTA_BASVURU', 'KABUL_SEKLI', 'KABUL_SEKLI'),
('HASTA_BASVURU', 'SOSYAL_GUVENCE_DURUMU', 'SOSYAL_GUVENCE_DURUMU'),
('HASTA_BASVURU', 'VAKA_TURU', 'VAKA_TURU'),
('HASTA_BASVURU', 'ADLI_VAKA_GELIS_SEKLI', 'ADLI_VAKA_GELIS_SEKLI'),
('HASTA_BASVURU', 'ARAC_TURU', 'ARAC_TURU'),
('HASTA_BASVURU', 'TRIAJ_KODU', 'TRIAJ_KODU'),
('HASTA_BASVURU', 'YATIS_BILGISI', 'YATIS_BILGISI'),
('HASTA_BASVURU', 'BASVURU_DURUMU', 'BASVURU_DURUMU'),
('HASTA_BASVURU', 'MUAYENE_TURU', 'MUAYENE_TURU'),
('HASTA_BASVURU', 'YABANCI_HASTA_TURU', 'YABANCI_HASTA_TURU'),
('HASTA_BASVURU', 'GENCLIK_SAGLIGI_ISLEMLERI', 'GENCLIK_SAGLIGI_ISLEMLERI'),
-- HASTA_DIS
('HASTA_DIS', 'DIS_ISLEM_TURU', 'DIS_ISLEM_TURU'),
('HASTA_DIS', 'MEVCUT_DIS_DURUMU', 'MEVCUT_DIS_DURUMU'),
('HASTA_DIS', 'DIS_KODU', 'DIS_KODU'),
('HASTA_DIS', 'CENE_BOLGESI', 'CENE_BOLGESI'),
-- HASTA_HIZMET
('HASTA_HIZMET', 'HASTA_HIZMET_DURUMU', 'HASTA_HIZMET_DURUMU'),
('HASTA_HIZMET', 'HIZMET_FATURA_DURUMU', 'HIZMET_FATURA_DURUMU'),
('HASTA_HIZMET', 'TIBBI_ISLEM_PUAN_BILGISI', 'TIBBI_ISLEM_PUAN_BILGISI'),
-- HASTA_ILETISIM
('HASTA_ILETISIM', 'ADRES_TIPI', 'ADRES_TIPI'),
('HASTA_ILETISIM', 'ADRES_KODU_SEVIYESI', 'ADRES_KODU_SEVIYESI'),
('HASTA_ILETISIM', 'BUCAK_KODU', 'BUCAK_KODU'),
('HASTA_ILETISIM', 'KOY_KODU', 'KOY_KODU'),
('HASTA_ILETISIM', 'MAHALLE_KODU', 'MAHALLE_KODU'),
-- HASTA_MALZEME
('HASTA_MALZEME', 'HIZMET_FATURA_DURUMU', 'HIZMET_FATURA_DURUMU'),
-- HASTA_SEANS
('HASTA_SEANS', 'SEANS_ISLEM_TURU', 'SEANS_ISLEM_TURU'),
('HASTA_SEANS', 'ANTIHIPERTANSIF_ILAC_DURUMU', 'ANTIHIPERTANSIF_ILAC_DURUMU'),
('HASTA_SEANS', 'ONCEKI_RRT_YONTEMI', 'ONCEKI_RRT_YONTEMI'),
('HASTA_SEANS', 'HEMODIYALIZE_GECME_NEDENLERI', 'HEMODIYALIZE_GECME_NEDENLERI'),
('HASTA_SEANS', 'DAMAR_ERISIM_YOLU', 'DAMAR_ERISIM_YOLU'),
('HASTA_SEANS', 'DIYALIZE_GIRME_SIKLIGI', 'DIYALIZE_GIRME_SIKLIGI'),
('HASTA_SEANS', 'DIYALIZOR_ALANI', 'DIYALIZOR_ALANI'),
('HASTA_SEANS', 'DIYALIZOR_TIPI', 'DIYALIZOR_TIPI'),
('HASTA_SEANS', 'KAN_AKIM_HIZI', 'KAN_AKIM_HIZI'),
('HASTA_SEANS', 'AGIRLIK_OLCUM_ZAMANI', 'AGIRLIK_OLCUM_ZAMANI'),
('HASTA_SEANS', 'KULLANILAN_DIYALIZ_TEDAVISI', 'KULLANILAN_DIYALIZ_TEDAVISI'),
('HASTA_SEANS', 'PERITONEAL_GECIRGENLIK_DURUMU', 'PERITONEAL_GECIRGENLIK_DURUMU'),
('HASTA_SEANS', 'PERITON_KACINCI_KATETER', 'PERITON_KACINCI_KATETER'),
('HASTA_SEANS', 'PERITON_KATETER_TIPI', 'PERITON_KATETER_TIPI'),
('HASTA_SEANS', 'PERITON_KATETER_YONTEMI', 'PERITON_KATETER_YONTEMI'),
('HASTA_SEANS', 'PERITON_TUNEL_YONU', 'PERITON_TUNEL_YONU'),
('HASTA_SEANS', 'SINEKALSET', 'SINEKALSET'),
('HASTA_SEANS', 'TEDAVININ_SEYRI', 'TEDAVININ_SEYRI'),
('HASTA_SEANS', 'AKTIF_VITAMIN_D_KULLANIMI', 'AKTIF_VITAMIN_D_KULLANIMI'),
('HASTA_SEANS', 'ANEMI_TEDAVISI_YONTEMI', 'ANEMI_TEDAVISI_YONTEMI'),
('HASTA_SEANS', 'FOSFOR_BAGLAYICI_AJAN', 'FOSFOR_BAGLAYICI_AJAN'),
('HASTA_SEANS', 'PERITON_KOMPLIKASYON', 'PERITON_KOMPLIKASYON'),
-- HASTA_SEVK
('HASTA_SEVK', 'SEVK_NEDENI', 'SEVK_NEDENI'),
('HASTA_SEVK', 'SEVK_SEKLI', 'SEVK_SEKLI'),
('HASTA_SEVK', 'SEVK_VASITASI_KODU', 'SEVK_VASITASI_KODU'),
('HASTA_SEVK', 'SEVK_TEDAVI_TIPI', 'SEVK_TEDAVI_TIPI'),
-- HEMOGLOBINOPATI
('HEMOGLOBINOPATI', 'HEMOGLOBINOPATI_TARAMA_TESTI_SONUCU', 'HEMOGLOBINOPATI_TARAMA_TESTI_SONUCU'),
('HEMOGLOBINOPATI', 'HEMOGLOBINOPATI_TEST_SONUCU_HASTALIK_TURU', 'HEMOGLOBINOPATI_TEST_SONUCU_HASTALIK_TURU'),
('HEMOGLOBINOPATI', 'HEMOGLOBINOPATI_TEST_SONUCU_TASIYICILIK_TURU', 'HEMOGLOBINOPATI_TEST_SONUCU_TASIYICILIK_TURU'),
-- HEMSIRE_BAKIM
('HEMSIRE_BAKIM', 'HEMSIRELIK_TANI_KODU', 'HEMSIRELIK_TANI_KODU'),
-- HIZMET
('HIZMET', 'ISLEM_GRUBU', 'ISLEM_GRUBU'),
('HIZMET', 'HIZMET_ISLEM_TURU', 'HIZMET_ISLEM_TURU'),
('HIZMET', 'TIBBI_ISLEM_PUAN_BILGISI', 'TIBBI_ISLEM_PUAN_BILGISI'),
-- ILAC_UYUM
('ILAC_UYUM', 'ILAC_UYUMSUZLUK_TURU', 'ILAC_UYUMSUZLUK_TURU'),
('ILAC_UYUM', 'BIRINCI_ILAC_BARKODU', 'BIRINCI_ILAC_BARKODU'),
('ILAC_UYUM', 'BIRINCI_ETKEN_MADDE_KODU', 'BIRINCI_ETKEN_MADDE_KODU'),
('ILAC_UYUM', 'IKINCI_ILAC_BARKODU', 'IKINCI_ILAC_BARKODU'),
('ILAC_UYUM', 'IKINCI_ETKEN_MADDE_KODU', 'IKINCI_ETKEN_MADDE_KODU'),
('ILAC_UYUM', 'BESIN_KODU', 'BESIN_KODU'),
('ILAC_UYUM', 'RENK_SEVIYE_KODU', 'RENK_SEVIYE_KODU'),
-- INTIHAR_IZLEM
('INTIHAR_IZLEM', 'INTIHAR_GIRISIM_KRIZ_NEDENLERI', 'INTIHAR_GIRISIMI_YADA_KRIZ_NEDENLERI'),
-- KADIN_IZLEM
('KADIN_IZLEM', 'KULLANILAN_AILE_PLANLAMASI_YONTEMI', 'KULLANILAN_AILE_PLANLAMASI_YONTEMI'),
('KADIN_IZLEM', 'BIR_ONCEKI_KULLANILAN_AILE_PLANLAMASI_YONTEM', 'BIR_ONCEKI_KULLANILAN_AILE_PLANLAMASI_YONTEM'),
('KADIN_IZLEM', 'AILE_PLANLAMASI_YONTEMI_LOJISTIGI', 'AILE_PLANLAMASI_YONTEMI_LOJISTIGI'),
('KADIN_IZLEM', 'KADIN_SAGLIGI_ISLEMLERI', 'KADIN_SAGLIGI_ISLEMLERI'),
-- KLINIK_SEYIR
('KLINIK_SEYIR', 'DURUM', 'DURUM'),
-- KUDUZ_IZLEM
('KUDUZ_IZLEM', 'PROFILAKSI_TAMAMLANMA_DURUMU', 'PROFILAKSI_TAMAMLANMA_DURUMU'),
('KUDUZ_IZLEM', 'UYGULANAN_KUDUZ_PROFILAKSISI', 'UYGULANAN_KUDUZ_PROFILAKSISI'),
-- KULLANICI
('KULLANICI', 'PAROLA_SIFRELEME_TURU', 'PAROLA_SIFRELEME_TURU'),
-- KURUL_ASKERI
('KURUL_ASKERI', 'DURUM', 'DURUM'),
('KURUL_ASKERI', 'ASAL_HASTALIK', 'ASAL_HASTALIK'),
('KURUL_ASKERI', 'ASAL_HASTALIK_TIPI', 'ASAL_HASTALIK_TIPI'),
-- KURUL_ETKEN_MADDE
('KURUL_ETKEN_MADDE', 'ILAC_PERIYOT_BIRIMI', 'ILAC_PERIYOT_BIRIMI'),
-- KURUM
('KURUM', 'HASTA_KURUM_TURU', 'HASTA_KURUM_TURU'),
-- LOHUSA_IZLEM
('LOHUSA_IZLEM', 'KACINCI_LOHUSA_IZLEM', 'KACINCI_LOHUSA_IZLEM'),
('LOHUSA_IZLEM', 'IZLEMIN_YAPILDIGI_YER', 'KURUMLAR'),
('LOHUSA_IZLEM', 'DVITAMINI_LOJISTIGI_VE_DESTEGI', 'D_VITAMINI_LOJISTIGI_VE_DESTEGI'),
('LOHUSA_IZLEM', 'POSTPARTUM_DEPRESYON', 'POSTPARTUM_DEPRESYON'),
('LOHUSA_IZLEM', 'UTERUS_INVOLUSYON', 'UTERUS_INVOLUSYON'),
('LOHUSA_IZLEM', 'SEYIR_TEHLIKE_ISARETI', 'SEYIR_TEHLIKE_ISARETI'),
('LOHUSA_IZLEM', 'KADIN_SAGLIGI_ISLEMLERI', 'KADIN_SAGLIGI_ISLEMLERI'),
-- MADDE_BAGIMLILIGI
('MADDE_BAGIMLILIGI', 'BILGI_ALINAN_KISI', 'BILGI_ALINAN_KISI'),
('MADDE_BAGIMLILIGI', 'DANISMA_TEDAVI_HIZMET_ALMA_DURUMU', 'DANISMA_TEDAVI_HIZMET_ALMA_DURUMU'),
('MADDE_BAGIMLILIGI', 'IKAME_TEDAVISI_GORME_DURUMU', 'IKAME_TEDAVISI_GORME_DURUMU'),
('MADDE_BAGIMLILIGI', 'COCUKLARIYLA_YASAM_DURUMU', 'COCUKLARIYLA_YASAM_DURUMU'),
('MADDE_BAGIMLILIGI', 'YASAMINDA_ENJEKSIYON_YOLU_ILE_MADDE_KULLANIM_DURUMU', 'YASAMINDA_ENJEKSIYON_YOLU_ILE_MADDE_KULLANIM_DURUMU'),
('MADDE_BAGIMLILIGI', 'TEST_YAPILMA_DURUMU', 'TEST_YAPILMA_DURUMU'),
('MADDE_BAGIMLILIGI', 'TEDAVI_SONUCU', 'TEDAVI_SONUCU'),
('MADDE_BAGIMLILIGI', 'UYGULANAN_TEDAVI_TURU', 'UYGULANAN_TEDAVI_TURU'),
('MADDE_BAGIMLILIGI', 'KULLANILAN_MADDE', 'KULLANILAN_MADDE'),
-- MEDULA_TAKIP
('MEDULA_TAKIP', 'PROVIZYON_TURU', 'PROVIZYON_TURU'),
('MEDULA_TAKIP', 'TAKIP_TIPI', 'TAKIP_TIPI'),
('MEDULA_TAKIP', 'TEDAVI_TIPI', 'TEDAVI_TIPI'),
('MEDULA_TAKIP', 'TEDAVI_SEKLI', 'TEDAVI_SEKLI'),
-- NOBETCI_PERSONEL_BILGISI
('NOBETCI_PERSONEL_BILGISI', 'KURUM_KODU', 'KURUMLAR'),
('NOBETCI_PERSONEL_BILGISI', 'KLINIK_KODU', 'KLINIKLER'),
-- OBEZITE_IZLEM
('OBEZITE_IZLEM', 'MORBIT_OBEZ_HASTA_LENFATIK_ODEM_VARLIGI', 'MORBIT_OBEZ_HASTA_LENFATIK_ODEM_VARLIGI'),
-- OPTIK_RECETE
('OPTIK_RECETE', 'GOZLUK_RECETE_TIPI', 'GOZLUK_RECETE_TIPI'),
('OPTIK_RECETE', 'GOZLUK_TURU', 'GOZLUK_TURU'),
('OPTIK_RECETE', 'SAG_CAM_TIPI', 'SAG_CAM_TIPI'),
('OPTIK_RECETE', 'SAG_CAM_RENGI', 'SAG_CAM_RENGI'),
('OPTIK_RECETE', 'SOL_CAM_TIPI', 'SOL_CAM_TIPI'),
('OPTIK_RECETE', 'SOL_CAM_RENGI', 'SOL_CAM_RENGI'),
('OPTIK_RECETE', 'TELESKOPIK_GOZLUK_TIPI', 'TELESKOPIK_GOZLUK_TIPI'),
('OPTIK_RECETE', 'TELESKOPIK_GOZLUK_TURU', 'TELESKOPIK_GOZLUK_TURU'),
-- PATOLOJI
('PATOLOJI', 'PATOLOJI_RAPOR_TURU', 'PATOLOJI_RAPOR_TURU'),
('PATOLOJI', 'NUMUNENIN_ALINDIGI_DOKUNUN_TEMEL_OZELLIGI', 'NUMUNENIN_ALINDIGI_DOKUNUN_TEMEL_OZELLIGI'),
('PATOLOJI', 'NUMUNE_ALINMA_SEKLI', 'NUMUNE_ALINMA_SEKLI'),
('PATOLOJI', 'PATOLOJI_PREPARATI_DURUMU', 'PATOLOJI_PREPARATI_DURUMU'),
('PATOLOJI', 'NUMUNE_ALINMA_YERI', 'NUMUNE_ALINMA_YERI'),
('PATOLOJI', 'PATOLOJIK_TANI_MORFOLOJI_KODU', 'PATOLOJIK_TANI_MORFOLOJI_KODU'),
('PATOLOJI', 'PATOLOJIK_TANI_YERLESIM_YERI', 'PATOLOJIK_TANI_YERLESIM_YERI'),
('PATOLOJI', 'SONUC_ICERIK_TURU', 'SONUC_ICERIK_TURU'),
-- PERSONEL
('PERSONEL', 'ADRES_TIPI', 'ADRES_TIPI'),
('PERSONEL', 'ADRES_KODU_SEVIYESI', 'ADRES_KODU_SEVIYESI'),
('PERSONEL', 'ASKERLIK_DURUMU', 'ASKERLIK_DURUMU'),
('PERSONEL', 'CALISMA_DURUMU', 'CALISMA_DURUMU'),
('PERSONEL', 'IS_DURUMU', 'IS_DURUMU'),
('PERSONEL', 'MEMURIYET_TIPI', 'MEMURIYET_TIPI'),
('PERSONEL', 'ISTEN_AYRILMA_NEDENI', 'ISTEN_AYRILMA_NEDENI'),
('PERSONEL', 'KADRO_UNVAN_KODU', 'KADRO_UNVAN_KODU'),
('PERSONEL', 'IMZA_UNVAN_KODU', 'IMZA_UNVAN_KODU'),
('PERSONEL', 'AKADEMIK_UNVAN', 'AKADEMIK_UNVAN'),
('PERSONEL', 'ENGELLILIK_DURUMU', 'ENGELLILIK_DURUMU'),
-- PERSONEL_BAKMAKLA_YUKUMLU
('PERSONEL_BAKMAKLA_YUKUMLU', 'YAKINLIK_DERECESI', 'YAKINLIK_DERECESI'),
('PERSONEL_BAKMAKLA_YUKUMLU', 'ENGELLILIK_DURUMU', 'ENGELLILIK_DURUMU'),
-- PERSONEL_EGITIM
('PERSONEL_EGITIM', 'PERSONEL_EGITIM_TURU', 'PERSONEL_EGITIM_TURU'),
('PERSONEL_EGITIM', 'SERTIFIKA_TIPI', 'SERTIFIKA_TIPI'),
-- PERSONEL_IZIN
('PERSONEL_IZIN', 'IZIN_TURU', 'IZIN_TURU'),
-- PERSONEL_ODUL_CEZA
('PERSONEL_ODUL_CEZA', 'ODUL_CEZA_TURU', 'ODUL_CEZA_TURU'),
-- RANDEVU
('RANDEVU', 'RANDEVU_ALT_TURU', 'RANDEVU_ALT_TURU'),
-- RECETE
('RECETE', 'RECETE_ALT_TURU', 'RECETE_ALT_TURU'),
-- RECETE_ILAC_ACIKLAMA
('RECETE_ILAC_ACIKLAMA', 'ILAC_ACIKLAMA_TURU', 'ILAC_ACIKLAMA_TURU');

-- Değişkenler
DECLARE @id INT = 1;
DECLARE @maxId INT = (SELECT MAX(ID) FROM @updates);
DECLARE @table NVARCHAR(128);
DECLARE @column NVARCHAR(128);
DECLARE @refKod NVARCHAR(128);
DECLARE @refKodu NVARCHAR(128);
DECLARE @sql NVARCHAR(MAX);
DECLARE @updated INT;
DECLARE @hasFk BIT;

PRINT 'Toplam ' + CAST(@maxId AS VARCHAR) + ' kolon işlenecek...';
PRINT '';

WHILE @id <= @maxId
BEGIN
    SELECT @table = TableName, @column = ColumnName, @refKod = RefKodTuru FROM @updates WHERE ID = @id;
    SET @refKodu = @refKod + '_0';

    -- Kolon var mı kontrol et
    IF EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'Lbys' AND TABLE_NAME = @table AND COLUMN_NAME = @column
    )
    BEGIN
        -- FK var mı kontrol et
        SET @hasFk = 0;
        IF EXISTS (
            SELECT 1 FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu
            INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ON ccu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
            WHERE tc.CONSTRAINT_TYPE = 'FOREIGN KEY' AND ccu.TABLE_SCHEMA = 'Lbys'
            AND ccu.TABLE_NAME = @table AND ccu.COLUMN_NAME = @column
        )
        BEGIN
            SET @hasFk = 1;

            -- Referans kodu var mı kontrol et, yoksa ekle
            IF NOT EXISTS (SELECT 1 FROM [Lbys].[REFERANS_KODLAR] WHERE REFERANS_KODU = @refKodu)
            BEGIN
                BEGIN TRY
                    INSERT INTO [Lbys].[REFERANS_KODLAR] (REFERANS_KODU, KOD_TURU, REFERANS_ADI, SKRS_KODU, MEDULA_KODU, MKYS_KODU, TIG_KODU)
                    VALUES (@refKodu, @refKod, N'BELİRTİLMEDİ', '', '', '', '');
                END TRY
                BEGIN CATCH
                END CATCH
            END
        END

        -- Update yap
        BEGIN TRY
            IF @hasFk = 1
                SET @sql = N'UPDATE [Lbys].[' + @table + N'] SET [' + @column + N'] = ''' + @refKodu + N''' WHERE [' + @column + N'] IS NULL';
            ELSE
                SET @sql = N'UPDATE [Lbys].[' + @table + N'] SET [' + @column + N'] = N''BELİRTİLMEDİ'' WHERE [' + @column + N'] IS NULL';

            EXEC sp_executesql @sql;
            SET @updated = @@ROWCOUNT;
            INSERT INTO #UpdateLog (TableName, ColumnName, RefKodTuru, RowsUpdated, Status)
            VALUES (@table, @column, @refKod, @updated, 'SUCCESS');
        END TRY
        BEGIN CATCH
            INSERT INTO #UpdateLog (TableName, ColumnName, RefKodTuru, RowsUpdated, Status)
            VALUES (@table, @column, @refKod, 0, 'ERROR: ' + LEFT(ERROR_MESSAGE(), 150));
        END CATCH
    END
    ELSE
    BEGIN
        INSERT INTO #UpdateLog (TableName, ColumnName, RefKodTuru, RowsUpdated, Status)
        VALUES (@table, @column, @refKod, 0, 'COLUMN_NOT_FOUND');
    END

    SET @id = @id + 1;
END

-- Sonuçları göster
PRINT '';
PRINT '=== SONUÇLAR ===';
PRINT '';

SELECT TableName, ColumnName, RowsUpdated, Status FROM #UpdateLog
WHERE RowsUpdated > 0 OR Status != 'SUCCESS'
ORDER BY
    CASE WHEN Status = 'SUCCESS' AND RowsUpdated > 0 THEN 1
         WHEN Status LIKE 'ERROR%' THEN 2
         ELSE 3 END,
    TableName, ColumnName;

-- Özet
PRINT '';
PRINT '=== ÖZET ===';
SELECT
    CASE
        WHEN Status = 'SUCCESS' AND RowsUpdated > 0 THEN 'GUNCELLENDI'
        WHEN Status = 'SUCCESS' AND RowsUpdated = 0 THEN 'ZATEN_DOLU'
        WHEN Status = 'COLUMN_NOT_FOUND' THEN 'KOLON_BULUNAMADI'
        ELSE 'HATA'
    END as Durum,
    COUNT(*) as KolonSayisi,
    SUM(RowsUpdated) as ToplamSatir
FROM #UpdateLog
GROUP BY
    CASE
        WHEN Status = 'SUCCESS' AND RowsUpdated > 0 THEN 'GUNCELLENDI'
        WHEN Status = 'SUCCESS' AND RowsUpdated = 0 THEN 'ZATEN_DOLU'
        WHEN Status = 'COLUMN_NOT_FOUND' THEN 'KOLON_BULUNAMADI'
        ELSE 'HATA'
    END;

DROP TABLE #UpdateLog;
PRINT '';
PRINT 'İşlem tamamlandı.';
GO
